import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { WrappedSidebar } from '../wrapped/components/WrappedSidebar';
import { wrappedDemoReport } from '../wrapped/wrappedDemoData';
import { getDeltaCard, listDeltasInView, loadDeltaCategories, loadDeltaCities, reactToDelta, DeltaApiError } from '../deltas/deltaApi';
import type { DeltaCard, DeltaCategory, DeltaCity, DeltaMapItem, DeltaReaction } from '../deltas/deltaTypes';
import { appMode, isDemoMode, isProductionConfigured } from '../../app/appMode';
import { DeltaMapCanvas } from './DeltaMapCanvas';
import { DeltaMapHeader } from './DeltaMapHeader';
import { DeltaMapFiltersView } from './DeltaMapFilters';
import { DeltaMapCard } from './DeltaMapCard';
import { DeltaMapState } from './DeltaMapState';
import { demoCard, demoDeltaMapData } from './demoDeltaMapData';
import { areFiltersActive, buildViewportInput, defaultDeltaMapFilters, deltaMatchesFilters, fallbackCategories, loadDeltaMapContext, PERM_FALLBACK, shouldShowDeltaOnMap, type DeltaMapFilters } from './deltaMapLogic';
import './deltaMap.css';

type Bounds = { minLat:number; minLng:number; maxLat:number; maxLng:number };
const token = import.meta.env.VITE_MAPBOX_ACCESS_TOKEN as string | undefined;
function cityCenter(city?: DeltaCity | null) { return city ? { lat: city.centerLat, lng: city.centerLng, zoom: city.defaultZoom } : PERM_FALLBACK; }
function isMissingMigration(error: unknown) { return error instanceof DeltaApiError && error.code === 'unknown'; }

export function DeltaMapPage() {
 const [filters,setFilters]=useState<DeltaMapFilters>(defaultDeltaMapFilters); const [categories,setCategories]=useState<DeltaCategory[]>(fallbackCategories); const [city,setCity]=useState<DeltaCity|null>(null); const [context,setContext]=useState<{circleId:string;citySlug:'perm'}|null>(isDemoMode?{circleId:'demo-circle',citySlug:'perm'}:null); const [status,setStatus]=useState<'loading'|'ready'|'empty'|'no-circle'|'missing-token'|'missing-migration'|'error'>(token?'loading':'missing-token'); const [deltas,setDeltas]=useState<DeltaMapItem[]>([]); const [bounds,setBounds]=useState<Bounds|null>(null); const [selectedId,setSelectedId]=useState<string|null>(null); const [card,setCard]=useState<DeltaCard|null>(null); const [cardLoading,setCardLoading]=useState(false); const [reacting,setReacting]=useState(false); const [effect,setEffect]=useState(''); const [cardError,setCardError]=useState(''); const [highlightedId,setHighlightedId]=useState<string|null>(null); const seq=useRef(0);
 const center = useMemo(()=>cityCenter(city),[city]);
 useEffect(()=>{ if (!token) return; let alive=true; void Promise.resolve().then(async()=>{ try { if (isDemoMode) { setCategories(fallbackCategories); setStatus('ready'); return; } if (appMode==='production' && !isProductionConfigured) { setStatus('no-circle'); return; } const ctx = await loadDeltaMapContext(); if (!alive) return; if (!ctx) { setStatus('no-circle'); return; } setContext(ctx); const [cats,cities]=await Promise.all([loadDeltaCategories(), loadDeltaCities()]); if (!alive) return; setCategories(cats.length?cats:fallbackCategories); setCity(cities.find(c=>c.slug==='perm')??null); setStatus('ready'); } catch(e) { setStatus(isMissingMigration(e)?'missing-migration':'error'); } }); return()=>{ alive=false; }; },[]);
 const fetchDeltas = useCallback(async (nextBounds: Bounds = bounds!)=>{ if (!token || !nextBounds) return; setBounds(nextBounds); const current=++seq.current; try { if (isDemoMode) { const rows=demoDeltaMapData.filter(d=>shouldShowDeltaOnMap(d)&&deltaMatchesFilters(d,filters)&&d.location.lat>=nextBounds.minLat&&d.location.lat<=nextBounds.maxLat&&d.location.lng>=nextBounds.minLng&&d.location.lng<=nextBounds.maxLng); setDeltas(rows); setStatus(rows.length?'ready':'empty'); return; } if (!context) return; setStatus((prev)=>deltas.length?prev:'loading'); const rows = await listDeltasInView(buildViewportInput(context,nextBounds,filters)); if (current!==seq.current) return; const visible=rows.filter(shouldShowDeltaOnMap); setDeltas(visible); setStatus(visible.length?'ready':'empty'); } catch(e) { if (current!==seq.current) return; setStatus(isMissingMigration(e)?'missing-migration':'error'); } },[bounds,context,filters,deltas.length]);
 useEffect(()=>{ if (!bounds) return; const id = window.setTimeout(()=>{ void fetchDeltas(bounds); },0); return ()=>window.clearTimeout(id); },[filters]);
 useEffect(()=>{ if (!(selectedId && !deltas.some(d=>d.id===selectedId && deltaMatchesFilters(d,filters)))) return; const id = window.setTimeout(()=>{ setSelectedId(null); setCard(null); },0); return ()=>window.clearTimeout(id); },[filters,deltas,selectedId]);
 const selectDelta=useCallback((delta:DeltaMapItem)=>{ setSelectedId(delta.id); setCardLoading(true); setEffect(''); setCardError(''); (async()=>{ try { const loaded = isDemoMode ? demoCard(delta.id) : await getDeltaCard(delta.id); setCard(loaded); } catch { setCardError('Не удалось открыть карточку дельты.'); } finally { setCardLoading(false); } })(); },[]);
 const handleReact=async(reaction:DeltaReaction)=>{ if(!selectedId||!card) return; setReacting(true); setCardError(''); try { if (isDemoMode) { const next={...card, viewerReaction:reaction, confirmCount:card.confirmCount+(reaction==='confirm'?1:0), disconfirmCount:card.disconfirmCount+(reaction==='disconfirm'?1:0), status: reaction==='disconfirm'?'fork':card.confirmCount+1>=card.confirmationTarget?'confirmed':'checking'} as DeltaCard; setCard(next); setDeltas(rows=>rows.map(d=>d.id===next.id?{...d,status:next.status,confirmCount:next.confirmCount,disconfirmCount:next.disconfirmCount,lastActivityAt:new Date().toISOString()}:d)); setEffect(reaction==='disconfirm'?'Вы создали развилку. В этом месте ситуацию видят по-разному.':'Ваш отклик усилил дельту. Она перешла в стадию проверки.'); setHighlightedId(next.id); return; } const result=await reactToDelta(selectedId,reaction); setEffect(`${result.effect.message}. ${result.effect.detail}`); setCard({...card,...result.delta,viewerReaction:reaction}); setDeltas(rows=>rows.map(d=>d.id===selectedId?{...d,status:result.delta.status,confirmCount:result.delta.confirmCount,disconfirmCount:result.delta.disconfirmCount,lastActivityAt:new Date().toISOString()}:d)); setHighlightedId(selectedId); void getDeltaCard(selectedId).then(setCard).catch(()=>undefined); } catch(e) { setCardError(e instanceof DeltaApiError && e.code==='author_reaction_locked' ? 'Первая отметка автора закреплена. Другие участники помогут проверить вашу дельту.' : 'Не удалось сохранить отклик. Попробуйте ещё раз.'); } finally { setReacting(false); window.setTimeout(()=>setHighlightedId(null),600); } };
 const resetFilters=()=>setFilters(defaultDeltaMapFilters);
 return <div className="delta-map-page"><WrappedSidebar report={wrappedDemoReport}/><main className="delta-map-main"><DeltaMapHeader loading={status==='loading' && deltas.length>0}/>{token && <DeltaMapFiltersView filters={filters} categories={categories} onChange={setFilters}/>} {!token ? <DeltaMapState kind="missing-token"/> : status==='no-circle' ? <DeltaMapState kind="no-circle"/> : status==='missing-migration' ? <DeltaMapState kind="missing-migration" onRetry={()=>bounds&&void fetchDeltas(bounds)}/> : <><DeltaMapCanvas token={token} city={center} deltas={deltas} selectedId={selectedId} highlightedId={highlightedId} onViewport={fetchDeltas} onSelect={selectDelta}/><Legend />{status==='loading'&&deltas.length===0&&<DeltaMapState kind="loading"/>}{status==='empty'&&<div className="delta-empty"><h2>В этой части карты пока нет дельт</h2><p>Переместите карту или сбросьте фильтры.</p><button onClick={()=>setCity(null)}>К центру Перми</button>{areFiltersActive(filters)&&<button onClick={resetFilters}>Сбросить фильтры</button>}<small>Добавление новой дельты появится на следующем этапе.</small></div>}{status==='error'&&<DeltaMapState kind="error" onRetry={()=>bounds&&void fetchDeltas(bounds)}/>}</>} {selectedId&&<DeltaMapCard card={card} loading={cardLoading} reacting={reacting} effect={effect} error={cardError} onClose={()=>{setSelectedId(null);setCard(null);}} onReact={handleReact}/>}</main></div>;
}
function Legend(){return <div className="delta-map-legend"><strong>Легенда</strong><p><i className="positive"/> зелёный — стало лучше</p><p><i className="negative"/> коралловый — стало хуже</p><p><i className="new"/> жёлтое — новая</p><p><i className="checking"/> янтарное — проверяется</p><p><i className="confirmed"/> светлое — подтверждена</p><p><i className="fork"/> фиолетовое двойное — развилка</p></div>}
