import { useEffect, useRef, useState } from 'react';
import type { DeltaCategory } from '../deltas/deltaTypes';
import type { DeltaMapFilters } from './deltaMapLogic';
import { defaultDeltaMapFilters } from './deltaMapLogic';
import { DeltaMapFiltersView } from './DeltaMapFilters';
import { DeltaMapHeader } from './DeltaMapHeader';

export function DeltaMapLegend(){return <div className="delta-map-legend"><strong>Легенда</strong><p><i className="positive"/> зелёный — стало лучше</p><p><i className="negative"/> коралловый — стало хуже</p><p><i className="new"/> жёлтое — новая</p><p><i className="checking"/> янтарное — проверяется</p><p><i className="confirmed"/> светлое — подтверждена</p><p><i className="fork"/> фиолетовое двойное — развилка</p></div>}
export function DesktopDeltaMapChrome({loading,filters,categories,onChange}:{loading:boolean;filters:DeltaMapFilters;categories:DeltaCategory[];onChange:(filters:DeltaMapFilters)=>void}){return <><DeltaMapHeader loading={loading}/><DeltaMapFiltersView filters={filters} categories={categories} onChange={onChange}/><DeltaMapLegend/></>}
export function MobileDeltaMapChrome({filters,categories,onChange,collapsed,onCollapsedChange}:{filters:DeltaMapFilters;categories:DeltaCategory[];onChange:(filters:DeltaMapFilters)=>void;collapsed:boolean;onCollapsedChange:(value:boolean)=>void}){const [open,setOpen]=useState(false);const [draft,setDraft]=useState(filters);const buttonRef=useRef<HTMLButtonElement>(null),sheetRef=useRef<HTMLDivElement>(null);const count=[filters.direction,filters.status,filters.categorySlug].filter(value=>value!=='all').length;
 const close=()=>{setOpen(false);window.setTimeout(()=>buttonRef.current?.focus(),0)};useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';sheetRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')close()};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key)}},[open,filters]);
 if(collapsed)return <div className="delta-mobile-toolbar is-collapsed"><button onClick={()=>onCollapsedChange(false)}>Пермь · показать панель</button></div>;
 return <><div className="delta-mobile-toolbar"><strong>Пермь</strong><button ref={buttonRef} onClick={()=>{setDraft(filters);setOpen(true)}}>Фильтры · {count}</button><button onClick={()=>onCollapsedChange(true)}>Скрыть</button></div>{open&&<div className="delta-filter-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)close()}}><div className="delta-filter-sheet" role="dialog" aria-modal="true" aria-labelledby="delta-filter-title" tabIndex={-1} ref={sheetRef}><header><h2 id="delta-filter-title">Фильтры</h2><button onClick={close} aria-label="Закрыть">×</button></header><FilterGroup title="Направление" value={draft.direction} options={[['all','Все'],['positive','Стало лучше'],['negative','Стало хуже']]} onChange={value=>setDraft({...draft,direction:value as DeltaMapFilters['direction']})}/><FilterGroup title="Статус" value={draft.status} options={[['all','Все'],['new','Новые'],['checking','Проверяются'],['confirmed','Подтверждены'],['fork','Развилки']]} onChange={value=>setDraft({...draft,status:value as DeltaMapFilters['status']})}/><FilterGroup title="Категория" value={draft.categorySlug} options={[['all','Все категории'],...categories.map(category=>[category.slug,category.title] as [string,string])]} onChange={value=>setDraft({...draft,categorySlug:value})}/><details><summary>Легенда</summary><DeltaMapLegend/></details><footer><button onClick={()=>setDraft(defaultDeltaMapFilters)}>Сбросить</button><button className="primary" onClick={()=>{onChange(draft);close()}}>Применить</button></footer></div></div>}</>}
function FilterGroup({title,value,options,onChange}:{title:string;value:string;options:[string,string][];onChange:(value:string)=>void}){return <fieldset><legend>{title}</legend>{options.map(([key,label])=><label key={key}><input type="radio" name={title} value={key} checked={value===key} onChange={()=>onChange(key)}/><span>{label}</span></label>)}</fieldset>}
