import React from 'react';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { Link, MemoryRouter, Route, Routes } from 'react-router-dom';
import { ProductShell } from '../../app/ProductShell';
import { PwaInstallCard } from './PwaInstallCard';
import { PwaInstallProvider } from './PwaInstallProvider';

type Choice = { outcome: 'accepted' | 'dismissed'; platform: string };
type PromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<Choice>; rejectChoice?: () => void };
type Mql = { matches: boolean; addEventListener: ReturnType<typeof vi.fn>; removeEventListener: ReturnType<typeof vi.fn>; emit: () => void };
const original = { hasMatchMedia: Object.prototype.hasOwnProperty.call(window, 'matchMedia'), matchMedia: window.matchMedia, ua: navigator.userAgent, platform: navigator.platform, maxTouchPoints: navigator.maxTouchPoints, hasStandalone: Object.prototype.hasOwnProperty.call(navigator, 'standalone'), standalone: (navigator as Navigator & { standalone?: boolean }).standalone, hasIndexedDB: Object.prototype.hasOwnProperty.call(window, 'indexedDB'), indexedDB: window.indexedDB };
let mobileMql: Mql; let standaloneMql: Mql;
function makeMql(matches: boolean): Mql { const listeners: Array<() => void> = []; return { matches, addEventListener: vi.fn((_event: string, cb: () => void) => listeners.push(cb)), removeEventListener: vi.fn(), emit: () => listeners.forEach((cb) => cb()) }; }
function setEnv({ mobile = true, standalone = false, ua = 'Mozilla/5.0 Android Chrome/120 Safari/537.36', platform = 'Linux armv8l', touch = 5, navStandalone }: { mobile?: boolean; standalone?: boolean; ua?: string; platform?: string; touch?: number; navStandalone?: boolean } = {}) {
  mobileMql = makeMql(mobile); standaloneMql = makeMql(standalone);
  Object.defineProperty(window, 'matchMedia', { configurable: true, value: vi.fn((query: string) => query.includes('standalone') ? standaloneMql : mobileMql) });
  Object.defineProperty(navigator, 'userAgent', { configurable: true, value: ua });
  Object.defineProperty(navigator, 'platform', { configurable: true, value: platform });
  Object.defineProperty(navigator, 'maxTouchPoints', { configurable: true, value: touch });
  Object.defineProperty(navigator, 'standalone', { configurable: true, value: navStandalone });
}
function renderWithProvider(ui: React.ReactElement, route = '/pulse') { return render(<MemoryRouter initialEntries={[route]}><PwaInstallProvider>{ui}</PwaInstallProvider></MemoryRouter>); }
function renderApp(route = '/pulse') { return render(<MemoryRouter initialEntries={[route]}><PwaInstallProvider><ProductShell><Routes><Route path="/pulse" element={<><PwaInstallCard/><div>pulse</div></>} /><Route path="/map" element={<div>map</div>} /><Route path="/contribute" element={<div className="mobile-delta-create-page">form</div>} /></Routes></ProductShell></PwaInstallProvider></MemoryRouter>); }
function emitPrompt({ outcome = 'accepted', promptReject = false, choiceReject = false }: { outcome?: 'accepted' | 'dismissed'; promptReject?: boolean; choiceReject?: boolean } = {}) {
  const event = new Event('beforeinstallprompt') as PromptEvent;
  event.preventDefault = vi.fn();
  event.prompt = vi.fn(() => promptReject ? Promise.reject(new Error('prompt')) : Promise.resolve());
  event.userChoice = choiceReject ? new Promise<Choice>((_resolve, reject) => { event.rejectChoice = () => reject(new Error('choice')); }) : Promise.resolve({ outcome, platform: 'web' });
  fireEvent(window, event);
  return event;
}
beforeEach(() => { localStorage.setItem('delta-draft', 'keep'); setEnv(); });
afterEach(() => { cleanup(); localStorage.removeItem('delta-draft'); if (original.hasMatchMedia) Object.defineProperty(window, 'matchMedia', { configurable: true, value: original.matchMedia }); else delete (window as unknown as { matchMedia?: unknown }).matchMedia; Object.defineProperty(navigator, 'userAgent', { configurable: true, value: original.ua }); Object.defineProperty(navigator, 'platform', { configurable: true, value: original.platform }); Object.defineProperty(navigator, 'maxTouchPoints', { configurable: true, value: original.maxTouchPoints }); if (original.hasStandalone) Object.defineProperty(navigator, 'standalone', { configurable: true, value: original.standalone }); else delete (navigator as Navigator & { standalone?: unknown }).standalone; if (original.hasIndexedDB) Object.defineProperty(window, 'indexedDB', { configurable: true, value: original.indexedDB }); else delete (window as unknown as { indexedDB?: unknown }).indexedDB; vi.clearAllMocks(); });

describe('PwaInstallCard', () => {
  it('captures Chromium event and prompts only after a direct click', async () => { renderWithProvider(<PwaInstallCard />); const event = emitPrompt(); expect(event.preventDefault).toHaveBeenCalled(); expect(await screen.findByRole('button', { name: 'Установить' })).toBeInTheDocument(); expect(event.prompt).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Установить' })); await waitFor(() => expect(event.prompt).toHaveBeenCalledOnce()); });
  it('keeps an accepted choice pending until appinstalled confirms installation', async () => { renderWithProvider(<PwaInstallCard />); emitPrompt({ outcome: 'accepted' }); fireEvent.click(await screen.findByRole('button', { name: 'Установить' })); expect(await screen.findByText(/Браузер готовит установку/)).toBeInTheDocument(); expect(screen.queryByText(/Откройте меню браузера/)).not.toBeInTheDocument(); fireEvent(window, new Event('appinstalled')); await waitFor(() => expect(screen.queryByText('Установить УЗОР')).not.toBeInTheDocument()); });
  it('suppresses the card for this session after dismissed userChoice', async () => { renderWithProvider(<PwaInstallCard />); emitPrompt({ outcome: 'dismissed' }); fireEvent.click(await screen.findByRole('button', { name: 'Установить' })); await waitFor(() => expect(screen.getByRole('heading', { name: 'Установить УЗОР' })).toBeInTheDocument()); });
  it('handles rejected prompt and rejected userChoice without clearing drafts', async () => { renderWithProvider(<PwaInstallCard />); emitPrompt({ promptReject: true }); fireEvent.click(await screen.findByRole('button', { name: 'Установить' })); expect(await screen.findByText(/Не удалось открыть установку/)).toBeInTheDocument(); cleanup(); renderWithProvider(<PwaInstallCard />); const rejectedChoice = emitPrompt({ choiceReject: true }); fireEvent.click(await screen.findByRole('button', { name: 'Установить' })); rejectedChoice.rejectChoice?.(); expect(await screen.findByText(/Не удалось открыть установку/)).toBeInTheDocument(); expect(localStorage.getItem('delta-draft')).toBe('keep'); });
  it('hides for initial standalone, media-query standalone changes, and navigator.standalone', async () => { setEnv({ standalone: true }); renderWithProvider(<PwaInstallCard />); expect(screen.queryByText('Установить УЗОР')).not.toBeInTheDocument(); cleanup(); setEnv({ navStandalone: true }); renderWithProvider(<PwaInstallCard />); expect(screen.queryByText('Установить УЗОР')).not.toBeInTheDocument(); cleanup(); setEnv(); renderWithProvider(<PwaInstallCard />); expect(screen.getByText('Установить УЗОР')).toBeInTheDocument(); act(() => { standaloneMql.matches = true; standaloneMql.emit(); }); await waitFor(() => expect(screen.queryByText('Установить УЗОР')).not.toBeInTheDocument()); });
  it.each([
    ['iPhone Safari', 'Mozilla/5.0 (iPhone) Version/17.0 Mobile/15E148 Safari/604.1', 'iPhone', 1],
    ['classic iPad Safari', 'Mozilla/5.0 (iPad) Version/17.0 Mobile/15E148 Safari/604.1', 'iPad', 5],
    ['modern iPadOS Safari', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) Version/17.0 Safari/605.1.15', 'MacIntel', 5],
  ])('shows manual instructions for %s', (_label, ua, platform, touch) => { setEnv({ ua, platform, touch }); renderWithProvider(<PwaInstallCard />); expect(screen.getByText('Нажмите «Поделиться».')).toBeInTheDocument(); expect(screen.queryByText(/Откройте меню браузера/)).not.toBeInTheDocument(); });
  it('keeps unsupported mobile fallback collapsed until Как установить', () => { renderWithProvider(<PwaInstallCard />); expect(screen.getByText('Установить УЗОР')).toBeInTheDocument(); expect(screen.queryByText(/Откройте меню браузера/)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Как установить' })); expect(screen.getByText(/Откройте меню браузера/)).toBeInTheDocument(); });
  it('does not show generic fallback on desktop without a prompt but shows a genuine prompt', async () => { setEnv({ mobile: false }); renderWithProvider(<PwaInstallCard />); expect(screen.queryByText('Установить УЗОР')).not.toBeInTheDocument(); const event = emitPrompt(); expect(await screen.findByRole('button', { name: 'Установить' })).toBeInTheDocument(); expect(event.preventDefault).toHaveBeenCalled(); });

  it.each(['/map', '/contribute'])('captures beforeinstallprompt on direct %s entry', async (route) => { renderApp(route); const event = emitPrompt(); expect(event.preventDefault).toHaveBeenCalled(); expect(await screen.findByRole('button', { name: 'Установить УЗОР' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Установить УЗОР' })); await waitFor(() => expect(event.prompt).toHaveBeenCalledOnce()); });
  it('preserves the deferred prompt while navigating between map and pulse', async () => { render(<MemoryRouter initialEntries={['/map']}><PwaInstallProvider><ProductShell><Routes><Route path="/map" element={<Link to="/pulse">go pulse</Link>} /><Route path="/pulse" element={<PwaInstallCard />} /></Routes></ProductShell></PwaInstallProvider></MemoryRouter>); const event = emitPrompt(); fireEvent.click(screen.getByText('go pulse')); expect(await screen.findByRole('button', { name: 'Установить' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Установить' })); await waitFor(() => expect(event.prompt).toHaveBeenCalledOnce()); });
  it('registers exactly one beforeinstallprompt listener per provider mount', () => { const add = vi.spyOn(window, 'addEventListener'); const remove = vi.spyOn(window, 'removeEventListener'); const { unmount } = renderWithProvider(<PwaInstallCard />); expect(add.mock.calls.filter(([name]) => name === 'beforeinstallprompt')).toHaveLength(1); unmount(); expect(remove.mock.calls.filter(([name]) => name === 'beforeinstallprompt')).toHaveLength(1); });
  it('opens global manual instructions when no Chromium event exists', () => { renderApp('/map'); fireEvent.click(screen.getByRole('button', { name: 'Установить УЗОР' })); expect(screen.getByText(/Откройте меню браузера/)).toBeInTheDocument(); });
  it('uses promotion dismissal without clearing localStorage or IndexedDB', async () => { const db = { marker: 'keep' } as unknown as IDBFactory; Object.defineProperty(window, 'indexedDB', { configurable: true, value: db }); renderApp('/pulse'); fireEvent.click(screen.getByRole('button', { name: 'Не сейчас' })); await waitFor(() => expect(screen.queryByRole('heading', { name: 'Установить УЗОР' })).not.toBeInTheDocument()); expect(screen.getByRole('button', { name: 'Установить УЗОР' })).toBeInTheDocument(); expect(localStorage.getItem('delta-draft')).toBe('keep'); expect(window.indexedDB).toBe(db); });
});
