import { getSupabaseClient } from '../../lib/supabase/client';
import type { CreateDeltaInput, DeltaApiErrorCode, DeltaCard, DeltaCategory, DeltaCity, DeltaMapItem, DeltaReaction, DeltaViewportInput, FindSimilarDeltaInput, ReactToDeltaResult, DeltaEffect } from './deltaTypes';

export class DeltaApiError extends Error { constructor(public code: DeltaApiErrorCode, message = code) { super(message); } }

function mapDeltaError(error: unknown): DeltaApiError {
  const message = error && typeof error === 'object' && 'message' in error ? String((error as { message?: unknown }).message) : '';
  const codes: DeltaApiErrorCode[] = ['not_authenticated', 'not_circle_member', 'city_not_found', 'category_not_found', 'invalid_coordinates', 'invalid_delta_payload', 'delta_not_found', 'author_reaction_locked'];
  return new DeltaApiError(codes.find((code) => message.includes(code)) ?? 'unknown');
}
async function rpc<T>(name: string, args?: Record<string, unknown>): Promise<T> { const { data, error } = await getSupabaseClient().rpc(name, args); if (error) throw mapDeltaError(error); return data as T; }

export function createDelta(input: CreateDeltaInput) { return rpc<{ delta: DeltaCard; effect: DeltaEffect }>('create_delta', { input_circle_id: input.circleId, input_city_slug: input.citySlug, input_category_slug: input.categorySlug, input_direction: input.direction, input_subject: input.subject, input_change_type: input.changeType, input_statement: input.statement, input_details: input.details ?? null, input_observed_window: input.observedWindow, input_impact_level: input.impactLevel, input_lat: input.lat, input_lng: input.lng, input_location_label: input.locationLabel, input_location_precision: input.locationPrecision ?? 'point' }); }
export function reactToDelta(deltaId: string, reaction: DeltaReaction) { return rpc<ReactToDeltaResult>('react_to_delta', { input_delta_id: deltaId, input_reaction: reaction }); }
export function getDeltaCard(deltaId: string) { return rpc<DeltaCard>('get_delta_card', { input_delta_id: deltaId }); }
export function findSimilarDeltas(input: FindSimilarDeltaInput) { return rpc<Array<Pick<DeltaCard, 'id' | 'statement' | 'status' | 'confirmCount' | 'disconfirmCount' | 'createdAt'> & { distanceMeters: number; locationLabel: string }>>('find_similar_deltas', { input_circle_id: input.circleId, input_city_slug: input.citySlug, input_category_slug: input.categorySlug, input_direction: input.direction, input_change_type: input.changeType, input_lat: input.lat, input_lng: input.lng, input_radius_m: input.radiusM ?? 1000, input_days: input.days ?? 14 }); }
export function listDeltasInView(input: DeltaViewportInput) { return rpc<DeltaMapItem[]>('list_deltas_in_view', { input_circle_id: input.circleId, input_city_slug: input.citySlug, min_lat: input.minLat, min_lng: input.minLng, max_lat: input.maxLat, max_lng: input.maxLng, input_direction: input.direction ?? null, input_category_slug: input.categorySlug ?? null, input_status: input.status ?? null }); }
export async function loadDeltaCategories() { const { data, error } = await getSupabaseClient().from('delta_categories').select('id,slug,title,description,icon_key,sensitivity_weight,sort_order').eq('is_active', true).order('sort_order'); if (error) throw mapDeltaError(error); return (data ?? []).map((row) => ({ id: row.id, slug: row.slug, title: row.title, description: row.description, iconKey: row.icon_key, sensitivityWeight: row.sensitivity_weight, sortOrder: row.sort_order })) as DeltaCategory[]; }
export async function loadDeltaCities() { const { data, error } = await getSupabaseClient().from('delta_cities').select('id,slug,name,center_lat,center_lng,default_zoom,outskirts_distance_m').eq('is_active', true).order('name'); if (error) throw mapDeltaError(error); return (data ?? []).map((row) => ({ id: row.id, slug: row.slug, name: row.name, centerLat: row.center_lat, centerLng: row.center_lng, defaultZoom: row.default_zoom, outskirtsDistanceM: row.outskirts_distance_m })) as DeltaCity[]; }
