import type { ForecastEvent, ForecastOutcome, ForecastScore, UserForecast } from '../types';
import { formatResolutionSource, formatRussianUtcDateTime } from './forecastUiLogic';

const safeUrl=(value:string)=>{try{const url=new URL(value);return url.protocol==='http:'||url.protocol==='https:'?url.href:null;}catch{return null;}};
const decimal=(value:number,digits:number)=>value.toLocaleString('ru-RU',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const preciseDecimal=(value:number,minimumFractionDigits=2)=>value.toLocaleString('ru-RU',{minimumFractionDigits,maximumFractionDigits:12});
const percentage=(value:number)=>`${(value*100).toLocaleString('ru-RU',{maximumFractionDigits:10})}%`;
export function ForecastOutcomeView({event,outcome,forecast,score}:{event:ForecastEvent;outcome:ForecastOutcome;forecast:UserForecast|null;score?:ForecastScore|null}){
 const resolved=event.options.find(option=>option.id===outcome.resolvedOptionId)?.label;
 const selected=forecast&&event.options.find(option=>option.id===forecast.selectedOptionId)?.label;
 const url=safeUrl(outcome.sourceReference);
 return <section className="forecast-outcome" aria-labelledby="verified-outcome-title"><h2 id="verified-outcome-title">Исход проверен</h2><dl><div><dt>Проверенный исход</dt><dd>{resolved}</dd></div><div><dt>Время фиксации</dt><dd>{formatRussianUtcDateTime(outcome.resolvedAt)}</dd></div><div><dt>Тип источника</dt><dd>{formatResolutionSource(outcome.sourceType)}</dd></div><div><dt>Источник</dt><dd>{url?<a href={url} target="_blank" rel="noopener noreferrer">{outcome.sourceReference}</a>:outcome.sourceReference}</dd></div><div><dt>Примечание о проверке</dt><dd>{outcome.resolutionNote}</dd></div>{forecast&&<><div><dt>Ваш выбранный вариант</dt><dd>{selected}</dd></div><div><dt>Ваша вероятность</dt><dd>{percentage(forecast.probability)}</dd></div></>}</dl>{!forecast?<p>Вы не зафиксировали прогноз до дедлайна, поэтому персональная математическая оценка отсутствует.</p>:!score?<p>Математическая оценка пока недоступна.</p>:<section className="forecast-score" aria-labelledby="forecast-score-title"><p className="forecast-kicker">ЛИЧНЫЙ РЕЗУЛЬТАТ</p><h3 id="forecast-score-title">Математическая оценка прогноза</h3><p className="forecast-score__label">Оценка Брайера</p><strong className="forecast-score__value">{decimal(score.brierScore,4)}</strong><div className="forecast-score__scale" role="img" aria-label={`Шкала оценки Брайера от 0 до 1, значение ${decimal(score.brierScore,4)}`}><span className="forecast-score__marker" style={{left:`${score.brierScore*100}%`}} /></div><div className="forecast-score__ends"><span>0 — точнее</span><span>1 — максимальная ошибка</span></div><dl><div><dt>Указанная вероятность</dt><dd>{percentage(score.forecastProbability)}</dd></div><div><dt>Наблюдаемое значение</dt><dd>{score.observedBinaryOutcome} — выбранный вариант {score.observedBinaryOutcome===1?'произошёл':'не произошёл'}</dd></div><div><dt>Подстановка</dt><dd>({preciseDecimal(score.forecastProbability)} − {score.observedBinaryOutcome})² = {preciseDecimal(score.brierScore,4)}</dd></div><div><dt>Дата оценки</dt><dd>{formatRussianUtcDateTime(score.scoredAt)}</dd></div></dl><details><summary>Технические сведения</summary><p>Версия расчёта: {score.scoringVersion}</p></details><p>Чем ближе оценка к 0, тем точнее была указанная вероятность. 1 — максимальная возможная ошибка.</p></section>}</section>;
}
