import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { ForecastResolutionBlockReason, ForecastResolutionWorkspace } from '../api/forecastApiTypes';
import { ForecastApiError } from '../api/forecastApi';
import { createInteractiveDemoEvent } from './forecastUiLogic';

const state=vi.hoisted(()=>({configured:true}));
const api=vi.hoisted(()=>({get:vi.fn(),resolve:vi.fn()}));
vi.mock('../../../app/appMode',()=>({get isProductionConfigured(){return state.configured;}}));
vi.mock('../api/forecastApi',async original=>({...await original<typeof import('../api/forecastApi')>(),getForecastResolutionWorkspace:api.get,resolveForecastEvent:api.resolve}));
import { ForecastResolverPage } from './ForecastResolverPage';

const event={...createInteractiveDemoEvent(),id:'sandbox-demo-milk-price-2026-12-15',status:'awaiting-outcome' as const};
const ready:ForecastResolutionWorkspace={event,outcome:null,serverTimestamp:'2026-12-15T12:00:00Z',authorized:true,canResolve:true,blockReason:null};
const blocked=(reason:Exclude<ForecastResolutionBlockReason,null>):ForecastResolutionWorkspace=>({event,outcome:null,serverTimestamp:'2026-12-15T12:00:00Z',authorized:reason!=='not_authenticated'&&reason!=='resolver_not_authorized',canResolve:false,blockReason:reason});
const renderPage=()=>render(<MemoryRouter><ForecastResolverPage/></MemoryRouter>);
const fill=async()=>{await userEvent.click(await screen.findByRole('radio',{name:event.options[0].label}));await userEvent.type(screen.getByRole('textbox',{name:/Источник/}),' https://example.test/result ');await userEvent.type(screen.getByRole('textbox',{name:/Примечание/}),' проверено человеком ');};
afterEach(()=>{cleanup();state.configured=true;api.get.mockReset();api.resolve.mockReset();});

describe('ForecastResolverPage',()=>{
 it('does not call the API in demo mode',()=>{state.configured=false;renderPage();expect(screen.getByText('Фиксация проверенного исхода доступна только в рабочем контуре.')).toBeInTheDocument();expect(api.get).not.toHaveBeenCalled();});
 it('shows the production loading state',()=>{api.get.mockReturnValue(new Promise(()=>{}));renderPage();expect(screen.getByText('Проверяем полномочия и состояние события…')).toBeInTheDocument();});
 it.each([
  ['not_authenticated','Необходимо войти в аккаунт.'],['resolver_not_authorized','Доступ к фиксации исходов не предоставлен.'],['forecast_still_open','Приём прогнозов ещё открыт.'],['resolution_time_not_reached','Время проверки ещё не наступило.'],['event_cancelled','Событие отменено.'],['outcome_already_resolved','Исход уже зафиксирован.'],
 ] as const)('shows distinct blocked state %s without a form',async(reason,message)=>{api.get.mockResolvedValue(blocked(reason));renderPage();expect(await screen.findByText(message)).toBeInTheDocument();expect(screen.queryByRole('form')).not.toBeInTheDocument();expect(screen.queryByRole('radio')).not.toBeInTheDocument();});
 it('starts with no option and rejects trimmed empty fields',async()=>{api.get.mockResolvedValue(ready);renderPage();const radios=await screen.findAllByRole('radio');expect(radios.every(x=>!(x as HTMLInputElement).checked)).toBe(true);const review=screen.getByRole('button',{name:'Перейти к проверке'});expect(review).toBeDisabled();fireEvent.change(screen.getByRole('textbox',{name:/Источник/}),{target:{value:'   '}});fireEvent.change(screen.getByRole('textbox',{name:/Примечание/}),{target:{value:'   '}});expect(review).toBeDisabled();expect(screen.getByRole('textbox',{name:/Источник/})).toHaveAttribute('maxlength','2000');expect(screen.getByRole('textbox',{name:/Примечание/})).toHaveAttribute('maxlength','2000');});
 it('reviews trimmed values and returns to edit',async()=>{api.get.mockResolvedValue(ready);renderPage();await fill();await userEvent.click(screen.getByRole('button',{name:'Перейти к проверке'}));expect(screen.getByRole('heading',{name:'Проверьте исход'})).toBeInTheDocument();expect(screen.getByText(event.options[0].label)).toBeInTheDocument();expect(screen.getByText('https://example.test/result')).toBeInTheDocument();expect(screen.getByText('проверено человеком')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Изменить'}));expect(screen.getByRole('textbox',{name:/Источник/})).toBeInTheDocument();});
 it('protects duplicate confirmation, disables actions, and sends no identity or time',async()=>{api.get.mockResolvedValue(ready);let finish!:(value:unknown)=>void;api.resolve.mockReturnValue(new Promise(resolve=>{finish=resolve;}));renderPage();await fill();await userEvent.click(screen.getByRole('button',{name:'Перейти к проверке'}));const confirm=screen.getByRole('button',{name:'Зафиксировать проверенный исход'}),edit=screen.getByRole('button',{name:'Изменить'});fireEvent.click(confirm);fireEvent.click(confirm);expect(api.resolve).toHaveBeenCalledTimes(1);expect(confirm).toBeDisabled();expect(edit).toBeDisabled();expect(JSON.stringify(api.resolve.mock.calls)).not.toMatch(/userId|resolvedAt|timestamp/i);finish({});});
 it('maps backend errors without exposing raw text',async()=>{api.get.mockResolvedValue(ready);api.resolve.mockRejectedValue(new ForecastApiError('forecast_outcome_write_failed'));renderPage();await fill();await userEvent.click(screen.getByRole('button',{name:'Перейти к проверке'}));await userEvent.click(screen.getByRole('button',{name:'Зафиксировать проверенный исход'}));expect(await screen.findByRole('alert')).toHaveTextContent('Не удалось зафиксировать исход. Попробуйте ещё раз.');expect(document.body).not.toHaveTextContent('forecast_outcome_write_failed');});
 it('uses authoritative success data and a Russian status',async()=>{api.get.mockResolvedValue(ready);const authoritative={...event,title:'Серверное событие',status:'resolved' as const};api.resolve.mockResolvedValue({event:authoritative,eventUpdatedAt:'2026-12-15T12:01:00Z',serverTimestamp:'2026-12-15T12:01:00Z',outcome:{id:'o',eventId:event.id,resolvedOptionId:event.options[1].id,resolvedAt:'2026-12-15T12:01:00Z',sourceReference:'Серверный источник',sourceType:event.resolutionSource,resolutionNote:'Серверное примечание',resolverStatus:'verified',version:'forecast-domain-v1'}});renderPage();await fill();await userEvent.click(screen.getByRole('button',{name:'Перейти к проверке'}));await userEvent.click(screen.getByRole('button',{name:'Зафиксировать проверенный исход'}));expect(await screen.findByRole('heading',{name:'Проверенный исход зафиксирован'})).toBeInTheDocument();expect(screen.getByText(event.options[1].label)).toBeInTheDocument();expect(screen.getByText('Серверный источник')).toBeInTheDocument();expect(screen.getByText('Исход проверен')).toBeInTheDocument();expect(screen.queryByText('resolved')).not.toBeInTheDocument();await waitFor(()=>expect(api.resolve).toHaveBeenCalledTimes(1));});
});
