import { useEffect, useRef, useState } from 'react';
import { ProductShell } from '../../../app/ProductShell';
import { isProductionConfigured } from '../../../app/appMode';
import { getForecastResolutionWorkspace, resolutionErrorMessage, resolveForecastEvent } from '../api/forecastApi';
import type { ForecastResolutionWorkspace, ResolveForecastResult } from '../api/forecastApiTypes';
import { FORECAST_DOMAIN_VERSION } from '../types';
import { formatResolution, formatResolutionSource, formatRussianUtcDateTime } from './forecastUiLogic';

const EVENT_ID='sandbox-demo-milk-price-2026-12-15';
const reasons={forecast_still_open:'Приём прогнозов ещё открыт.',resolution_time_not_reached:'Время проверки ещё не наступило.',event_cancelled:'Событие отменено.',outcome_already_resolved:'Исход уже зафиксирован.',event_not_found:'Событие не найдено.',not_authenticated:'Необходимо войти в аккаунт.',resolver_not_authorized:'Доступ к фиксации исходов не предоставлен.'} as const;
export function ForecastResolverPage(){
 const [workspace,setWorkspace]=useState<ForecastResolutionWorkspace|null>(null),[error,setError]=useState(''),[option,setOption]=useState(''),[source,setSource]=useState(''),[note,setNote]=useState(''),[review,setReview]=useState(false),[saving,setSaving]=useState(false),[result,setResult]=useState<ResolveForecastResult|null>(null);const submitting=useRef(false);
 useEffect(()=>{if(!isProductionConfigured)return;getForecastResolutionWorkspace(EVENT_ID).then(setWorkspace).catch(e=>setError(resolutionErrorMessage(e)));},[]);
 if(!isProductionConfigured)return <ProductShell className="forecast-shell"><main className="forecast-page"><p>Фиксация проверенного исхода доступна только в рабочем контуре.</p></main></ProductShell>;
 if(result){const label=workspace?.event?.options.find(x=>x.id===result.outcome.resolvedOptionId)?.label;return <ProductShell className="forecast-shell"><main className="forecast-page"><h1>Проверенный исход зафиксирован</h1><dl><div><dt>Проверенный исход</dt><dd>{label}</dd></div><div><dt>Время</dt><dd>{formatRussianUtcDateTime(result.outcome.resolvedAt)}</dd></div><div><dt>Источник</dt><dd>{result.outcome.sourceReference}</dd></div><div><dt>Примечание</dt><dd>{result.outcome.resolutionNote}</dd></div><div><dt>Статус события</dt><dd>{result.event.status}</dd></div></dl></main></ProductShell>}
 if(error&&!workspace)return <ProductShell className="forecast-shell"><main className="forecast-page"><p role="alert">{error}</p></main></ProductShell>;
 if(!workspace)return <ProductShell className="forecast-shell"><main className="forecast-page"><p>Проверяем полномочия и состояние события…</p></main></ProductShell>;
 if(!workspace.authorized)return <ProductShell className="forecast-shell"><main className="forecast-page"><p>Доступ к фиксации исходов не предоставлен.</p></main></ProductShell>;
 if(!workspace.canResolve||!workspace.event)return <ProductShell className="forecast-shell"><main className="forecast-page"><p>{workspace.blockReason?reasons[workspace.blockReason]:'Фиксация сейчас недоступна.'}</p></main></ProductShell>;
 const event=workspace.event,valid=Boolean(option&&source.trim()&&note.trim());
 const submit=async()=>{if(submitting.current)return;submitting.current=true;setSaving(true);setError('');try{setResult(await resolveForecastEvent({eventId:event.id,resolvedOptionId:option,sourceReference:source.trim(),resolutionNote:note.trim(),version:FORECAST_DOMAIN_VERSION}));}catch(e){setError(resolutionErrorMessage(e));}finally{submitting.current=false;setSaving(false);}};
 return <ProductShell className="forecast-shell"><main className="forecast-page"><p className="forecast-kicker">РАБОЧЕЕ МЕСТО РЕЗОЛВЕРА</p><h1>{event.title}</h1><dl><div><dt>Точное условие разрешения</dt><dd>{event.shortDescription}</dd></div><div><dt>Приём прогнозов до</dt><dd>{formatRussianUtcDateTime(event.closesAt)}</dd></div><div><dt>Ожидаемое время проверки</dt><dd>{formatResolution(event)}</dd></div><div><dt>Тип источника</dt><dd>{formatResolutionSource(event.resolutionSource)}</dd></div></dl>{error&&<p role="alert">{error}</p>}{review?<section><h2>Проверьте исход</h2><dl><div><dt>Проверенный исход</dt><dd>{event.options.find(x=>x.id===option)?.label}</dd></div><div><dt>Источник</dt><dd>{source.trim()}</dd></div><div><dt>Примечание</dt><dd>{note.trim()}</dd></div></dl><button type="button" onClick={()=>setReview(false)}>Изменить</button><button type="button" disabled={saving} onClick={()=>void submit()}>{saving?'Фиксируем исход…':'Зафиксировать проверенный исход'}</button></section>:<form onSubmit={e=>{e.preventDefault();if(valid)setReview(true);}}><fieldset><legend>Вариант исхода</legend>{event.options.map(item=><label key={item.id}><input type="radio" name="outcome" value={item.id} checked={option===item.id} onChange={()=>setOption(item.id)}/>{item.label}</label>)}</fieldset><label>Источник<input value={source} maxLength={2000} onChange={e=>setSource(e.target.value)}/><span>{source.length}/2000</span></label><label>Примечание о проверке<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/><span>{note.length}/2000</span></label><p>После подтверждения исход будет зафиксирован как проверенный. В версии v1 его нельзя изменить через приложение.</p><button type="submit" disabled={!valid}>Перейти к проверке</button></form>}</main></ProductShell>;
}
