import { cleanup, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import { createInteractiveDemoEvent } from './forecastUiLogic';
import { ForecastOutcomeView } from './ForecastOutcomeView';
const event={...createInteractiveDemoEvent(),status:'resolved' as const};
const outcome={id:'o',eventId:event.id,resolvedOptionId:event.options[0].id,resolvedAt:'2026-12-15T12:00:00Z',sourceReference:'https://example.test/result',sourceType:event.resolutionSource,resolutionNote:'Проверено человеком',resolverStatus:'verified' as const,version:'forecast-domain-v1' as const};
const forecast={id:'f',eventId:event.id,selectedOptionId:event.options[0].id,probability:.7,createdAt:'2026-12-01T00:00:00Z',updatedAt:'2026-12-01T00:00:00Z',version:'forecast-domain-v1' as const};
const score={id:'f:o:brier-binary-v1',eventId:event.id,forecastId:'f',outcomeId:'o',forecastProbability:.7,observedBinaryOutcome:1 as const,brierScore:.09,scoredAt:'2026-12-15T12:00:00Z',scoringVersion:'brier-binary-v1' as const,version:'forecast-domain-v1' as const};
afterEach(cleanup);
describe('ForecastOutcomeView',()=>{
 it('renders the authoritative personal Brier result and neutral scale',()=>{render(<ForecastOutcomeView event={event} outcome={outcome} forecast={forecast} score={score}/>);expect(screen.getByRole('heading',{name:'Математическая оценка прогноза'})).toBeInTheDocument();expect(screen.getByText('0,0900')).toBeInTheDocument();expect(screen.getByText('(0,70 − 1)² = 0,0900')).toBeInTheDocument();expect(screen.getByText('1 — выбранный вариант произошёл')).toBeInTheDocument();expect(screen.getByText('0 — точнее')).toBeInTheDocument();expect(screen.getByText('1 — максимальная ошибка')).toBeInTheDocument();expect(screen.getByRole('img')).toHaveAttribute('aria-label',expect.stringContaining('0,0900'));expect(screen.getByRole('link',{name:outcome.sourceReference})).toHaveAttribute('rel','noopener noreferrer');expect(document.body.textContent).not.toMatch(/репутац|\bXP\b|рейтинг|выиграл|проиграл|точность 91%/i);});
 it('shows observation zero using the server value',()=>{render(<ForecastOutcomeView event={event} outcome={outcome} forecast={{...forecast,selectedOptionId:event.options[1].id}} score={{...score,observedBinaryOutcome:0,brierScore:.49}}/>);expect(screen.getByText('0 — выбранный вариант не произошёл')).toBeInTheDocument();expect(screen.getByText('(0,70 − 0)² = 0,4900')).toBeInTheDocument();});
 it('does not calculate a missing score',()=>{render(<ForecastOutcomeView event={event} outcome={outcome} forecast={forecast} score={null}/>);expect(screen.getByText('Математическая оценка пока недоступна.')).toBeInTheDocument();expect(screen.queryByText('0,0900')).not.toBeInTheDocument();});
 it('explains when there was no personal forecast',()=>{render(<ForecastOutcomeView event={event} outcome={outcome} forecast={null} score={null}/>);expect(screen.getByText('Вы не зафиксировали прогноз до дедлайна, поэтому персональная математическая оценка отсутствует.')).toBeInTheDocument();});
 it('renders a non-URL reference as text',()=>{render(<ForecastOutcomeView event={event} outcome={{...outcome,sourceReference:'Бюллетень № 17'}} forecast={null}/>);expect(screen.getByText('Бюллетень № 17').tagName).not.toBe('A');});
});
