import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it } from 'vitest';
import type { ForecastEventStatus } from '..';
import { ForecastCard } from './ForecastCard';
import { createInteractiveDemoEvent } from './forecastUiLogic';

afterEach(cleanup);
const renderCard = (status: ForecastEventStatus = 'open') => render(<ForecastCard event={{ ...createInteractiveDemoEvent(), status }} />);

describe('ForecastCard', () => {
  it('shows the fixed demo warning with no preselected option', () => { renderCard(); expect(screen.getByText('Интерактивное демо · время сценария зафиксировано')).toBeInTheDocument(); expect(screen.getAllByRole('radio')).toHaveLength(2); expect(screen.getAllByRole('radio').every((radio) => !(radio as HTMLInputElement).checked)).toBe(true); });
  it('selects exactly one outcome and reveals probability controls', async () => { const user=userEvent.setup();renderCard();await user.click(screen.getByRole('radio',{name:'Строго выше 120,00 ₽'}));expect(screen.getByRole('radio',{name:'Строго выше 120,00 ₽'})).toBeChecked();expect(screen.getByRole('slider')).toBeInTheDocument(); });
  it('keeps range and numeric controls synchronized', async () => { const user=userEvent.setup();renderCard();await user.click(screen.getAllByRole('radio')[0]);fireEvent.change(screen.getByRole('slider'),{target:{value:'70'}});expect(screen.getByRole('spinbutton')).toHaveValue(70);await user.clear(screen.getByRole('spinbutton'));await user.type(screen.getByRole('spinbutton'),'83');expect(screen.getByRole('slider')).toHaveValue('83');expect(screen.getByText('83%')).toBeInTheDocument(); });
  it('blocks invalid manual percentages with Russian feedback', async () => { const user=userEvent.setup();renderCard();await user.click(screen.getAllByRole('radio')[0]);await user.clear(screen.getByRole('spinbutton'));await user.type(screen.getByRole('spinbutton'),'101');expect(screen.getByRole('alert')).toHaveTextContent('от 0% до 100%');expect(screen.getByRole('button',{name:'Проверить прогноз'})).toBeDisabled(); });
  it('reviews the selected outcome, probability and normalized optional text', async () => { const user=userEvent.setup();renderCard();await user.click(screen.getAllByRole('radio')[0]);await user.clear(screen.getByRole('spinbutton'));await user.type(screen.getByRole('spinbutton'),'70');await user.type(screen.getByLabelText(/Почему вы так думаете/),'   ');await user.click(screen.getByRole('button',{name:'Проверить прогноз'}));expect(screen.getByRole('heading',{name:'Проверьте прогноз'})).toHaveFocus();expect(screen.getByText('Строго выше 120,00 ₽')).toBeInTheDocument();expect(screen.getByText('70%')).toBeInTheDocument();expect(screen.getByText('Не добавлено')).toBeInTheDocument(); });
  it('returns from review to editing', async () => { const user=userEvent.setup();renderCard();await user.click(screen.getAllByRole('radio')[0]);fireEvent.change(screen.getByRole('slider'),{target:{value:'70'}});await user.click(screen.getByRole('button',{name:'Проверить прогноз'}));await user.click(screen.getByRole('button',{name:'Изменить'}));expect(screen.getByRole('button',{name:'Проверить прогноз'})).toBeEnabled(); });
  it('confirms only an honest non-persistent demo result', async () => { const user=userEvent.setup();renderCard();await user.click(screen.getAllByRole('radio')[0]);fireEvent.change(screen.getByRole('slider'),{target:{value:'70'}});await user.click(screen.getByRole('button',{name:'Проверить прогноз'}));await user.click(screen.getByRole('button',{name:'Собрать демо-прогноз'}));expect(screen.getByRole('heading',{name:'Демо-прогноз собран'})).toHaveFocus();expect(screen.getByText(/не отправлен на сервер/)).toBeInTheDocument();expect(screen.getByText(/не сохранён после перезагрузки/)).toBeInTheDocument();expect(screen.getByText(/не влияет на репутацию/)).toBeInTheDocument(); });
  it.each<ForecastEventStatus>(['draft','closed','awaiting-outcome','resolved','cancelled'])('disables controls for %s events', (status) => { renderCard(status);expect(screen.getByRole('group',{name:'Какой исход вы выбираете?'})).toBeDisabled();expect(screen.getByRole('button',{name:'Проверить прогноз'})).toBeDisabled();expect(screen.getByText('Собрать прогноз для события в этом состоянии нельзя.')).toBeInTheDocument(); });
});
