import type { WrappedActivityPoint } from '../wrappedTypes';
const dayX = (i: number, total: number) => 32 + (i * 456) / Math.max(total - 1, 1);
const pointY = (value: number, max: number) => 150 - (value / Math.max(max, 1)) * 108;
export function WrappedActivityChart({ points }: { points: WrappedActivityPoint[] }) {
  const safe = points.length ? points : ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((day) => ({ day, signals: 0, confirmed: 0, unconfirmed: 0 }));
  const max = Math.max(...safe.map((p) => p.signals), 1);
  const line = safe.map((p, i) => `${dayX(i, safe.length)},${pointY(p.signals, max)}`).join(' ');
  return <><div className="wrapped-legend"><span>Ваши сигналы</span><span>Подтверждено</span><span>Не подтвердилось</span></div><svg className="wrapped-chart" viewBox="0 0 520 190" role="img" aria-label="Активность сигналов по дням"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#18e7ff" stopOpacity=".24"/><stop offset="1" stopColor="#18e7ff" stopOpacity="0"/></linearGradient><filter id="chartGlow"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d={`M32,164 L${line} L488,164 Z`} fill="url(#chartFill)"/><polyline points={line} className="chart-line" fill="none" filter="url(#chartGlow)"/>{safe.map((p, i) => { const x = dayX(i, safe.length); return <g key={p.day}><line x1={x} x2={x} y1="38" y2="164" className="chart-grid"/><circle cx={x} cy={pointY(p.signals, max)} r="4.5" className="chart-dot"/>{p.confirmed > 0 && <g className="chart-marker-ok"><circle cx={x} cy={pointY(p.confirmed, max)} r="9"/><path d={`M${x - 4} ${pointY(p.confirmed, max)}l3 3 6-7`}/></g>}{p.unconfirmed > 0 && <g className="chart-marker-bad"><circle cx={x} cy={pointY(p.unconfirmed, max)} r="9"/><path d={`M${x - 4} ${pointY(p.unconfirmed, max) - 4}l8 8M${x + 4} ${pointY(p.unconfirmed, max) - 4}l-8 8`}/></g>}<text x={x} y="181" textAnchor="middle">{p.day}</text></g>; })}</svg></>;
}
