import { useEffect, useMemo, useState } from 'react';
import './deltaCreate.css';
import { DELTA_CREATE_CATEGORIES, DELTA_CREATE_DISTRICTS, DELTA_CREATE_STORAGE_KEY, type DeltaCreateDraft, type DeltaCreateStep } from './deltaCreateTypes';
import { buildDeltaStatement, createEmptyDeltaDraft, getChangeTypeOptions, getImpactOptions, getSubjectPlaceholder, isStepComplete, resetDependentFields, restoreDeltaDraft, serializeDeltaDraft, validateDeltaStep } from './deltaCreateLogic';

const steps: Array<{ id: DeltaCreateStep; label: string }> = [{ id: 1, label: 'Место' }, { id: 2, label: 'Изменение' }, { id: 3, label: 'Контекст' }, { id: 4, label: 'Проверка' }];
const periodOptions = [{ value: 'today', label: 'Сегодня' }, { value: 'last_3_days', label: 'Последние 3 дня' }, { value: 'last_week', label: 'Последняя неделя' }, { value: 'last_2_4_weeks', label: 'Последние 2–4 недели' }] as const;
const directionLabels = { positive: 'Стало лучше', negative: 'Стало хуже', '': 'Не выбрано' };
const periodLabels = Object.fromEntries(periodOptions.map((o) => [o.value, o.label]));

function Progress({ draft, setStep }: { draft: DeltaCreateDraft; setStep: (step: DeltaCreateStep) => void }) {
  const canOpen = (target: DeltaCreateStep) => target <= draft.currentStep || steps.filter((s) => s.id < target).every((s) => isStepComplete(draft, s.id));
  return <nav className="delta-create-progress" aria-label="Шаги конструктора"><p>Шаг {draft.currentStep} из 4</p><ol>{steps.map((step) => <li key={step.id}><button type="button" aria-current={draft.currentStep === step.id ? 'step' : undefined} disabled={!canOpen(step.id)} onClick={() => canOpen(step.id) && setStep(step.id)}><span className="wide">{step.label}</span><span className="narrow">{step.id}</span></button></li>)}</ol></nav>;
}
function OptionButton({ active, children, onClick }: { active: boolean; children: React.ReactNode; onClick: () => void }) { return <button type="button" className={active ? 'delta-create-option active' : 'delta-create-option'} aria-pressed={active} onClick={onClick}>{children}</button>; }
function LocationStep({ draft, update }: { draft: DeltaCreateDraft; update: (patch: Partial<DeltaCreateDraft>) => void }) { return <section><h2>Где это изменилось?</h2><fieldset><legend>Территория</legend><div className="delta-create-grid">{DELTA_CREATE_DISTRICTS.map((district) => <OptionButton key={district.code} active={draft.districtCode === district.code} onClick={() => update({ districtCode: district.code, districtLabel: district.label })}>{district.label}</OptionButton>)}</div></fieldset><label>Улица, остановка, участок или ориентир<input value={draft.locationHint} maxLength={120} onChange={(e) => update({ locationHint: e.target.value })} placeholder="Например: район остановки Попова" /></label><p className="delta-create-counter">{draft.locationHint.length}/120</p><p className="delta-create-note">На следующем этапе здесь появятся поиск и выбор точки на карте.</p></section>; }
function ChangeStep({ draft, update }: { draft: DeltaCreateDraft; update: (patch: Partial<DeltaCreateDraft>, changed?: 'direction' | 'subject' | 'changeType') => void }) {
  const preview = draft.statementMode === 'auto' ? buildDeltaStatement(draft) : draft.statement;
  return <section><h2>Что изменилось?</h2><fieldset><legend>Направление</legend><div className="delta-create-grid two"><OptionButton active={draft.direction === 'positive'} onClick={() => update({ direction: 'positive' }, 'direction')}><strong>Стало лучше</strong><span>Изменение облегчило, ускорило или улучшило ситуацию.</span></OptionButton><OptionButton active={draft.direction === 'negative'} onClick={() => update({ direction: 'negative' }, 'direction')}><strong>Стало хуже</strong><span>Изменение усложнило, замедлило или ухудшило ситуацию.</span></OptionButton></div></fieldset><fieldset><legend>Категория</legend><div className="delta-create-grid">{DELTA_CREATE_CATEGORIES.map((category) => <OptionButton key={category.slug} active={draft.categorySlug === category.slug} onClick={() => update({ categorySlug: category.slug })}><strong>{category.title}</strong><span>{category.description}</span></OptionButton>)}</div></fieldset><fieldset><legend>Тип изменения</legend><div className="delta-create-grid">{getChangeTypeOptions(draft.direction).map((option) => <OptionButton key={option.value} active={draft.changeType === option.value} onClick={() => update({ changeType: option.value }, 'changeType')}>{option.label}</OptionButton>)}</div></fieldset><label>Что именно изменилось?<input value={draft.subject} maxLength={80} onChange={(e) => update({ subject: e.target.value }, 'subject')} placeholder={getSubjectPlaceholder(draft.categorySlug)} /></label><p className="delta-create-counter">{draft.subject.length}/80</p>{draft.changeType && draft.subject.trim().length >= 2 && <article className="delta-create-preview"><p>Ваша Дельта</p>{draft.statementMode === 'manual' ? <><textarea value={draft.statement} maxLength={180} onChange={(e) => update({ statement: e.target.value })} aria-label="Формулировка Дельты" /><p className="delta-create-counter">{draft.statement.length}/180</p><button type="button" onClick={() => update({ statementMode: 'auto', statement: buildDeltaStatement(draft) })}>Вернуть автоматическую формулировку</button></> : <><strong>{preview}</strong><button type="button" onClick={() => update({ statementMode: 'manual', statement: preview })}>Уточнить формулировку</button></>}</article>}</section>;
}
function ContextStep({ draft, update }: { draft: DeltaCreateDraft; update: (patch: Partial<DeltaCreateDraft>) => void }) { return <section><h2>Когда это началось и насколько влияет?</h2><fieldset><legend>Период</legend><div className="delta-create-grid two">{periodOptions.map((option) => <OptionButton key={option.value} active={draft.observedWindow === option.value} onClick={() => update({ observedWindow: option.value })}>{option.label}</OptionButton>)}</div></fieldset><fieldset><legend>Влияние</legend><div className="delta-create-grid two">{getImpactOptions(draft.direction).map((option) => <OptionButton key={option.value} active={draft.impactLevel === option.value} onClick={() => update({ impactLevel: option.value })}>{option.label}</OptionButton>)}</div></fieldset><label>Что именно вы заметили?<textarea value={draft.details} maxLength={500} onChange={(e) => update({ details: e.target.value })} placeholder="Коротко опишите наблюдение без обвинений и оценок людей." /></label><p className="delta-create-counter">{draft.details.length}/500</p><ul className="delta-create-rules"><li>описывайте изменение;</li><li>не публикуйте персональные данные;</li><li>не указывайте фамилии;</li><li>избегайте обвинений.</li></ul></section>; }
function ReviewStep({ draft, done }: { draft: DeltaCreateDraft; done: () => void }) { const category = DELTA_CREATE_CATEGORIES.find((c) => c.slug === draft.categorySlug); const impact = getImpactOptions(draft.direction).find((o) => o.value === draft.impactLevel); return <section><h2>Проверьте Дельту</h2><article className="delta-create-summary"><dl><dt>Место</dt><dd>{draft.districtLabel}{draft.locationHint ? ` · ${draft.locationHint}` : ''}</dd><dt>Направление</dt><dd>{directionLabels[draft.direction]}</dd><dt>Категория</dt><dd>{category?.title}</dd><dt>Формулировка</dt><dd>{draft.statement}</dd><dt>Период</dt><dd>{draft.observedWindow ? periodLabels[draft.observedWindow] : ''}</dd><dt>Влияние</dt><dd>{impact?.label}</dd>{draft.details && <><dt>Пояснение</dt><dd>{draft.details}</dd></>}</dl></article><aside className="delta-create-next"><h3>Что произойдёт дальше</h3><p>На этапе 3.2 система проверит похожие Дельты рядом. На этапе 3.3 черновик можно будет опубликовать на карте.</p></aside><button className="primary" type="button" onClick={done}>Черновик готов</button></section>; }
export function DeltaCreateLabPage() {
  const [draft, setDraft] = useState(createEmptyDeltaDraft); const [errors, setErrors] = useState<string[]>([]); const [result, setResult] = useState(false); const [pending, setPending] = useState<DeltaCreateDraft | null>(() => { const raw = localStorage.getItem(DELTA_CREATE_STORAGE_KEY); const restored = restoreDeltaDraft(raw); if (!restored && raw) localStorage.removeItem(DELTA_CREATE_STORAGE_KEY); return restored; }); const [confirmReset, setConfirmReset] = useState(false);
  useEffect(() => { const hasContent = draft.districtCode || draft.direction || draft.categorySlug || draft.subject.trim() || draft.statement.trim() || draft.observedWindow || draft.impactLevel || draft.details.trim(); if (!hasContent) return; const id = window.setTimeout(() => localStorage.setItem(DELTA_CREATE_STORAGE_KEY, serializeDeltaDraft(draft)), 300); return () => window.clearTimeout(id); }, [draft]);
  const update = (patch: Partial<DeltaCreateDraft>, changed?: 'direction' | 'subject' | 'changeType') => setDraft((current) => { const next = { ...current, ...patch }; return changed ? resetDependentFields(next, changed) : next; });
  const stepErrors = useMemo(() => validateDeltaStep(draft, draft.currentStep), [draft]);
  const goNext = () => { const currentErrors = validateDeltaStep(draft, draft.currentStep); setErrors(currentErrors); if (!currentErrors.length && draft.currentStep < 4) update({ currentStep: (draft.currentStep + 1) as DeltaCreateStep }); };
  const startOver = () => { if (!confirmReset) { setConfirmReset(true); return; } localStorage.removeItem(DELTA_CREATE_STORAGE_KEY); setDraft(createEmptyDeltaDraft()); setPending(null); setResult(false); setConfirmReset(false); };
  if (pending) return <main className="delta-create-lab"><section className="delta-create-card" aria-live="polite"><h1>У вас есть незавершённая Дельта</h1><button className="primary" onClick={() => { setDraft(pending); setPending(null); }}>Продолжить</button><button onClick={startOver}>{confirmReset ? 'Подтвердить начало заново' : 'Начать заново'}</button></section></main>;
  if (result) return <main className="delta-create-lab"><section className="delta-create-card delta-create-result" aria-live="polite"><h1>Черновик Дельты готов</h1><p>Форма, тексты и логика готовы к подключению географии и Supabase.</p><button onClick={() => setResult(false)}>Вернуться к редактированию</button><button onClick={startOver}>{confirmReset ? 'Подтвердить начало заново' : 'Начать заново'}</button></section></main>;
  return <main className="delta-create-lab"><section className="delta-create-hero"><p className="delta-create-badge">Лаборатория · этап 3.1</p><h1>Что изменилось рядом с вами?</h1><p>Опишите конкретное изменение — стало лучше или хуже. Другие участники позже помогут его проверить.</p><p className="delta-create-note">На этом этапе публикация в базу ещё не выполняется.</p></section><section className="delta-create-card"><Progress draft={draft} setStep={(step) => update({ currentStep: step })} />{draft.currentStep === 1 && <LocationStep draft={draft} update={update} />}{draft.currentStep === 2 && <ChangeStep draft={draft} update={update} />}{draft.currentStep === 3 && <ContextStep draft={draft} update={update} />}{draft.currentStep === 4 && <ReviewStep draft={draft} done={() => setResult(true)} />}{errors.length > 0 && <div className="delta-create-errors" aria-live="polite">{errors.map((error) => <p key={error}>{error}</p>)}</div>}<div className="delta-create-actions"><button type="button" disabled={draft.currentStep === 1} onClick={() => update({ currentStep: (draft.currentStep - 1) as DeltaCreateStep })}>Назад</button>{draft.currentStep < 4 && <button type="button" className="primary" disabled={stepErrors.length > 0} onClick={goNext}>Далее</button>}{draft.currentStep === 4 && <button type="button" onClick={startOver}>{confirmReset ? 'Подтвердить начало заново' : 'Начать заново'}</button>}</div></section></main>;
}
