import { describe, expect, it, vi } from 'vitest';
import { createEmptyDeltaDraft } from './deltaCreateLogic';
import { buildCreateDeltaInput, buildDeltaSharePayload, canConfirmExisting, canNavigateToStep, canPublishSeparate, createDemoDeltaResult, mapDeltaPublishError, resetProductionDraftAfterSuccess, shareDeltaPayload } from './deltaCreateProductionLogic';
import type { DeltaCreateDraft } from './deltaCreateTypes';

function draft(): DeltaCreateDraft { return { ...createEmptyDeltaDraft(), currentStep: 4, lat: 58.01, lng: 56.25, locationLabel: ' Пермь ', locationSource: 'map', direction: 'positive', categorySlug: 'transport', changeType: 'faster', subject: '  автобус  ', statement: '  Автобус стал быстрее  ', observedWindow: 'today', impactLevel: 'noticeable', details: '   ', selectedSimilarDeltaId: 'similar-id', similarDecision: 'existing' }; }

describe('deltaCreateProductionLogic', () => {
  it('builds safe create input', () => { const input = buildCreateDeltaInput(draft(), 'circle-1'); expect(input.circleId).toBe('circle-1'); expect(input.citySlug).toBe('perm'); expect(input.lat).toBe(58.01); expect(input.lng).toBe(56.25); expect(input.subject).toBe('автобус'); expect(input.statement).toBe('Автобус стало быстрее'); expect(input.details).toBeNull(); expect(input).not.toHaveProperty('userId'); expect(input).not.toHaveProperty('token'); expect(input).not.toHaveProperty('selectedSimilarDeltaId'); });
  it('validates separate and existing paths', () => { const d = draft(); expect(canPublishSeparate(d)).toBe(true); expect(canConfirmExisting(d)).toBe(true); expect(canPublishSeparate({ ...d, lat: null })).toBe(false); expect(canConfirmExisting({ ...d, selectedSimilarDeltaId: null })).toBe(false); expect(() => buildCreateDeltaInput({ ...d, lat: null }, 'c')).toThrow(); });
  it('builds share payload without private fields', () => { const payload = buildDeltaSharePayload({ id: 'delta-1', statement: 'Автобус стал быстрее' }, 'created_new', 'https://host/uzor/#/contribute'); expect(payload.text).toContain('Автобус стал быстрее'); expect(payload.url).toContain('#/map?delta=delta-1'); expect(JSON.stringify(payload)).not.toContain('58.01'); expect(JSON.stringify(payload)).not.toContain('circle'); });
  it('maps known and unknown errors safely', () => { expect(mapDeltaPublishError(new Error('not_authenticated'))).toContain('Нужно войти'); expect(mapDeltaPublishError({ code: 'not_circle_member' })).toContain('не подключены'); expect(mapDeltaPublishError(new Error('invalid_coordinates'))).toContain('место'); expect(mapDeltaPublishError(new Error('author_reaction_locked'))).toContain('автора'); expect(mapDeltaPublishError(new Error('select * from secret'))).toBe('Не удалось выполнить действие. Попробуйте ещё раз.'); });

  it('blocks future invalid progress navigation', () => { const empty = createEmptyDeltaDraft(); expect(canNavigateToStep(4, empty)).toBe(false); const d = draft(); expect(canNavigateToStep(2, d)).toBe(true); expect(canNavigateToStep(4, { ...d, currentStep: 1 })).toBe(true); });
  it('reports honest share statuses', async () => { const payload = buildDeltaSharePayload({ id: 'delta-1', statement: 'Тест' }, 'created_new', 'https://host/#/contribute'); await expect(shareDeltaPayload(payload, { share: vi.fn(async () => undefined) } as unknown as Navigator)).resolves.toBe('Дельта отправлена'); await expect(shareDeltaPayload(payload, { share: vi.fn(async () => { throw new DOMException('cancel', 'AbortError'); }) } as unknown as Navigator)).resolves.toBe('Отправка отменена'); await expect(shareDeltaPayload(payload, { clipboard: { writeText: vi.fn(async () => undefined) } } as unknown as Navigator)).resolves.toBe('Ссылка на Дельту скопирована'); Object.defineProperty(document, 'execCommand', { configurable: true, value: vi.fn(() => false) }); await expect(shareDeltaPayload(payload, { clipboard: { writeText: vi.fn(async () => { throw new Error('denied'); }) } } as unknown as Navigator)).resolves.toBe('Не удалось поделиться ссылкой'); });
  it('creates demo result locally and resets draft', () => { const result = createDemoDeltaResult(draft()); expect(result.delta.status).toBe('new'); expect(result.delta.confirmCount).toBe(1); expect(result.delta.confirmationTarget).toBe(3); expect(resetProductionDraftAfterSuccess()).toEqual(createEmptyDeltaDraft()); });
});
