import { SearchBox } from '@mapbox/search-js-react';
import mapboxgl from 'mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';
import { useEffect, useRef, useState } from 'react';
import { DELTA_CREATE_DISTRICTS, type DeltaCreateDraft } from './deltaCreateTypes';
import { mapSearchResultToLocation } from './deltaGeoLogic';
import { PERM_FALLBACK } from '../deltaMap/deltaMapLogic';

type Props = { draft: DeltaCreateDraft; token?: string; update: (patch: Partial<DeltaCreateDraft>, changed?: string) => void; demo?: boolean };
const styleUrl = import.meta.env.VITE_MAPBOX_STYLE_URL || 'mapbox://styles/mapbox/dark-v11';
const demoPoints = [{ label:'Центр Перми', lat:58.0105, lng:56.2502 },{ label:'Парковый', lat:57.984, lng:56.171 },{ label:'Индустриальный район', lat:57.994, lng:56.307 }];

export function DeltaLocationPicker({ draft, token, update, demo }: Props) {
 const ref=useRef<HTMLDivElement|null>(null); const mapRef=useRef<mapboxgl.Map|null>(null); const markerRef=useRef<mapboxgl.Marker|null>(null); const statusRef=useRef<HTMLParagraphElement|null>(null); const [geoError,setGeoError]=useState(''); const [showHelp,setShowHelp]=useState(false);
 const choose=(patch: Partial<DeltaCreateDraft>)=>{ update({ ...patch, selectedSimilarDeltaId:null, similarDecision:null }, 'location'); window.setTimeout(()=>statusRef.current?.focus(),0); };
 useEffect(()=>{ if (!token || !ref.current || mapRef.current) return; mapboxgl.accessToken=token; const map=new mapboxgl.Map({ container:ref.current, style:styleUrl, center:[draft.lng ?? PERM_FALLBACK.lng, draft.lat ?? PERM_FALLBACK.lat], zoom:draft.lat?13:11.5 }); mapRef.current=map; map.addControl(new mapboxgl.NavigationControl({visualizePitch:false}), 'bottom-right'); map.on('click',(event)=>choose({ lat:event.lngLat.lat, lng:event.lngLat.lng, locationLabel:draft.locationLabel || 'Выбранная точка в Перми', locationPrecision:'point', locationSource:'map' })); return()=>{ markerRef.current?.remove(); map.remove(); mapRef.current=null; }; },[token]);
 useEffect(()=>{ if (!mapRef.current || draft.lat===null || draft.lng===null) return; markerRef.current?.remove(); markerRef.current=new mapboxgl.Marker().setLngLat([draft.lng,draft.lat]).addTo(mapRef.current); mapRef.current.flyTo({ center:[draft.lng,draft.lat], zoom:13, essential:false }); },[draft.lat,draft.lng]);
 const geolocate=()=>{ setGeoError(''); if (!navigator.geolocation) { setGeoError('Доступ к местоположению не предоставлен. Выберите место через поиск или карту.'); return; } navigator.geolocation.getCurrentPosition(pos=>choose({ lat:pos.coords.latitude, lng:pos.coords.longitude, locationLabel:'Моё местоположение в Перми', locationPrecision:'point', locationSource:'geolocation' }),()=>setGeoError('Доступ к местоположению не предоставлен. Выберите место через поиск или карту.'),{ enableHighAccuracy:false, timeout:10000 }); };
 if (!token && !demo) return <section className="delta-location-setup" aria-live="polite"><h3>Для выбора места нужна настройка Mapbox</h3><p>Добавьте VITE_MAPBOX_ACCESS_TOKEN в GitHub Actions Variables.</p><button type="button" onClick={()=>setShowHelp(v=>!v)}>Открыть инструкцию</button>{showHelp&&<p>Откройте docs/MAPBOX_SETUP.md и проверьте переменные VITE_MAPBOX_ACCESS_TOKEN и VITE_MAPBOX_STYLE_URL.</p>}</section>;
 return <div className="delta-location-picker"><label id="delta-search-label">Поиск места</label>{token ? <SearchBox accessToken={token} placeholder="Район, улица или место" options={{ language:'ru', country:'RU', types:'address,street,place,poi', proximity:[PERM_FALLBACK.lng,PERM_FALLBACK.lat] }} onRetrieve={(res: unknown)=>{ const loc=mapSearchResultToLocation(res); if (loc) choose(loc); }} /> : <div className="delta-demo-points"><p>Демо-режим · используются учебные точки</p>{demoPoints.map(p=><button type="button" key={p.label} onClick={()=>choose({ ...p, locationLabel:p.label, locationPrecision:'point', locationSource:'map' })}>{p.label}</button>)}</div>}<div ref={ref} role="application" aria-label="Карта выбора места" className="delta-location-map">{!token && demo ? 'Демо-точки доступны кнопками выше' : null}</div><button type="button" onClick={geolocate}>Моё местоположение</button>{geoError&&<p className="delta-create-error" role="status">{geoError}</p>}<label>Уточните район<select value={draft.districtCode} onChange={(e)=>{ const d=DELTA_CREATE_DISTRICTS.find(x=>x.code===e.target.value); update({ districtCode:d?.code ?? '', districtLabel:d?.label ?? '' }); }}><option value="">Не уверен</option>{DELTA_CREATE_DISTRICTS.filter(d=>d.code!=='perm-all'&&d.code!=='other').map(d=><option key={d.code} value={d.code}>{d.label.replace(' район','')}</option>)}</select></label><p tabIndex={-1} ref={statusRef} aria-live="polite">{draft.locationLabel ? `Выбрано: ${draft.locationLabel}` : 'Найдите место или укажите точку на карте'}</p><p className="delta-create-note">Точная выбранная точка используется для поиска похожих Дельт. На публичной карте координаты округляются сервером.</p></div>;
}
