import { describe, expect, it } from 'vitest';
import { createEmptyDeltaDraft, restoreDeltaDraft, serializeDeltaDraft } from './deltaCreateLogic';
import { buildSimilarSearchInput, findDemoSimilarDeltas, formatDistance, isLocationComplete, isValidCoordinate, shouldResetSimilarDecision } from './deltaGeoLogic';
import type { DeltaMapItem } from '../deltas/deltaTypes';
const draft = () => ({ ...createEmptyDeltaDraft(), lat:58, lng:56, locationLabel:'Пермь', locationSource:'map' as const, categorySlug:'transport' as const, direction:'negative' as const, changeType:'slower' as const });
const item: DeltaMapItem = { id:'1', category:{slug:'transport',title:'Транспорт',iconKey:'transport'}, direction:'negative', statement:'Тест', status:'new', confirmCount:1, disconfirmCount:0, confirmationTarget:3, priorityScore:0, location:{lat:58.001,lng:56.001,label:'Рядом'}, lastActivityAt:new Date().toISOString() };
describe('delta geo logic',()=>{
 it('валидный lat принимается',()=>expect(isValidCoordinate(58,'lat')).toBe(true));
 it('lat > 90 отклоняется',()=>expect(isValidCoordinate(91,'lat')).toBe(false));
 it('валидный lng принимается',()=>expect(isValidCoordinate(56,'lng')).toBe(true));
 it('lng > 180 отклоняется',()=>expect(isValidCoordinate(181,'lng')).toBe(false));
 it('location без lat неполная',()=>expect(isLocationComplete({...draft(),lat:null})).toBe(false));
 it('location без lng неполная',()=>expect(isLocationComplete({...draft(),lng:null})).toBe(false));
 it('district необязателен',()=>expect(isLocationComplete(draft())).toBe(true));
 it('formatDistance показывает метры',()=>expect(formatDistance(450)).toBe('примерно 450 м'));
 it('formatDistance показывает километры',()=>expect(formatDistance(1200)).toBe('примерно 1,2 км'));
 it('изменение location сбрасывает similar decision',()=>expect(shouldResetSimilarDecision('location')).toBe(true));
 it('изменение category сбрасывает similar decision',()=>expect(shouldResetSimilarDecision('categorySlug')).toBe(true));
 it('изменение direction сбрасывает similar decision',()=>expect(shouldResetSimilarDecision('direction')).toBe(true));
 it('изменение changeType сбрасывает similar decision',()=>expect(shouldResetSimilarDecision('changeType')).toBe(true));
 it('изменение details не обязано сбрасывать similar decision',()=>expect(shouldResetSimilarDecision('details')).toBe(false));
 it('search input получает radius 1000',()=>expect(buildSimilarSearchInput(draft(),'circle')?.radiusM).toBe(1000));
 it('search input получает days 14',()=>expect(buildSimilarSearchInput(draft(),'circle')?.days).toBe(14));
 it('search input не содержит userId',()=>expect(buildSimilarSearchInput(draft(),'circle')).not.toHaveProperty('userId'));
 it('search input не содержит token',()=>expect(buildSimilarSearchInput(draft(),'circle')).not.toHaveProperty('token'));
 it('demo similar ищет по category',()=>expect(findDemoSimilarDeltas({...draft(),categorySlug:'services'},[item])).toHaveLength(0));
 it('demo similar ищет по direction',()=>expect(findDemoSimilarDeltas({...draft(),direction:'positive'},[item])).toHaveLength(0));
 it('damaged geo draft безопасно игнорируется',()=>expect(restoreDeltaDraft('{bad')).toBeNull());
 it('координаты сохраняются и восстанавливаются',()=>{ const restored=restoreDeltaDraft(serializeDeltaDraft(draft())); expect(restored?.lat).toBe(58); expect(restored?.lng).toBe(56); });
 it('неизвестный locationSource не восстанавливается',()=>{ const restored=restoreDeltaDraft(JSON.stringify({...draft(),locationSource:'bad'})); expect(restored?.locationSource).toBeNull(); });
});
