import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { useCallback, useEffect, useRef, useState } from 'react';
import { DELTA_CREATE_DISTRICTS, type DeltaCreateDraft } from './deltaCreateTypes';
import { PERM_FALLBACK } from '../deltaMap/deltaMapLogic';
import { isWithinPermMvpArea, PERM_MVP_AREA_ERROR } from './deltaGeoLogic';

type Props = { draft: DeltaCreateDraft; update: (patch: Partial<DeltaCreateDraft>, changed?: string) => void; demo?: boolean };
const styleUrl = import.meta.env.VITE_MAP_STYLE_URL || 'https://tiles.openfreemap.org/styles/liberty';
const demoPoints = [{ label:'Центр Перми', lat:58.0105, lng:56.2502 },{ label:'Парковый', lat:57.984, lng:56.171 },{ label:'Индустриальный район', lat:57.994, lng:56.307 }];

function buildLocationLabel(draft: Pick<DeltaCreateDraft, 'districtLabel' | 'locationHint' | 'locationSource'>) { const hint=draft.locationHint.trim(); const district=draft.districtLabel.trim(); if (hint && district) return `${hint}, ${district}`; if (hint) return hint; if (district) return district; return draft.locationSource === 'geolocation' ? 'Моё местоположение в Перми' : 'Выбранная точка в Перми'; }

export function DeltaLocationPicker({ draft, update, demo }: Props) {
 const ref=useRef<HTMLDivElement|null>(null); const mapRef=useRef<maplibregl.Map|null>(null); const markerRef=useRef<maplibregl.Marker|null>(null); const statusRef=useRef<HTMLParagraphElement|null>(null); const [geoError,setGeoError]=useState(''); const [mapError,setMapError]=useState(false); const [retryKey,setRetryKey]=useState(0);
 const choose=useCallback((patch: Partial<DeltaCreateDraft>)=>{ update({ ...patch, selectedSimilarDeltaId:null, similarDecision:null }, 'location'); window.setTimeout(()=>statusRef.current?.focus(),0); },[update]);
 const choosePoint=useCallback((lat:number,lng:number, source: 'map'|'geolocation'='map')=>{ if(!isWithinPermMvpArea(lat,lng)){ setGeoError(PERM_MVP_AREA_ERROR); return; } choose({ lat, lng, locationLabel: buildLocationLabel({ ...draft, locationSource: source }), locationPrecision:'point', locationSource:source }); },[choose,draft]);
 useEffect(()=>{ if (!ref.current || mapRef.current) return; let map: maplibregl.Map; try { map=new maplibregl.Map({ container:ref.current, style:styleUrl, center:[draft.lng ?? PERM_FALLBACK.lng, draft.lat ?? PERM_FALLBACK.lat], zoom:draft.lat?13:11.5, attributionControl:{} }); } catch { window.setTimeout(()=>setMapError(true),0); return; } mapRef.current=map; map.addControl(new maplibregl.NavigationControl({visualizePitch:false}), 'bottom-right'); map.on('click',(event)=>choosePoint(event.lngLat.lat, event.lngLat.lng)); map.on('error',()=>setMapError(true)); return()=>{ markerRef.current?.remove(); map.remove(); mapRef.current=null; }; },[retryKey,choosePoint,draft.lat,draft.lng]);
 useEffect(()=>{ if (!mapRef.current || draft.lat===null || draft.lng===null) return; markerRef.current?.remove(); markerRef.current=new maplibregl.Marker().setLngLat([draft.lng,draft.lat]).addTo(mapRef.current); mapRef.current.flyTo({ center:[draft.lng,draft.lat], zoom:13, essential:false }); },[draft.lat,draft.lng]);
 useEffect(()=>{ if (draft.lat===null || draft.lng===null || draft.locationSource==='geolocation') return; const label=buildLocationLabel(draft); if (label!==draft.locationLabel) update({ locationLabel: label }); },[draft,update]);
 const geolocate=()=>{ setGeoError(''); if (!navigator.geolocation) { setGeoError('Доступ к местоположению не предоставлен. Выберите точку на карте.'); return; } navigator.geolocation.getCurrentPosition(pos=>choosePoint(pos.coords.latitude, pos.coords.longitude, 'geolocation'),err=>setGeoError(err.code===err.TIMEOUT?'Не удалось получить местоположение. Выберите точку на карте.':'Доступ к местоположению не предоставлен. Выберите точку на карте.'),{ enableHighAccuracy:false, timeout:10000 }); };
 const retry=()=>{ setMapError(false); markerRef.current?.remove(); mapRef.current?.remove(); mapRef.current=null; setRetryKey(k=>k+1); };
 return <div className="delta-location-picker">{demo&&<div className="delta-demo-points"><p>Демо-режим · быстрый выбор учебной точки</p>{demoPoints.map(p=><button type="button" key={p.label} onClick={()=>choose({ lat:p.lat, lng:p.lng, locationLabel:p.label, locationPrecision:'point', locationSource:'map' })}>{p.label}</button>)}</div>}<div ref={ref} role="application" aria-label="Карта выбора места" className="delta-location-map" />{mapError&&<div className="delta-map-local-error" role="alert"><h3>Не удалось открыть карту</h3><p>Проверьте соединение или попробуйте ещё раз.</p><button type="button" onClick={retry}>Повторить</button></div>}<button type="button" onClick={geolocate}>Моё местоположение</button>{geoError&&<p className="delta-create-error" role="status">{geoError}</p>}<label>Уточните район<select value={draft.districtCode} onChange={(e)=>{ const d=DELTA_CREATE_DISTRICTS.find(x=>x.code===e.target.value); update({ districtCode:d?.code ?? '', districtLabel:d?.label ?? '' }); }}><option value="">Не уверен</option>{DELTA_CREATE_DISTRICTS.filter(d=>d.code!=='perm-all'&&d.code!=='other').map(d=><option key={d.code} value={d.code}>{d.label.replace(' район','')}</option>)}</select></label><label>Уточнение места<input value={draft.locationHint} maxLength={120} onChange={(e)=>update({ locationHint:e.target.value.slice(0,120) })} placeholder="Например: остановка Попова или участок улицы Ленина" /></label><p className="delta-create-note">Можно указать ориентир. Точку всё равно нужно выбрать на карте.</p><p tabIndex={-1} ref={statusRef} aria-live="polite">{draft.locationLabel ? `Выбрано: ${draft.locationLabel}` : 'Выберите точку на карте или используйте геолокацию'}</p><p className="delta-create-note">Точная выбранная точка используется для поиска похожих Дельт. На публичной карте координаты округляются сервером.</p></div>;
}
