import { Link } from 'react-router-dom';
import { BoltIcon, CarIcon, CheckOrb, HeroEmblem, LineIcon, MetricIcon, PulseLogo, RingIcon, ShieldIcon } from './WrappedReferenceV2Icons';
import { wrappedReferenceV2Data as data } from './wrappedReferenceV2Data';
import './wrappedReferenceV2.css';

const nav = [['map','Карта давления'],['exchange','Биржа ожиданий'],['tarot','Таро дня'],['circle','Пульс круга'],['signal','Сигналы'],['topics','Подтемы'],['radar','Радар'],['wrapped','Wrapped'],['profile','Профиль']];
const statCards = [
  ['pink','Главная тема недели',data.mainTheme,'Вы замечали чаще других в этой теме.',<CarIcon />],
  ['blue','3 ваших сигнала','подтвердились','Отличная интуиция и чтение контекста.',<CheckOrb />],
  ['cyan','Точность ожиданий',`${data.accuracy}%`,'Вы точнее 62% людей на платформе.',<RingIcon />],
  ['violet','1 раз вы были','раньше других','Ваш сигнал опередил круг на 6 часов.',<BoltIcon />],
  ['green','Ваш стиль','осторожный аналитик','Вы взвешиваете риски и подтверждаете факты.',<ShieldIcon />],
] as const;
const metrics = [['pulse','Сигналов за неделю',data.signalsThisWeek,'↑ 28% vs прошл. неделя'],['shield','Подтверждено',data.confirmedSignals,'↑ 17% vs прошл. неделя'],['target','Точность',`${data.accuracy}%`,'↑ 12% vs прошл. неделя'],['bolt','Раньше круга',data.earlySignals,'↑ 1 vs прошл. неделя'],['flame','Серия недель',data.weekStreak,'Лучший результат!']];

function Sidebar(){return <aside className="wr-ref-sidebar"><Link to="/" className="wr-ref-brand"><PulseLogo/><span>ПУЛЬС</span></Link><nav>{nav.map(([icon,label])=><span className={label==='Wrapped'?'active':''} key={label}><LineIcon name={icon}/>{label}</span>)}</nav><div className="wr-ref-status"><i><MetricIcon type="flame"/></i><div><span>Ваш статус</span><b>{data.status}</b><em>Точность: {data.accuracy}%</em></div></div></aside>}
function Header(){return <header className="wr-ref-header"><div><h1>Личный Wrapped реальности</h1><p>Ваш личный отчёт: что вы заметили, где были правы и где опередили круг.</p></div><div><button><LineIcon name="tarot"/> Эта неделя</button><button><LineIcon name="exchange"/> Поделиться</button></div></header>}
function Donut(){const r=55,l=2*Math.PI*r;return <div className="wr-ref-donut"><svg viewBox="0 0 150 150"><defs><linearGradient id="donutGrad" x1="0" x2="1"><stop stopColor="#18e7ff"/><stop offset=".55" stopColor="#9a5cff"/><stop offset="1" stopColor="#22ffc1"/></linearGradient></defs><circle cx="75" cy="75" r={r} className="bg"/><circle cx="75" cy="75" r={r} className="fg" strokeDasharray={l} strokeDashoffset={l-l*data.accuracy/100}/><text x="75" y="84" textAnchor="middle">{data.accuracy}%</text></svg><span>+12%</span><p>Отличный результат!</p></div>}
function Chart(){const pts='16,122 54,104 91,76 128,76 165,76 203,99 240,72 277,84 314,58 351,56 388,49 426,72 463,79 500,105 537,75 574,66 611,58 648,72';return <svg className="wr-ref-chart" viewBox="0 0 670 160"><defs><filter id="wrLine"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{[54,128,203,277,351,426,500,574].map(x=><line key={x} x1={x} x2={x} y1="20" y2="132"/>)}<polyline points={pts} filter="url(#wrLine)"/><g>{[16,91,240,314,500,574,611].map((x,i)=><circle key={x} cx={x} cy={[122,76,72,58,105,75,58][i]} r="10" className="ok"/>)}<circle cx="165" cy="76" r="10" className="bad"/><circle cx="388" cy="49" r="10" className="bad"/></g>{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((d,i)=><text key={d} x={18+i*96} y="153">{d}</text>)}</svg>}

export function WrappedReferenceV2Page(){return <div className="wr-ref-page"><Sidebar/><main><Header/><section className="wr-ref-hero"><article className="card hero"><HeroEmblem/><div><p>Ваш итог недели</p><h2>{data.status}</h2><small>Вы замечаете сдвиги раньше круга.</small><b>Вы в числе 23% самых точных</b></div></article>{statCards.map(([c,k,v,t,icon])=><article className={`card stat ${c}`} key={c}><p>{k}</p><h3>{v}</h3><div className="stat-icon">{icon}</div><small>{t}</small></article>)}</section><section className="wr-ref-mid"><article className="card"><h2>Ваша точность за неделю ⓘ</h2><Donut/></article><article className="card activity"><div className="head"><h2>Активность сигналов ⓘ</h2><button>По дням⌄</button></div><div className="legend"><span>Ваши сигналы</span><span>Подтверждено</span><span>Не подтвердилось</span></div><Chart/></article><article className="card themes"><h2>Что вы замечали ⓘ</h2>{data.topThemes.map((t,i)=><div className="theme" key={t.label}><em>{i+1}</em><b>{t.label}</b><span>{t.share}%</span><i><u style={{width:`${t.share*2}%`}}/></i></div>)}<button>Смотреть все темы ›</button></article></section><section className="wr-ref-low"><article className="card right"><div className="head"><h2>Где вы были правы ⓘ</h2><button>Смотреть все</button></div>{data.rightSignals.map(s=><div className="signal" key={s.title}><i><MetricIcon type="shield"/></i><b>{s.title}<em>{s.tag}</em></b><span>Подтверждено<br/><small>{s.time}</small></span><strong aria-hidden="true">›</strong></div>)}</article><article className="card progress"><h2>Ваш прогресс ⓘ</h2><div className="levels"><span><MetricIcon type="target"/><b>Сигнальный разведчик</b><em>Получено</em></span><span className="current"><MetricIcon type="pulse"/><b>{data.status}</b><em>Текущий уровень</em></span><span><MetricIcon type="bolt"/><b>Тренд-предвидец</b><em>До следующего: {data.xpToNextLevel} XP</em></span></div><div className="xp"><p>До следующего уровня</p><h3>{data.xp.toLocaleString('ru-RU')} <span>XP</span></h3><i><u/></i><small>из 10 000 XP</small><em>Продолжайте замечать сдвиги раньше других!</em></div></article></section><section className="wr-ref-metrics">{metrics.map(([icon,k,v,copy])=><article className={`card metric ${icon}`} key={k}><MetricIcon type={icon as string}/><p>{k}</p><h3>{v}</h3><small>{copy}</small></article>)}</section></main></div>}
