import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { motion, useReducedMotion } from 'framer-motion';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { catalog as demoCatalog, demoContributions } from '../data/demo/catalog';
import { aggregateContributions, upsertContribution } from '../lib/aggregation/aggregation';
import { ensureAnonymousSession, hasSupabaseSession } from '../lib/supabase/auth';
import { getThemeSnapshot, isCurrentUserCurator, joinCircleByCode, listPendingCandidates, loadActiveTheme, loadCatalog, reviewCandidateProposal, submitCandidateProposal, upsertContributionRpc } from '../lib/supabase/api';
import type { ActiveTheme, BranchAggregate, CandidateProposal, CatalogItem, Evidence, Intensity, Layer, ThemeSnapshot } from '../types/domain';
import { appMode, isDemoMode, isProductionConfigured } from './appMode';
import { t } from './text';
import { LabShell } from '../lab/LabShell';
import { LabV4Shell } from '../lab/v4/LabV4Shell';
import { WrappedPage } from '../features/wrapped/WrappedPage';
import { WrappedReferencePage } from '../lab/wrappedReference/WrappedReferencePage';
import { WrappedReferenceV2Page } from '../lab/wrappedReferenceV2/WrappedReferenceV2Page';
import '../styles/main.css';

const emptySnapshot: ThemeSnapshot = { participantCount: 0, branchCount: 0, threadCount: 0, branches: [], convergence: [], clarity: 0 };
const layerList: Layer[] = ['tension', 'support', 'potential'];
const layerNames: Record<Layer, string> = { tension: 'Забирает', support: 'Возвращает', potential: 'Можно сдвинуть' };
const layerQuestions: Record<Layer, string> = { tension: 'Что забирает?', support: 'Что возвращает?', potential: 'Что можно сдвинуть?' };
const layerHints: Record<Layer, string> = { tension: 'Где люди теряют силы, время или свободу движения.', support: 'Что делает день легче и возвращает время.', potential: 'Какие точки люди считают возможностью изменить ситуацию.' };
const preferredContextKey = 'uzor.preferredContext.v2';

type CircleStatusKind = 'fog' | 'sparks' | 'contour' | 'pattern' | 'fork';
type DemoScenario = 'fog' | 'contour' | 'fork';

const demoScenarioContributions: Record<DemoScenario, typeof demoContributions> = {
  fog: demoContributions.slice(0, 1),
  contour: [
    ...demoContributions.slice(0, 1),
    { ...demoContributions[0], id: 'demo-c2', userId: 'demo-2', groupId: 'family', evidence: 'observed' as Evidence, intensity: 'high' as Intensity },
    { ...demoContributions[0], id: 'demo-c3', userId: 'demo-3', groupId: 'district', intensity: 'medium' as Intensity },
    { ...demoContributions[0], id: 'demo-c4', userId: 'demo-4', groupId: 'work', intensity: 'high' as Intensity },
    { ...demoContributions[0], id: 'demo-c5', userId: 'demo-5', groupId: 'family', evidence: 'observed' as Evidence },
    { ...demoContributions[0], id: 'demo-c6', userId: 'demo-6', groupId: 'district' },
    { ...demoContributions[1], id: 'demo-c7', userId: 'demo-7', groupId: 'work' },
  ],
  fork: [
    ...demoContributions.slice(0, 1),
    { ...demoContributions[0], id: 'demo-f2', userId: 'demo-2', groupId: 'family' },
    { ...demoContributions[0], id: 'demo-f3', userId: 'demo-3', groupId: 'district' },
    { ...demoContributions[0], id: 'demo-f4', userId: 'demo-4', consequenceId: 'late', groupId: 'work' },
    { ...demoContributions[0], id: 'demo-f5', userId: 'demo-5', consequenceId: 'late', groupId: 'family', evidence: 'observed' as Evidence },
    { ...demoContributions[0], id: 'demo-f6', userId: 'demo-6', consequenceId: 'late', groupId: 'district' },
  ],
};

function label(items: CatalogItem[], id: string) { return items.find((i) => i.id === id)?.label ?? 'Отклик круга'; }
function humanCount(n: number) { if (n <= 0) return 'Пока нет независимых откликов.'; if (n === 1) return 'Пока один независимый отклик.'; return `Эту связь отметили ${n} человека из разных жизненных контекстов.`; }
function branchState(branch?: BranchAggregate) { if (!branch || branch.participantCount <= 1) return 'personal'; if (branch.isDivergence) return 'fork'; if (branch.participantCount < 3) return 'echo'; return 'contour'; }
function circleKind(snapshot: ThemeSnapshot): CircleStatusKind {
  if (snapshot.branches.some((b) => b.isDivergence)) return 'fork';
  if (snapshot.branches.length >= 3 && snapshot.participantCount >= 5) return 'pattern';
  if (snapshot.branches.some((b) => b.participantCount >= 3)) return 'contour';
  if (snapshot.threadCount > 0 || snapshot.branchCount > 0) return 'sparks';
  return 'fog';
}
function statusCopy(kind: CircleStatusKind) {
  return ({
    fog: ['Туман', 'В круге пока мало независимых откликов.', 'Ещё нет общего вывода.'],
    sparks: ['Искры', 'В круге появился первый след.', 'Ещё нет общего вывода.'],
    contour: ['Контур', 'Несколько людей независимо увидели одну связь.', 'Картина начинает собираться.'],
    pattern: ['Узор', 'В круге проявилось несколько связанных путей.', 'Можно увидеть общий путь без рейтингов и шума.'],
    fork: ['Развилка', 'Люди видят одну причину, но расходятся в последствиях.', 'Это не спор, а место, где картина стала глубже.'],
  } as const)[kind];
}
function Shell({ children }: { children: React.ReactNode }) { return <><header><Link to="/wrapped" className="brand">УЗОР</Link></header>{isDemoMode && <div className="demo">ДЕМО — вымышленные отклики</div>}<main>{children}</main></>; }
function SetupScreen() { return <Shell><section className="panel"><h1>Нужна настройка Supabase</h1><p>{t.setup}</p><p>Для production укажите VITE_SUPABASE_URL и VITE_SUPABASE_PUBLISHABLE_KEY. Демо-данные здесь не используются.</p></section></Shell>; }
function InvitePrompt() { return <section className="panel"><h1>Войдите в закрытый круг</h1><p>УЗОР открывается по ссылке-приглашению от куратора круга.</p><Link className="primary" to="/join">У меня есть приглашение</Link></section>; }
function scenarioFromUrl(value: string | null): DemoScenario { return value === 'contour' || value === 'fork' ? value : 'fog'; }
function useThemeData(scenario?: DemoScenario) {
  const initialDemo = scenario ? demoScenarioContributions[scenario] : demoContributions;
  const [theme, setTheme] = useState<ActiveTheme | null>(isDemoMode ? { id: 'demo-theme', circleId: 'demo-circle', title: 'Время города', subtitle: 'Как город забирает и возвращает людям время.' } : null);
  const [catalog, setCatalog] = useState<CatalogItem[]>(isDemoMode ? demoCatalog : []);
  const [snapshotState, setSnapshot] = useState<ThemeSnapshot>(emptySnapshot);
  const [demoItems, setDemoItems] = useState(initialDemo);
  const [status, setStatus] = useState<'loading' | 'ready' | 'no-circle' | 'empty-snapshot' | 'empty-catalog' | 'error'>(isDemoMode ? 'ready' : 'loading');
  const [error, setError] = useState('');
  const demoSnapshot = useMemo(() => aggregateContributions(demoItems), [demoItems]);
  const snapshot = isDemoMode ? demoSnapshot : snapshotState;
  const refresh = useCallback(async () => {
    if (isDemoMode) { setStatus(aggregateContributions(demoItems).branches.length ? 'ready' : 'empty-snapshot'); return; }
    if (!isProductionConfigured) return;
    try { setStatus('loading'); setError(''); if (!await hasSupabaseSession()) { setTheme(null); setCatalog([]); setSnapshot(emptySnapshot); setStatus('no-circle'); return; } const active = await loadActiveTheme(); if (!active) { setTheme(null); setCatalog([]); setSnapshot(emptySnapshot); setStatus('no-circle'); return; } const [items, snap] = await Promise.all([loadCatalog(active.id), getThemeSnapshot(active.id)]); setTheme(active); setCatalog(items); const normalized = { ...emptySnapshot, ...snap, branches: snap.branches ?? [], branchCount: snap.branchCount ?? snap.branches?.length ?? 0, threadCount: snap.threadCount ?? snap.branchCount ?? snap.branches?.length ?? 0 }; setSnapshot(normalized); setStatus(items.length === 0 ? 'empty-catalog' : (normalized.branches.length ? 'ready' : 'empty-snapshot')); } catch (e) { setError(e instanceof Error ? e.message : 'UZOR-LOAD-THEME: Не удалось загрузить УЗОР'); setCatalog([]); setStatus('error'); }
  }, [demoItems]);
  useEffect(() => { void Promise.resolve().then(refresh); }, [refresh]);
  useEffect(() => { if (isDemoMode && scenario) void Promise.resolve().then(() => setDemoItems(demoScenarioContributions[scenario])); }, [scenario]);
  const addDemo = (payload: Parameters<typeof upsertContribution>[1]) => setDemoItems((rows) => upsertContribution(rows, payload));
  return { theme, catalog, snapshot, status, error, refresh, addDemo };
}
function CircleStatus({ snapshot }: { snapshot: ThemeSnapshot }) { const copy = statusCopy(circleKind(snapshot)); return <section className="circle-status"><p className="eyebrow">Состояние круга</p><h2>{copy[0]}</h2><p>{copy[1]}</p><p>{copy[2]}</p><small>{humanCount(snapshot.participantCount)}</small></section>; }
function ThreadVisual({ state }: { state: 'personal' | 'echo' | 'contour' | 'fork' }) { const copy = { personal: ['Твой личный след', 'Пока эту связь отметил один человек. Она ещё не стала общим выводом.'], echo: ['Есть отклик', 'Эту связь уже заметил кто-то ещё. Картина начинает собираться.'], contour: ['Контур круга', 'Несколько людей независимо увидели этот путь.'], fork: ['Развилка', 'Люди одинаково видят начало, но по-разному ощущают, к чему оно ведёт.'] }[state]; return <div className={`thread-card ${state}`}><strong>{copy[0]}</strong><p>{copy[1]}</p></div>; }
function UzorScene({ snapshot, catalog, activeLayer }: { snapshot: ThemeSnapshot; catalog: CatalogItem[]; activeLayer?: Layer | null }) { const reduce = useReducedMotion(); const branches = snapshot.branches.slice(0, 8); return <div className="scene-wrap"><svg viewBox="0 0 760 440" role="img" aria-label="Живая картина круга"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><ellipse cx="380" cy="220" rx="330" ry="170" className="mist"/><text x="115" y="95" className="zone-label">Забирает</text><text x="620" y="95" className="zone-label">Возвращает</text><text x="380" y="385" className="zone-label">Можно сдвинуть</text>{branches.map((b, i) => { const x = b.layer === 'tension' ? 140 : b.layer === 'support' ? 620 : 380; const y = b.layer === 'potential' ? 345 : 110 + (i % 3) * 68; const midY = 170 + (i % 4) * 28; const state = branchState(b); const width = state === 'personal' ? 1.8 : state === 'echo' ? 2.6 : 4; return <Link to={`/branch/${encodeURIComponent(b.id)}`} key={b.id} aria-label={`Открыть путь ${label(catalog, b.signalId)}`}><motion.path initial={reduce ? false : { pathLength: 0, opacity: 0 }} animate={{ pathLength: 1, opacity: activeLayer && activeLayer !== b.layer ? .22 : .9 }} d={`M${x} ${y} Q380 ${midY} 380 220`} className={`thread ${b.layer} ${state}`} strokeWidth={width}/><motion.circle cx={x} cy={y} r={7 + Math.min(10, b.participantCount * 2)} className={`spark ${b.layer}`} animate={reduce ? undefined : { opacity: [.65, 1, .65] }} transition={{ duration: 3, repeat: Infinity }}/><text x={x} y={y - 18} textAnchor="middle" className="object-label">{label(catalog, b.signalId)}</text>{state === 'fork' && <path d={`M380 220 Q430 260 500 292`} className="thread fork" strokeWidth="3"/>}</Link>; })}<circle cx="380" cy="220" r="56" className="core"/><text x="380" y="214" textAnchor="middle" className="core-text">Время</text><text x="380" y="238" textAnchor="middle" className="core-text">города</text></svg></div>; }
function CircleStage({ snapshot, catalog }: { snapshot: ThemeSnapshot; catalog: CatalogItem[] }) { const [active, setActive] = useState<Layer | null>(null); return <section className="stage" id="circle-picture"><UzorScene snapshot={snapshot} catalog={catalog} activeLayer={active}/><div className="entry-grid">{layerList.map((layer) => <Link key={layer} to={`/contribute?layer=${layer}`} onMouseEnter={() => setActive(layer)} onFocus={() => setActive(layer)} onMouseLeave={() => setActive(null)} onBlur={() => setActive(null)} className={`field-entry ${layer}`}><span>{layerQuestions[layer]}</span><small>{layerHints[layer]}</small></Link>)}</div></section>; }
function Field() { const [params] = useSearchParams(); const scenario = useLocation().pathname === '/demo' ? scenarioFromUrl(params.get('scenario')) : undefined; const data = useThemeData(scenario); const location = useLocation(); if (appMode === 'production' && !isProductionConfigured) return <SetupScreen />; const joined = new URLSearchParams(location.search).get('joined') === '1'; if (data.status === 'no-circle') return <Shell><InvitePrompt /></Shell>; return <Shell><section className="hero"><p className="eyebrow">Это только у меня так?</p>{joined && <p className="status">Круг подключён</p>}<h1>Куда уходит твой час?</h1><p className="lead">То, что кажется личным,<br/>иногда уже собирается в общий узор.</p><p>Посмотри, что люди в круге связывают с потерей времени, что его возвращает и где видят точку изменения.</p><div className="hero-actions"><Link className="primary" to="/contribute?layer=tension">Проверить свой путь</Link><a href="#circle-picture">Посмотреть картину круга</a></div>{data.status === 'loading' && <p className="status">Загружаем отклики круга…</p>}{data.status === 'error' && <div className="panel"><p role="alert" className="error">{data.error}</p><button onClick={data.refresh}>Повторить</button></div>}{location.pathname === '/demo' && <DemoScenarioSwitcher scenario={scenario ?? 'fog'} />}{data.status !== 'error' && <CircleStatus snapshot={data.snapshot}/>} {data.status !== 'error' && <CircleStage snapshot={data.snapshot} catalog={data.catalog}/>}</section></Shell>; }
function DemoScenarioSwitcher({ scenario }: { scenario: DemoScenario }) { return <div className="scenario"><p>ДЕМО — вымышленные отклики</p>{(['fog','contour','fork'] as DemoScenario[]).map((s) => <Link className={scenario === s ? 'active' : ''} to={`/demo?scenario=${s}`} key={s}>{s === 'fog' ? 'Туман' : s === 'contour' ? 'Контур' : 'Развилка'}</Link>)}</div>; }
function ContributionResult({ result }: { result: 'first' | 'match' | 'fork' }) { const copy = { first: ['Ты оставил первый след', 'Пока этот путь личный. Когда его независимо заметят другие, он станет частью контура круга.'], match: ['Ты не один', 'Твой отклик усилил уже заметный путь. Картина круга стала чуть яснее.'], fork: ['Ты открыл развилку', 'Люди видят одно начало, но по-разному ощущают, к чему оно ведёт.'] }[result]; return <motion.div className="result" initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }}><div className="result-spark"/><h2>{copy[0]}</h2><p>{copy[1]}</p><Link className="primary" to="/wrapped">Посмотреть, что изменилось</Link></motion.div>; }
function Contribute() { const [params] = useSearchParams(); const data = useThemeData(); const layer = (params.get('layer') as Layer) || 'tension'; const signals = data.catalog.filter((i) => i.kind === 'signal' && i.layer === layer); const groups = data.catalog.filter((i) => i.kind === 'group'); const cons = data.catalog.filter((i) => i.kind === 'consequence'); const [step, setStep] = useState(0); const [showCandidate, setShowCandidate] = useState(false); const [draft, setDraft] = useState({ signalId: '', groupId: '', consequenceId: '', intensity: 'medium' as Intensity, evidence: 'experienced' as Evidence }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [candidate, setCandidate] = useState(''); const [result, setResult] = useState<'first' | 'match' | 'fork' | null>(null); const preferred = useMemo(() => groups.find((g) => g.id === localStorage.getItem(preferredContextKey)), [groups]); const sendCandidate = async (kind: 'signal' | 'consequence') => { if (!data.theme || !candidate.trim()) return; setBusy(true); try { if (!isDemoMode) await submitCandidateProposal(data.theme.id, layer, kind, candidate); setStep(5); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось отправить идею'); } finally { setBusy(false); } };
  const submit = async () => { if (!data.theme) return; setBusy(true); setError(''); const sameStart = data.snapshot.branches.filter((b) => b.layer === layer && b.signalId === draft.signalId); const exact = sameStart.find((b) => b.consequenceId === draft.consequenceId); try { if (isDemoMode) data.addDemo({ id: crypto.randomUUID(), userId: 'you', layer, ...draft, updatedAt: new Date().toISOString() }); else { await upsertContributionRpc({ themeId: data.theme.id, layer, ...draft }); await data.refresh(); } setResult(sameStart.length > 0 && !exact ? 'fork' : exact ? 'match' : 'first'); setStep(4); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось вплести в УЗОР'); } finally { setBusy(false); } };
  if (data.status === 'loading') return <Shell><section className="panel flow"><p className="status">Загружаем карточки темы…</p></section></Shell>; if (data.status === 'no-circle') return <Shell><InvitePrompt /></Shell>; if (data.status === 'error') return <Shell><section className="panel flow"><p role="alert" className="error">{data.error}</p><button onClick={data.refresh}>Повторить</button></section></Shell>; if (data.status === 'empty-catalog') return <Shell><section className="panel flow"><h1>{layerNames[layer]}</h1><p>Куратор ещё не подготовил карточки темы</p></section></Shell>; if (step === 4 && result) return <Shell><ContributionResult result={result}/></Shell>;
  const chooseGroup = (id: string) => { localStorage.setItem(preferredContextKey, id); setDraft({ ...draft, groupId: id }); setStep(3); };
  return <Shell><section className="panel flow"><p className="eyebrow">{layerNames[layer]}</p><h1>{step === 0 ? 'Что ты сейчас узнаёшь?' : step === 1 ? 'К чему это приводит у тебя?' : step === 2 ? 'Из какого опыта ты сейчас смотришь?' : 'Насколько это заметно?'}</h1>{error && <p role="alert" className="error">{error}</p>}{step === 0 && <><div className="choicegrid live">{signals.map((i) => <button key={i.id} onClick={() => { setDraft({ ...draft, signalId: i.id }); setStep(1); setShowCandidate(false); }}>{i.label}</button>)}</div><button className="text-link" onClick={() => setShowCandidate(true)}>У меня иначе</button>{showCandidate && <div className="candidate"><input maxLength={80} value={candidate} onChange={(e) => setCandidate(e.target.value)} placeholder="Опиши свой след"/><button disabled={busy || !candidate.trim()} onClick={() => sendCandidate('signal')}>Отправить в кандидаты</button></div>}</>}{step === 1 && <><p className="status">Выбери ближайшее последствие. Если твой путь другой — покажи его отдельно.</p><div className="choicegrid live">{cons.map((i) => <button key={i.id} onClick={() => { setDraft({ ...draft, consequenceId: i.id }); setStep(2); }}>{label(data.catalog, draft.signalId)} <span>↓</span> {i.label}</button>)}</div><button className="text-link" onClick={() => setShowCandidate(true)}>У меня другой путь</button>{showCandidate && <div className="candidate"><input maxLength={80} value={candidate} onChange={(e) => setCandidate(e.target.value)} placeholder="К чему это приводит?"/><button disabled={busy || !candidate.trim()} onClick={() => sendCandidate('consequence')}>Отправить в кандидаты</button></div>}</>}{step === 2 && <>{preferred && !draft.groupId ? <div className="context-chip">Сейчас ты отвечаешь из контекста: {preferred.label} · <button onClick={() => chooseGroup(preferred.id)}>оставить</button> <button onClick={() => localStorage.removeItem(preferredContextKey)}>изменить</button></div> : <div className="choicegrid live">{groups.map((i) => <button key={i.id} onClick={() => chooseGroup(i.id)}>{i.label}</button>)}</div>}</>}{step === 3 && <><div className="choicegrid compact"><button onClick={() => setDraft({ ...draft, intensity: 'low' })}>Слабо</button><button onClick={() => setDraft({ ...draft, intensity: 'medium' })}>Заметно</button><button onClick={() => setDraft({ ...draft, intensity: 'high' })}>Сильно</button><button onClick={() => setDraft({ ...draft, evidence: 'experienced' })}>Это мой опыт</button><button onClick={() => setDraft({ ...draft, evidence: 'observed' })}>Я замечаю это вокруг</button></div><button className="primary" disabled={busy || !draft.signalId || !draft.groupId || !draft.consequenceId} onClick={submit}>{busy ? 'Вплетаем…' : 'Вплести в УЗОР'}</button></>}{step === 5 && <p>Идея отправлена в кандидаты. Она появится в УЗОРЕ только после независимого отклика или решения куратора.</p>}</section></Shell>; }
function Join() { const [params] = useSearchParams(); const navigate = useNavigate(); const [initialCode] = useState(() => params.get('code') ?? ''); const autoJoinAttemptedRef = useRef(false); const [code, setCode] = useState(initialCode); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const join = useCallback(async (joinCode = code) => { setBusy(true); setError(''); try { await ensureAnonymousSession(); await joinCircleByCode(joinCode); navigate('/wrapped'); } catch (e) { setError(e instanceof Error ? e.message : 'UZOR-JOIN: Круг не найден. Проверь ссылку или код.'); } finally { setBusy(false); } }, [code, navigate]); useEffect(() => { if (!autoJoinAttemptedRef.current && initialCode) { autoJoinAttemptedRef.current = true; void Promise.resolve().then(() => join(initialCode)); } }, [initialCode, join]); return <Shell><section className="panel"><h1>Вход в закрытый круг</h1><input value={code} onChange={(e) => setCode(e.target.value)} placeholder="Код приглашения"/><button className="primary" disabled={busy || !code.trim()} onClick={() => join()}>{busy ? 'Входим…' : 'Войти в круг'}</button>{error && <p role="alert" className="error">{error}</p>}</section></Shell>; }
function Branch() { const { id = '' } = useParams(); const data = useThemeData(); const branch: BranchAggregate | undefined = data.snapshot.branches.find((b) => b.id === decodeURIComponent(id)); if (!branch) return <Shell><section className="panel"><h1>Нить не найдена</h1><p>Возможно, круг ещё не загрузил отклики или доступ не открыт.</p></section></Shell>; const alternatives = data.snapshot.branches.filter((b) => b.signalId === branch.signalId && b.consequenceId !== branch.consequenceId); return <Shell><section className="panel branch-detail"><p className="eyebrow">Путь в круге</p><h1>{label(data.catalog, branch.signalId)}<span>↓</span>{label(data.catalog, branch.consequenceId)}</h1><ThreadVisual state={branchState(branch)}/><p>{branch.participantCount <= 1 ? 'Пока личный след. Это ещё не общий вывод круга.' : `Эту связь независимо отметили ${branch.participantCount} человека. Чаще она проявляется в контексте: ${branch.dominantGroups.map((g) => label(data.catalog, g)).join(' и ')}.`}</p>{alternatives.length > 0 && <div><p>Другие люди чаще связывают это с:</p>{alternatives.map((a) => <Link className="chip" key={a.id} to={`/branch/${encodeURIComponent(a.id)}`}>{label(data.catalog, a.consequenceId)}</Link>)}</div>}<Link className="primary" to={`/contribute?layer=${branch.layer}`}>У меня иначе</Link></section></Shell>; }
function Curator() { const [items, setItems] = useState<CandidateProposal[]>([]); const [error, setError] = useState(''); const refresh = async () => { try { setError(''); setItems(await listPendingCandidates()); } catch { setError('Доступ denied: этот экран доступен только куратору круга.'); } }; useEffect(() => { if (!isDemoMode && isProductionConfigured) void Promise.resolve().then(refresh); }, []); if (isDemoMode) return <Shell><section className="panel"><h1>Куратор</h1><p>В демо кандидаты не публикуются.</p></section></Shell>; return <Shell><section className="panel"><h1>Кандидаты круга</h1>{error && <p role="alert">{error}</p>}{items.map((p) => <div className="candidate-card" key={p.id}><strong>{p.raw_text}</strong><p>{p.proposal_kind} · {layerNames[p.layer]}</p><button onClick={() => reviewCandidateProposal(p.id, 'approved', p.raw_text ?? '', p.proposal_kind, p.layer).then(refresh)}>Одобрить</button><button onClick={() => reviewCandidateProposal(p.id, 'rejected', '', p.proposal_kind, p.layer).then(refresh)}>Отклонить</button></div>)}</section></Shell>; }

function branchLabelForCurator(branch: BranchAggregate, catalog: CatalogItem[]) { return `${label(catalog, branch.signalId)} → ${label(catalog, branch.consequenceId)}`; }
function CuratorOverview() {
  const [status, setStatus] = useState<'loading' | 'ready' | 'denied' | 'error'>(isDemoMode ? 'ready' : 'loading');
  const [theme, setTheme] = useState<ActiveTheme | null>(isDemoMode ? { id: 'demo-theme', circleId: 'demo-circle', title: 'Время города', subtitle: 'Демо' } : null);
  const [catalog, setCatalog] = useState<CatalogItem[]>(isDemoMode ? demoCatalog : []);
  const [snapshot, setSnapshot] = useState<ThemeSnapshot>(isDemoMode ? aggregateContributions(demoContributions) : emptySnapshot);
  const [candidates, setCandidates] = useState<CandidateProposal[]>([]);
  const refresh = useCallback(async () => {
    if (isDemoMode) { setCandidates([]); setStatus('ready'); return; }
    try {
      const active = await loadActiveTheme();
      if (!active || !await isCurrentUserCurator(active.circleId)) { setStatus('denied'); return; }
      const [items, snap, pending] = await Promise.all([loadCatalog(active.id), getThemeSnapshot(active.id), listPendingCandidates()]);
      setTheme(active); setCatalog(items); setSnapshot({ ...emptySnapshot, ...snap, branches: snap.branches ?? [] }); setCandidates(pending); setStatus('ready');
    } catch (e) { console.error('[UZOR-CURATOR-OVERVIEW]', e); setStatus('error'); }
  }, []);
  useEffect(() => { void Promise.resolve().then(refresh); }, [refresh]);
  if (status === 'loading') return <Shell><section className="panel"><h1>Сводка круга</h1><p className="status">Собираем полную картину…</p></section></Shell>;
  if (status === 'denied') return <Shell><section className="panel"><h1>Сводка круга</h1><p>Этот раздел доступен только управляющему круга.</p></section></Shell>;
  if (status === 'error') return <Shell><section className="panel"><h1>Сводка круга</h1><p role="alert">Не удалось загрузить кураторскую сводку.</p><button onClick={refresh}>Повторить</button></section></Shell>;
  const confirmed = snapshot.branches.filter((b) => b.participantCount >= 3);
  const unconfirmed = snapshot.branches.filter((b) => b.participantCount < 3);
  const top = [...snapshot.branches].sort((a, b) => b.participantCount - a.participantCount).slice(0, 5);
  const weak = snapshot.branches.filter((b) => b.participantCount < 3 || b.dominantGroups.length < 2).slice(0, 4);
  return <Shell><section className="panel"><p className="eyebrow">Управляющий кругом</p><h1>Сводка круга{theme ? ` · ${theme.title}` : ''}</h1><div className="curator-overview-grid"><div className="curator-overview-card"><span>Участников</span><strong>{snapshot.participantCount}</strong></div><div className="curator-overview-card"><span>Сигналов за неделю</span><strong>{snapshot.threadCount}</strong></div><div className="curator-overview-card"><span>Активных веток</span><strong>{snapshot.branchCount || snapshot.branches.length}</strong></div><div className="curator-overview-card"><span>Подтверждённых веток</span><strong>{confirmed.length}</strong></div><div className="curator-overview-card"><span>Без подтверждения</span><strong>{unconfirmed.length}</strong></div></div><h2>Топ сигналов</h2><div className="curator-list">{top.length ? top.map((b) => <article key={b.id}><strong>{branchLabelForCurator(b, catalog)}</strong><p>{b.participantCount} участников · независимые контексты: {b.dominantGroups.length || 1} · статус: {b.participantCount >= 3 ? 'подтверждено' : b.participantCount >= 2 ? 'растёт' : 'ждёт'}</p></article>) : <p>Пока нет активных веток.</p>}</div><h2>Слабые места данных</h2><div className="curator-list">{weak.length ? weak.map((b) => <article key={b.id}><strong>{branchLabelForCurator(b, catalog)}</strong><p>{b.participantCount < 3 ? 'Мало участников' : 'Мало разных контекстов'} — попросите круг независимо проверить эту тему.</p></article>) : <p>Критичных слабых мест не видно.</p>}</div><h2>Pending candidates</h2><p>{candidates.length ? `Ожидают решения: ${candidates.length}` : 'Новых кандидатов нет.'}</p><div className="curator-actions"><button type="button">Попросить участников проверить</button><Link to="/curator" className="primary">Перейти к кандидатам</Link><Link to="/wrapped">Открыть Wrapped</Link></div></section></Shell>;
}

function Simple({ title, body }: { title: string; body: string }) { return <Shell><section className="panel"><h1>{title}</h1><p>{body}</p></section></Shell>; }
export function App() { return <Routes><Route path="/" element={<Navigate to="/wrapped" replace />} /><Route path="/join" element={<Join />} /><Route path="/contribute" element={<Contribute />} /><Route path="/branch/:id" element={<Branch />} /><Route path="/curator" element={<Curator />} /><Route path="/curator/overview" element={<CuratorOverview />} /><Route path="/about" element={<Simple title="Как читать УЗОР" body="Это не рейтинг и не доказательство. По откликам круга проявляются нити, туман, развилки и места, где чаще сходятся связи." />} /><Route path="/demo" element={<Field />} /><Route path="/lab/old-home" element={<Field />} /><Route path="/lab" element={<LabShell />} /><Route path="/lab/v4" element={<LabV4Shell />} /><Route path="/wrapped" element={<WrappedPage />} /><Route path="/lab/wrapped-reference" element={<WrappedReferencePage />} /><Route path="/lab/wrapped-reference-v2" element={<WrappedReferenceV2Page />} /></Routes>; }
