import { Link, Route, Routes, useNavigate, useSearchParams } from 'react-router-dom';
import { motion, useReducedMotion } from 'framer-motion';
import { useMemo, useState } from 'react';
import { catalog, demoContributions } from '../data/demo/catalog';
import { aggregateContributions, upsertContribution } from '../lib/aggregation/aggregation';
import { snapshotText, themeStatus } from '../lib/aggregation/interpretation';
import type { Layer } from '../types/domain';
import { t } from './text';
import '../styles/main.css';

const mode = import.meta.env.VITE_APP_MODE ?? 'demo';
const configured = Boolean(import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
function Shell({children}:{children:React.ReactNode}){return <><header><Link to="/" className="brand">{t.app}</Link><nav><Link to="/about">О проекте</Link><Link to="/curator">Куратор</Link></nav></header>{mode==='demo'&&<div className="demo">{t.demo}</div>}<main>{children}</main></>}
function Field(){const [items,setItems]=useState(demoContributions); const snapshot=useMemo(()=>aggregateContributions(items),[items]); if(mode!=='demo'&&!configured)return <Shell><section className="panel"><h1>Нужна настройка</h1><p>{t.setup}</p></section></Shell>; return <Shell><section className="hero"><p>{t.formula}</p><h1>{t.title}</h1><p>{t.subtitle}</p><div className="field"><svg viewBox="0 0 360 260" role="img" aria-label="Живое поле темы"><defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{snapshot.branches.map((b,i)=><path key={b.id} d={`M${b.layer==='tension'?60:b.layer==='support'?300:180} ${b.layer==='potential'?35:210} Q180 ${80+i*12} 180 130`} className={`thread ${b.layer} ${b.isDivergence?'fork':''}`} strokeWidth={Math.max(2,b.strength*5)} opacity={0.35+b.clarity/1.8}/>) }<circle cx="180" cy="130" r="42" className="core"/><text x="180" y="126" textAnchor="middle">Время</text><text x="180" y="146" textAnchor="middle">города</text></svg></div><div className="layers">{(['tension','support','potential'] as Layer[]).map(l=><Link className={`layer ${l}`} to={`/contribute?layer=${l}`} key={l}>{t.layers[l]}</Link>)}</div><p className="status">{themeStatus(snapshot.clarity)} · {snapshot.participantCount} участников · {snapshot.threadCount} нитей</p><div className="panel">{snapshotText(snapshot,catalog).map(s=><p key={s}>{s}</p>)}</div><button onClick={()=>setItems(upsertContribution(items,{id:crypto.randomUUID(),userId:'you',layer:'tension',signalId:'t0',groupId:'g0',consequenceId:'c0',evidence:'experienced',intensity:'medium',updatedAt:new Date().toISOString()}))}>Показать вплетение</button></section></Shell>}
function Contribute(){const [params]=useSearchParams(); const navigate=useNavigate(); const reduce=useReducedMotion(); const layer=(params.get('layer') as Layer)||'tension'; const signals=catalog.filter(i=>i.kind==='signal'&&i.layer===layer); const groups=catalog.filter(i=>i.kind==='group'); const cons=catalog.filter(i=>i.kind==='consequence'); const [step,setStep]=useState(0); const [draft,setDraft]=useState({signalId:'',groupId:'',consequenceId:'',intensity:'medium',evidence:'experienced'}); const choices=[signals,groups,cons] as const; const labels=['Что происходит','Кого сильнее касается','К чему приводит']; const submit=()=>{setStep(4); setTimeout(()=>navigate('/'), reduce?0:900)}; return <Shell><section className="panel flow"><h1>{t.layers[layer]}</h1>{step<3&&<><h2>{labels[step]}</h2><div className="choicegrid">{choices[step].map(i=><button key={i.id} onClick={()=>{setDraft({...draft,[step===0?'signalId':step===1?'groupId':'consequenceId']:i.id});setStep(step+1)}}>{i.label}</button>)}</div></>}{step===3&&<><h2>Сила и отклик</h2><div className="choicegrid"><button onClick={()=>setDraft({...draft,intensity:'low'})}>слегка</button><button onClick={()=>setDraft({...draft,intensity:'medium'})}>заметно</button><button onClick={()=>setDraft({...draft,intensity:'high'})}>сильно</button><button onClick={()=>setDraft({...draft,evidence:'experienced'})}>Это касается меня</button><button onClick={()=>setDraft({...draft,evidence:'observed'})}>Я вижу это вокруг</button></div><button className="primary" onClick={submit}>{t.weave}</button></>}{step===4&&<motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}}><h2>Картина стала чуть яснее</h2><p>Твоя нить мягко вплетается в общую картину.</p></motion.div>}</section></Shell>}
function Join(){const [params]=useSearchParams(); return <Shell><section className="panel"><h1>{params.get('join')?'Вход в круг':'Введите код круга'}</h1><p>{params.get('join')?'Закрытый круг: Время города':t.invalidInvite}</p><Link className="primary" to="/">Войти в круг</Link></section></Shell>}
function Simple({title,body}:{title:string;body:string}){return <Shell><section className="panel"><h1>{title}</h1><p>{body}</p></section></Shell>}
export function App(){return <Routes><Route path="/" element={<Field/>}/><Route path="/join" element={<Join/>}/><Route path="/contribute" element={<Contribute/>}/><Route path="/branch/:id" element={<Simple title="Ветка" body="Можно отметить: Меня касается, Вижу вокруг или У меня иначе."/>}/><Route path="/curator" element={<Simple title="Куратор" body="Здесь проверяются идеи-кандидаты: одобрить или отклонить без публикации сырого текста."/>}/><Route path="/about" element={<Simple title="Как читать УЗОР" body="Это не рейтинг и не доказательство. По откликам круга проявляются нити, туман, развилки и места, где чаще сходятся связи."/>}/><Route path="/demo" element={<Field/>}/></Routes>}
