import { useCallback, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ProductShell } from '../../app/ProductShell';
import { useAuth } from '../auth/AuthProvider';
import { ProductGuide } from '../guide/ProductGuide';
import { usePwaInstallSurface } from '../pwa/usePwaInstallSurface';
import { useDialogFocus } from '../guide/useDialogFocus';

const onboardingPrefix='uzor.onboarding.';
const draftKeys=['uzor_delta_create_core_v1','uzor_delta_create_geo_v1','uzor_delta_create_v1'] as const;
export function SettingsPage(){const auth=useAuth();const pwa=usePwaInstallSurface();const [confirm,setConfirm]=useState(false);const [signOutError,setSignOutError]=useState('');const [signingOut,setSigningOut]=useState(false);const dialogRef=useRef<HTMLDivElement>(null);const closeConfirm=useCallback(()=>setConfirm(false),[]);useDialogFocus(confirm,dialogRef,closeConfirm);
 const handleSignOut=async()=>{if(signingOut)return;setSigningOut(true);setSignOutError('');try{await auth.signOut()}catch{setSignOutError('Не удалось выйти. Проверьте интернет и повторите.')}finally{setSigningOut(false)}};
 const clearLocal=()=>{draftKeys.forEach(key=>localStorage.removeItem(key));for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith(onboardingPrefix))localStorage.removeItem(key)}setConfirm(false)};
 const replay=()=>{localStorage.removeItem(`${onboardingPrefix}${auth.user?.id??'demo'}`);window.dispatchEvent(new CustomEvent('uzor:replay-onboarding'))};
 return <ProductShell><div className="settings-page"><p className="eyebrow">Управление приложением</p><h1>Настройки</h1><div className="settings-grid">
  <section className="settings-section"><h2>Аккаунт</h2><dl className="settings-meta"><dt>Почта</dt><dd>{auth.user?.email??'Демо-профиль'}</dd><dt>Город</dt><dd>Пермь</dd><dt>Доступ</dt><dd>{auth.accessState==='ready' ? `Открытое городское пространство · ${auth.membership?.role==='curator'?'куратор':'участник'}` : auth.accessState==='loading' ? 'Подключение проверяется' : auth.accessState==='unavailable' ? 'Открытое пространство недоступно' : auth.accessState==='error' ? 'Ошибка подключения' : 'Не подключено'}</dd></dl>{auth.authenticationState==='legacy-anonymous'&&<p>Это прежняя гостевая сессия. Авторство не переносится автоматически.</p>}<button className="secondary-action" disabled={signingOut} onClick={()=>void handleSignOut()}>{signingOut?'Выходим…':'Выйти'}</button>{signOutError&&<p role="alert" className="error">{signOutError}</p>}</section>
  <section className="settings-section"><h2>Как пользоваться УЗОРом</h2><ProductGuide compact/><div className="settings-actions"><button className="secondary-action" onClick={replay}>Повторить знакомство</button><Link to="/map">Карта</Link><Link to="/contribute">Добавить Дельту</Link><Link to="/pulse">Пульс недели</Link></div></section>
  <section className="settings-section"><h2>Как читать данные</h2><p><strong>Наблюдение</strong> сообщает о замеченном изменении. Подтверждение и неподтверждение — независимые отклики жителей. Новая Дельта проходит проверку и может стать подтверждённой; разные оценки создают развилку, а не «проигравшее» мнение. Неактуальные Дельты архивируются. Неопределённость сохраняется: мнение группы не является официальным фактом.</p></section>
  <section className="settings-section"><h2>Приватность</h2><p>Точные координаты не публикуются: публичное место округляется. Почта автора и идентификатор пользователя не показываются. Дельты — коллективные сигналы, а не официальные жалобы или статистика.</p></section>
  <section className="settings-section"><h2>Приложение</h2><p>Версия {__APP_VERSION__} · сборка {__BUILD_ID__}</p><div className="settings-actions"><button className="secondary-action" onClick={pwa.canInstall?pwa.install:pwa.openInstructions}>{pwa.canInstall?'Установить приложение':'Как установить приложение'}</button><Link to="/about">Открыть публичный гид</Link></div></section>
  <section className="settings-section"><h2>Локальные данные</h2><p>Удаляются только черновики и отметка о прохождении знакомства на этом устройстве. Данные сервера останутся.</p><button className="danger-action" onClick={()=>setConfirm(true)}>Очистить локальные данные</button></section>
 </div>{confirm&&<div className="confirm-dialog"><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="clear-title"><h2 id="clear-title">Очистить локальные данные?</h2><p>Дельты и другие серверные записи не удалятся.</p><div className="confirm-dialog__actions"><button className="secondary-action" onClick={closeConfirm}>Отмена</button><button className="danger-action" onClick={clearLocal}>Очистить</button></div></div></div>}</div></ProductShell>}
