import { useCallback, useEffect, useRef, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import { useDialogFocus } from './useDialogFocus';
const screens=[['Добро пожаловать в УЗОР','Здесь жители замечают изменения города вместе.'],['Наблюдайте','Дельта описывает уже замеченное изменение, а не слух или ожидание.'],['Проверяйте независимо','Подтверждение и неподтверждение помогают увидеть общий сигнал и развилки.'],['Читайте Пульс','Недельный итог показывает изменения, а не рейтинг людей.'],['Берегите контекст','УЗОР не заменяет официальные факты, статистику и обращения.']];
export function Onboarding(){const auth=useAuth();const [step,setStep]=useState(0);const [open,setOpen]=useState(false);const dialogRef=useRef<HTMLElement>(null);const key=`uzor.onboarding.${auth.user?.id??'demo'}`;
 useEffect(()=>{if(auth.authenticationState==='authenticated'&&auth.user&&localStorage.getItem(key)!=='done')void Promise.resolve().then(()=>setOpen(true))},[auth.authenticationState,auth.user,key]);
 useEffect(()=>{const replay=()=>{setStep(0);setOpen(true)};window.addEventListener('uzor:replay-onboarding',replay);return()=>window.removeEventListener('uzor:replay-onboarding',replay)},[]);
 const skip=useCallback(()=>setOpen(false),[]);useDialogFocus(open,dialogRef,skip);const finish=()=>{localStorage.setItem(key,'done');setOpen(false)};
 if(!open)return null;return <div className="onboarding" role="presentation"><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><p>{step+1} / {screens.length}</p><h2 id="onboarding-title">{screens[step][0]}</h2><p>{screens[step][1]}</p><div className="onboarding-progress" aria-hidden="true">{screens.map((_,index)=><i className={index<=step?'active':''} key={index}/>)}</div><div className="onboarding-actions"><button onClick={skip} aria-label="Пропустить знакомство без отметки о завершении">Пропустить</button>{step<screens.length-1?<button className="primary" onClick={()=>setStep(value=>value+1)}>Дальше</button>:<button className="primary" onClick={finish}>Завершить знакомство</button>}</div></section></div>}
