import { getSupabaseClient } from '../../../lib/supabase/client';
import { isValidIsoTimestamp, validateForecastEvent, validateForecastRecord, validateProbability, validateVersion } from '../validation';
import type { ForecastEvent, UserForecast } from '../types';
import type { ForecastApiErrorCode, ForecastLockReason, ForecastWorkspace, SubmitForecastInput, SubmitForecastResult } from './forecastApiTypes';

export class ForecastApiError extends Error { constructor(public code: ForecastApiErrorCode) { super(code); this.name='ForecastApiError'; } }
const codes: ForecastApiErrorCode[]=['not_authenticated','forecast_event_not_found','forecast_event_not_open','forecast_not_started','forecast_deadline_passed','forecast_option_not_found','invalid_probability','invalid_reasoning','unsupported_forecast_version'];
const apiError=(error:unknown)=>{const message=error&&typeof error==='object'&&'message'in error?String((error as {message:unknown}).message):'';return new ForecastApiError(codes.find(code=>message.includes(code))??'unknown');};
const iso=(value:unknown)=>{if(typeof value!=='string'||!Number.isFinite(Date.parse(value)))throw new ForecastApiError('invalid_response');return new Date(value).toISOString();};
const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new ForecastApiError('invalid_response');return value as Record<string,unknown>;};
const string=(value:unknown)=>{if(typeof value!=='string')throw new ForecastApiError('invalid_response');return value;};
const nullable=(value:unknown)=>value==null?undefined:string(value);
function mapForecast(raw:unknown):UserForecast { const row=object(raw); return {id:string(row.id),eventId:string(row.event_id),selectedOptionId:string(row.selected_option_id),probability:Number(row.probability),reasoning:nullable(row.reasoning),version:string(row.domain_version) as UserForecast['version'],createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}; }
const lockReasons:Exclude<ForecastLockReason,null>[]=['not_authenticated','before_open','deadline_passed','event_not_open','event_not_found'];
function mapLockReason(value:unknown):ForecastLockReason { if(value===null)return null; if(typeof value==='string'&&lockReasons.includes(value as Exclude<ForecastLockReason,null>))return value as Exclude<ForecastLockReason,null>; throw new ForecastApiError('invalid_response'); }
function mapEvent(raw:unknown,optionsRaw:unknown):ForecastEvent { const row=object(raw); if(!Array.isArray(optionsRaw))throw new ForecastApiError('invalid_response'); const event:ForecastEvent={id:string(row.id),title:string(row.title),shortDescription:string(row.short_description),category:string(row.category),cityId:nullable(row.city_id),geographicScope:nullable(row.geographic_scope),options:optionsRaw.map(value=>{const option=object(value);return{id:string(option.id),label:string(option.label),description:nullable(option.description)}}),opensAt:iso(row.opens_at),closesAt:iso(row.closes_at),status:string(row.status) as ForecastEvent['status'],resolutionSource:string(row.resolution_source) as ForecastEvent['resolutionSource'],createdAt:iso(row.created_at),version:string(row.domain_version) as ForecastEvent['version']}; if(row.resolves_at)event.resolvesAt=iso(row.resolves_at); else event.resolutionWindow={startsAt:iso(row.resolution_window_starts_at),endsAt:iso(row.resolution_window_ends_at)}; if(!validateForecastEvent(event).valid)throw new ForecastApiError('invalid_response'); return event; }
export async function getForecastWorkspace(eventId:string):Promise<ForecastWorkspace>{const {data,error}=await getSupabaseClient().rpc('get_forecast_workspace',{input_event_id:eventId});if(error)throw apiError(error);const row=object(data);const event=row.event===null?null:mapEvent(row.event,row.options);const forecast=row.forecast===null?null:mapForecast(row.forecast);if(event&&forecast&&!validateForecastRecord(event,forecast).valid)throw new ForecastApiError('invalid_response');return{event,forecast,serverTimestamp:iso(row.server_timestamp),authenticationRequired:Boolean(row.authentication_required),submissionPermitted:Boolean(row.submission_permitted),locked:Boolean(row.locked),lockReason:mapLockReason(row.lock_reason??null)};}
export async function submitForecast(input:SubmitForecastInput):Promise<SubmitForecastResult>{const {data,error}=await getSupabaseClient().rpc('submit_forecast',{input_event_id:input.eventId,input_option_id:input.optionId,input_probability:input.probability,input_reasoning:input.reasoning??null,input_domain_version:input.version});if(error)throw apiError(error);const row=object(data);const forecast=mapForecast(row.forecast);if(!validateVersion(forecast).valid||forecast.eventId!==input.eventId||forecast.selectedOptionId!==input.optionId||!validateProbability(forecast.probability).valid||!isValidIsoTimestamp(forecast.createdAt)||!isValidIsoTimestamp(forecast.updatedAt))throw new ForecastApiError('invalid_response');return{forecast,serverTimestamp:iso(row.server_timestamp),eventDeadline:iso(row.event_deadline),created:Boolean(row.created),locked:Boolean(row.locked)};}
export const forecastErrorMessage=(error:unknown)=>{const code=error instanceof ForecastApiError?error.code:'unknown';const messages:Record<ForecastApiErrorCode,string>={not_authenticated:'Чтобы сохранить прогноз, войдите в круг.',forecast_event_not_found:'Событие не найдено.',forecast_event_not_open:'Приём прогнозов для события закрыт.',forecast_not_started:'Приём прогнозов ещё не начался.',forecast_deadline_passed:'Срок приёма закончился. Прогноз не был изменён.',forecast_option_not_found:'Выбранный исход недоступен.',invalid_probability:'Укажите вероятность от 0% до 100%.',invalid_reasoning:'Обоснование должно быть не длиннее 280 символов.',unsupported_forecast_version:'Версия прогноза не поддерживается.',invalid_response:'Не удалось загрузить корректные данные прогноза.',unknown:'Не удалось сохранить прогноз. Попробуйте ещё раз.'};return messages[code];};
