import { beforeEach, describe, expect, it, vi } from 'vitest';
const rpc=vi.fn();
vi.mock('../../../lib/supabase/client',()=>({getSupabaseClient:()=>({rpc})}));
import { ForecastApiError, getForecastResolutionWorkspace, getForecastWorkspace, resolveForecastEvent, submitForecast } from './forecastApi';

const event={id:'e',title:'Event',short_description:'Condition',category:'prices',city_id:null,geographic_scope:null,opens_at:'2026-07-25T00:00:00+00:00',closes_at:'2026-12-14T12:00:00+00:00',resolves_at:'2026-12-15T12:00:00+00:00',resolution_window_starts_at:null,resolution_window_ends_at:null,status:'open',resolution_source:'retailer-publication',domain_version:'forecast-domain-v1',created_at:'2026-07-25T00:00:00+00:00'};
const forecast={id:'f',event_id:'e',selected_option_id:'above',probability:0.5,reasoning:null,domain_version:'forecast-domain-v1',created_at:'2026-07-25T01:00:00Z',updated_at:'2026-07-25T01:00:00Z'};
beforeEach(()=>rpc.mockReset());
describe('forecast API',()=>{
 it('maps workspace and its existing forecast',async()=>{rpc.mockResolvedValue({data:{event,options:[{id:'above',label:'Above',description:null},{id:'no',label:'No',description:null}],forecast,server_timestamp:'2026-07-25T01:00:00Z',authentication_required:false,submission_permitted:true,locked:false,lock_reason:null},error:null});const value=await getForecastWorkspace('e');expect(rpc).toHaveBeenCalledWith('get_forecast_workspace',{input_event_id:'e'});expect(value.forecast).toMatchObject({id:'f',eventId:'e',probability:0.5});});
 it('maps a verified public outcome',async()=>{rpc.mockResolvedValue({data:{event:{...event,status:'resolved'},options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:null,outcome:{id:'o',event_id:'e',resolved_option_id:'above',resolved_at:'2026-08-01T01:00:00Z',source_reference:'https://example.test',source_type:'retailer-publication',resolution_note:'Checked',resolver_status:'verified',domain_version:'forecast-domain-v1'},server_timestamp:'2026-08-01T01:00:00Z',authentication_required:false,submission_permitted:false,locked:true,lock_reason:'event_not_open'},error:null});await expect(getForecastWorkspace('e')).resolves.toMatchObject({outcome:{id:'o',resolvedOptionId:'above',resolverStatus:'verified'}});});
 it.each([{resolved_option_id:'foreign'},{source_type:'unsupported'},{resolver_status:'pending'},{domain_version:'v2'},{resolved_at:'not-a-date'}])('rejects malformed outcome %#',async(change)=>{rpc.mockResolvedValue({data:{event:{...event,status:'resolved'},options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:null,outcome:{id:'o',event_id:'e',resolved_option_id:'above',resolved_at:'2026-08-01T01:00:00Z',source_reference:'reference',source_type:'retailer-publication',resolution_note:'Checked',resolver_status:'verified',domain_version:'forecast-domain-v1',...change},server_timestamp:'2026-08-01T01:00:00Z',authentication_required:false,submission_permitted:false,locked:true,lock_reason:'event_not_open'},error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
 it('sends only the controlled submit arguments',async()=>{rpc.mockResolvedValue({data:{forecast,server_timestamp:'2026-07-25T01:00:00Z',event_deadline:'2026-12-14T12:00:00Z',created:true,locked:false},error:null});await submitForecast({eventId:'e',optionId:'above',probability:.5,reasoning:'why',version:'forecast-domain-v1'});expect(rpc).toHaveBeenCalledWith('submit_forecast',{input_event_id:'e',input_option_id:'above',input_probability:.5,input_reasoning:'why',input_domain_version:'forecast-domain-v1'});expect(JSON.stringify(rpc.mock.calls)).not.toMatch(/user_id|created_at|updated_at/);});
 it('maps stable SQL errors',async()=>{rpc.mockResolvedValue({data:null,error:{message:'forecast_deadline_passed'}});await expect(submitForecast({eventId:'e',optionId:'above',probability:.5,version:'forecast-domain-v1'})).rejects.toMatchObject({code:'forecast_deadline_passed'});expect(ForecastApiError).toBeDefined();});
 it('rejects a foreign option in mapped forecast',async()=>{rpc.mockResolvedValue({data:{event,options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:{...forecast,selected_option_id:'foreign'},server_timestamp:'2026-07-25T01:00:00Z',authentication_required:false,submission_permitted:true,locked:false},error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
 it('rejects an unsupported mapped version',async()=>{rpc.mockResolvedValue({data:{event:{...event,domain_version:'v2'},options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:null,server_timestamp:'2026-07-25T01:00:00Z',authentication_required:true,submission_permitted:false,locked:true},error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
 it.each(['unexpected',42,{}])('rejects unknown workspace lock reason %j',async(lockReason)=>{rpc.mockResolvedValue({data:{event,options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:null,server_timestamp:'2026-07-25T01:00:00Z',authentication_required:false,submission_permitted:false,locked:true,lock_reason:lockReason},error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
 it.each([
  ['foreign event',{event_id:'other'}],['unsupported version',{domain_version:'v2'}],['invalid probability',{probability:2}],['malformed created timestamp',{created_at:'yesterday'}],['malformed updated timestamp',{updated_at:'tomorrow'}],
 ])('rejects malformed submit response: %s',async(_label,change)=>{rpc.mockResolvedValue({data:{forecast:{...forecast,...change},server_timestamp:'2026-07-25T01:00:00Z',event_deadline:'2026-12-14T12:00:00Z',created:false,locked:false},error:null});await expect(submitForecast({eventId:'e',optionId:'above',probability:.5,version:'forecast-domain-v1'})).rejects.toMatchObject({code:'invalid_response'});});
 const options=[{id:'above',label:'Above'},{id:'no',label:'No'}];
 const resolvedEvent={...event,status:'resolved',updated_at:'2026-12-15T12:00:00Z'};
 const outcome={id:'o',event_id:'e',resolved_option_id:'above',resolved_at:'2026-12-15T12:00:00Z',source_reference:'https://example.test/result',source_type:'retailer-publication',resolution_note:'Checked by a human',resolver_status:'verified',domain_version:'forecast-domain-v1'};
 it.each([
  ['outcome without event',{event:null,options:[],outcome}],
  ['unknown reason',{event,options,outcome:null,authorized:true,can_resolve:false,block_reason:'surprise'}],
  ['resolve while unauthorized',{event,options,outcome:null,authorized:false,can_resolve:true,block_reason:null}],
  ['resolve with reason',{event,options,outcome:null,authorized:true,can_resolve:true,block_reason:'forecast_still_open'}],
  ['resolve without event',{event:null,options:[],outcome:null,authorized:true,can_resolve:true,block_reason:null}],
  ['resolve with outcome',{event:resolvedEvent,options,outcome,authorized:true,can_resolve:true,block_reason:null}],
  ['blocked without reason',{event,options,outcome:null,authorized:true,can_resolve:false,block_reason:null}],
 ])('rejects inconsistent resolution workspace: %s',async(_label,change)=>{rpc.mockResolvedValue({data:{server_timestamp:'2026-12-15T12:00:00Z',authorized:false,can_resolve:false,block_reason:'resolver_not_authorized',...change},error:null});await expect(getForecastResolutionWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
 it('maps a consistent resolver workspace',async()=>{rpc.mockResolvedValue({data:{event,options,outcome:null,server_timestamp:'2026-12-15T12:00:00Z',authorized:true,can_resolve:true,block_reason:null},error:null});await expect(getForecastResolutionWorkspace('e')).resolves.toMatchObject({authorized:true,canResolve:true,blockReason:null,event:{id:'e'}});});
 it('maps resolve response from its full authoritative event and options',async()=>{rpc.mockResolvedValue({data:{event:resolvedEvent,options,outcome,server_timestamp:'2026-12-15T12:00:00Z'},error:null});const value=await resolveForecastEvent({eventId:'e',resolvedOptionId:'above',sourceReference:'client',resolutionNote:'client',version:'forecast-domain-v1'});expect(value.event).toMatchObject({id:'e',title:'Event',status:'resolved',options});expect(value.eventUpdatedAt).toBe('2026-12-15T12:00:00.000Z');expect(value.outcome.sourceReference).toBe('https://example.test/result');expect(JSON.stringify(rpc.mock.calls)).not.toMatch(/user_id|resolved_at|client_timestamp/);});
 it.each([{event:{...resolvedEvent,id:'other'}},{outcome:{...outcome,resolved_option_id:'no'}},{outcome:{...outcome,source_reference:'x'.repeat(2001)}},{event:{...resolvedEvent,updated_at:'invalid'}}])('rejects malformed resolve response %#',async(change)=>{rpc.mockResolvedValue({data:{event:resolvedEvent,options,outcome,server_timestamp:'2026-12-15T12:00:00Z',...change},error:null});await expect(resolveForecastEvent({eventId:'e',resolvedOptionId:'above',sourceReference:'client',resolutionNote:'client',version:'forecast-domain-v1'})).rejects.toMatchObject({code:'invalid_response'});});
});

describe('authoritative score mapping',()=>{
 const options=[{id:'above',label:'Above'},{id:'no',label:'No'}];
 const resolvedEvent={...event,status:'resolved'};
 const personal={...forecast,probability:.8};
 const verified={id:'11111111-1111-1111-1111-111111111111',event_id:'e',resolved_option_id:'above',resolved_at:'2026-08-01T01:00:00Z',source_reference:'reference',source_type:'retailer-publication',resolution_note:'Checked',resolver_status:'verified',domain_version:'forecast-domain-v1'};
 const validScore={id:`f:${verified.id}:brier-binary-v1`,event_id:'e',forecast_id:'f',outcome_id:verified.id,forecast_probability:.8,observed_binary_outcome:1,brier_score:.04,scored_at:'2026-08-01T01:00:00Z',scoring_version:'brier-binary-v1',domain_version:'forecast-domain-v1'};
 const response=(change:Record<string,unknown>={})=>({event:resolvedEvent,options,forecast:personal,outcome:verified,score:validScore,server_timestamp:'2026-08-01T01:00:01Z',authentication_required:false,submission_permitted:false,locked:true,lock_reason:'event_not_open',...change});
 it('maps a valid private score',async()=>{rpc.mockResolvedValue({data:response(),error:null});await expect(getForecastWorkspace('e')).resolves.toMatchObject({score:{brierScore:.04,observedBinaryOutcome:1,scoringVersion:'brier-binary-v1'}});});
 it.each([{p:1,o:1,b:0},{p:1,o:0,b:1},{p:0,o:0,b:0}])('accepts boundary score %#',async({p,o,b})=>{const selected=o?'above':'no';rpc.mockResolvedValue({data:response({forecast:{...personal,probability:p,selected_option_id:selected},score:{...validScore,forecast_probability:p,observed_binary_outcome:o,brier_score:b}}),error:null});await expect(getForecastWorkspace('e')).resolves.toMatchObject({score:{brierScore:b}});});
 it.each([
  ['without forecast',{forecast:null}],['without outcome',{outcome:null}],['on unresolved event',{event}],['wrong event',{score:{...validScore,event_id:'x'}}],['wrong forecast',{score:{...validScore,forecast_id:'x'}}],['wrong outcome',{score:{...validScore,outcome_id:'22222222-2222-2222-2222-222222222222'}}],['wrong snapshot',{score:{...validScore,forecast_probability:.7}}],['wrong observed',{score:{...validScore,observed_binary_outcome:0,brier_score:.64}}],['wrong formula',{score:{...validScore,brier_score:.05}}],['NaN',{score:{...validScore,brier_score:'NaN'}}],['infinity',{score:{...validScore,brier_score:'Infinity'}}],['outside range',{score:{...validScore,brier_score:1.1}}],['wrong id',{score:{...validScore,id:'wrong'}}],['wrong scoring version',{score:{...validScore,scoring_version:'v2'}}],['wrong domain version',{score:{...validScore,domain_version:'v2'}}],['invalid time',{score:{...validScore,scored_at:'invalid'}}],['before outcome',{score:{...validScore,scored_at:'2026-07-31T00:00:00Z'}}],['missing score',{score:null}],
 ])('rejects %s',async(_label,change)=>{rpc.mockResolvedValue({data:response(change as Record<string,unknown>),error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
});
