import { getSupabaseClient } from '../../../lib/supabase/client';
import { isValidIsoTimestamp, validateForecastEvent, validateForecastRecord, validateOutcome, validateProbability, validateVersion } from '../validation';
import { calculateBinaryBrierScore } from '../scoring';
import { FORECAST_DOMAIN_VERSION, type ForecastEvent, type ForecastOutcome, type ForecastScore, type UserForecast } from '../types';
import type { ForecastApiErrorCode, ForecastLockReason, ForecastResolutionBlockReason, ForecastResolutionWorkspace, ForecastWorkspace, ResolveForecastInput, ResolveForecastResult, SubmitForecastInput, SubmitForecastResult } from './forecastApiTypes';

export class ForecastApiError extends Error { constructor(public code: ForecastApiErrorCode) { super(code); this.name='ForecastApiError'; } }
const codes: ForecastApiErrorCode[]=['not_authenticated','forecast_resolver_not_authorized','forecast_event_not_found','forecast_event_cancelled','forecast_event_already_resolved','forecast_outcome_already_exists','forecast_event_still_open','forecast_resolution_time_not_reached','forecast_outcome_option_not_found','invalid_source_reference','invalid_resolution_note','forecast_outcome_write_failed','forecast_score_write_failed','forecast_event_not_open','forecast_not_started','forecast_deadline_passed','forecast_option_not_found','invalid_probability','invalid_reasoning','unsupported_forecast_version'];
const apiError=(error:unknown)=>{const message=error&&typeof error==='object'&&'message'in error?String((error as {message:unknown}).message):'';return new ForecastApiError(codes.find(code=>message.includes(code))??'unknown');};
const iso=(value:unknown)=>{if(typeof value!=='string'||!Number.isFinite(Date.parse(value)))throw new ForecastApiError('invalid_response');return new Date(value).toISOString();};
const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new ForecastApiError('invalid_response');return value as Record<string,unknown>;};
const string=(value:unknown)=>{if(typeof value!=='string')throw new ForecastApiError('invalid_response');return value;};
const boolean=(value:unknown)=>{if(typeof value!=='boolean')throw new ForecastApiError('invalid_response');return value;};
const nullable=(value:unknown)=>value==null?undefined:string(value);
function mapForecast(raw:unknown):UserForecast { const row=object(raw); return {id:string(row.id),eventId:string(row.event_id),selectedOptionId:string(row.selected_option_id),probability:Number(row.probability),reasoning:nullable(row.reasoning),version:string(row.domain_version) as UserForecast['version'],createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}; }
function mapScore(raw:unknown,event:ForecastEvent,forecast:UserForecast,outcome:ForecastOutcome):ForecastScore {const row=object(raw);const observed=Number(row.observed_binary_outcome),brier=Number(row.brier_score),probability=Number(row.forecast_probability),scoredAt=iso(row.scored_at);if((observed!==0&&observed!==1)||!Number.isFinite(brier)||brier<0||brier>1||!Number.isFinite(probability)||probability!==forecast.probability||string(row.event_id)!==event.id||string(row.forecast_id)!==forecast.id||string(row.outcome_id)!==outcome.id||string(row.scoring_version)!=='brier-binary-v1'||string(row.domain_version)!==FORECAST_DOMAIN_VERSION||string(row.id)!==`${forecast.id}:${outcome.id}:brier-binary-v1`||observed!==(forecast.selectedOptionId===outcome.resolvedOptionId?1:0)||Math.abs(brier-calculateBinaryBrierScore(probability,observed as 0|1))>1e-12||Date.parse(scoredAt)<Date.parse(outcome.resolvedAt))throw new ForecastApiError('invalid_response');return{id:string(row.id),eventId:event.id,forecastId:forecast.id,outcomeId:outcome.id,forecastProbability:probability,observedBinaryOutcome:observed as 0|1,brierScore:brier,scoredAt,scoringVersion:'brier-binary-v1',version:FORECAST_DOMAIN_VERSION};}
const resolutionSources:ForecastOutcome['sourceType'][]=['official-publication','municipal-service','retailer-publication','event-organizer','other-reference'];
function mapOutcome(raw:unknown,event:ForecastEvent):ForecastOutcome { const row=object(raw); const outcome:ForecastOutcome={id:string(row.id),eventId:string(row.event_id),resolvedOptionId:string(row.resolved_option_id),resolvedAt:iso(row.resolved_at),sourceReference:string(row.source_reference),sourceType:string(row.source_type) as ForecastOutcome['sourceType'],resolutionNote:string(row.resolution_note),resolverStatus:string(row.resolver_status) as ForecastOutcome['resolverStatus'],version:string(row.domain_version) as ForecastOutcome['version']}; if(event.status!=='resolved'||outcome.resolverStatus!=='verified'||!resolutionSources.includes(outcome.sourceType)||outcome.sourceType!==event.resolutionSource||!outcome.sourceReference.trim()||outcome.sourceReference.length>2000||!outcome.resolutionNote.trim()||outcome.resolutionNote.length>2000||!validateOutcome(event,outcome).valid)throw new ForecastApiError('invalid_response'); return outcome; }
const lockReasons:Exclude<ForecastLockReason,null>[]=['not_authenticated','before_open','deadline_passed','event_not_open','event_not_found'];
function mapLockReason(value:unknown):ForecastLockReason { if(value===null)return null; if(typeof value==='string'&&lockReasons.includes(value as Exclude<ForecastLockReason,null>))return value as Exclude<ForecastLockReason,null>; throw new ForecastApiError('invalid_response'); }
function mapEvent(raw:unknown,optionsRaw:unknown):ForecastEvent { const row=object(raw); if(!Array.isArray(optionsRaw))throw new ForecastApiError('invalid_response'); const event:ForecastEvent={id:string(row.id),title:string(row.title),shortDescription:string(row.short_description),category:string(row.category),cityId:nullable(row.city_id),geographicScope:nullable(row.geographic_scope),options:optionsRaw.map(value=>{const option=object(value);return{id:string(option.id),label:string(option.label),description:nullable(option.description)}}),opensAt:iso(row.opens_at),closesAt:iso(row.closes_at),status:string(row.status) as ForecastEvent['status'],resolutionSource:string(row.resolution_source) as ForecastEvent['resolutionSource'],createdAt:iso(row.created_at),version:string(row.domain_version) as ForecastEvent['version']}; if(row.resolves_at)event.resolvesAt=iso(row.resolves_at); else event.resolutionWindow={startsAt:iso(row.resolution_window_starts_at),endsAt:iso(row.resolution_window_ends_at)}; if(!validateForecastEvent(event).valid)throw new ForecastApiError('invalid_response'); return event; }
export async function getForecastWorkspace(eventId:string):Promise<ForecastWorkspace>{const {data,error}=await getSupabaseClient().rpc('get_forecast_workspace',{input_event_id:eventId});if(error)throw apiError(error);const row=object(data);const event=row.event==null?null:mapEvent(row.event,row.options);const forecast=row.forecast==null?null:mapForecast(row.forecast);const outcome=row.outcome==null?null:(event?mapOutcome(row.outcome,event):(()=>{throw new ForecastApiError('invalid_response');})());if(event&&forecast&&!validateForecastRecord(event,forecast).valid)throw new ForecastApiError('invalid_response');if(row.score!=null&&(!event||!forecast||!outcome||event.status!=='resolved'))throw new ForecastApiError('invalid_response');const score=row.score==null?null:mapScore(row.score,event!,forecast!,outcome!);if(event?.status==='resolved'&&forecast&&outcome&&!score)throw new ForecastApiError('invalid_response');return{event,forecast,outcome,score,serverTimestamp:iso(row.server_timestamp),authenticationRequired:boolean(row.authentication_required),submissionPermitted:boolean(row.submission_permitted),locked:boolean(row.locked),lockReason:mapLockReason(row.lock_reason??null)};}
export async function submitForecast(input:SubmitForecastInput):Promise<SubmitForecastResult>{const {data,error}=await getSupabaseClient().rpc('submit_forecast',{input_event_id:input.eventId,input_option_id:input.optionId,input_probability:input.probability,input_reasoning:input.reasoning??null,input_domain_version:input.version});if(error)throw apiError(error);const row=object(data);const forecast=mapForecast(row.forecast);if(!validateVersion(forecast).valid||forecast.eventId!==input.eventId||forecast.selectedOptionId!==input.optionId||!validateProbability(forecast.probability).valid||!isValidIsoTimestamp(forecast.createdAt)||!isValidIsoTimestamp(forecast.updatedAt))throw new ForecastApiError('invalid_response');return{forecast,serverTimestamp:iso(row.server_timestamp),eventDeadline:iso(row.event_deadline),created:Boolean(row.created),locked:Boolean(row.locked)};}
const resolutionReasons:Exclude<ForecastResolutionBlockReason,null>[]=['not_authenticated','resolver_not_authorized','event_not_found','event_cancelled','outcome_already_resolved','forecast_still_open','resolution_time_not_reached'];
function mapResolutionReason(value:unknown):ForecastResolutionBlockReason {if(value===null)return null;if(typeof value==='string'&&resolutionReasons.includes(value as Exclude<ForecastResolutionBlockReason,null>))return value as Exclude<ForecastResolutionBlockReason,null>;throw new ForecastApiError('invalid_response');}
export async function getForecastResolutionWorkspace(eventId:string):Promise<ForecastResolutionWorkspace>{
 const {data,error}=await getSupabaseClient().rpc('get_forecast_resolution_workspace',{input_event_id:eventId});if(error)throw apiError(error);
 const row=object(data),event=row.event==null?null:mapEvent(row.event,row.options);
 if(row.outcome!=null&&!event)throw new ForecastApiError('invalid_response');
 const outcome=row.outcome==null?null:mapOutcome(row.outcome,event!);
 const authorized=boolean(row.authorized),canResolve=boolean(row.can_resolve),blockReason=mapResolutionReason(row.block_reason??null);
 if(canResolve&&(!authorized||blockReason!==null||event===null||outcome!==null))throw new ForecastApiError('invalid_response');
 if(!canResolve&&blockReason===null)throw new ForecastApiError('invalid_response');
 return{event,outcome,serverTimestamp:iso(row.server_timestamp),authorized,canResolve,blockReason};
}
export async function resolveForecastEvent(input:ResolveForecastInput):Promise<ResolveForecastResult>{
 const {data,error}=await getSupabaseClient().rpc('resolve_forecast_event',{input_event_id:input.eventId,input_resolved_option_id:input.resolvedOptionId,input_source_reference:input.sourceReference,input_resolution_note:input.resolutionNote,input_domain_version:input.version});if(error)throw apiError(error);
 const row=object(data),eventRow=object(row.event),event=mapEvent(eventRow,row.options),eventUpdatedAt=iso(eventRow.updated_at);
 if(event.id!==input.eventId||event.status!=='resolved')throw new ForecastApiError('invalid_response');
 const outcome=mapOutcome(row.outcome,event);
 if(outcome.resolvedOptionId!==input.resolvedOptionId||outcome.version!=='forecast-domain-v1')throw new ForecastApiError('invalid_response');
 return{event,eventUpdatedAt,outcome,serverTimestamp:iso(row.server_timestamp)};
}
export const forecastErrorMessage=(error:unknown)=>{const code=error instanceof ForecastApiError?error.code:'unknown';const messages:Partial<Record<ForecastApiErrorCode,string>>={not_authenticated:'Чтобы сохранить прогноз, войдите в круг.',forecast_event_not_found:'Событие не найдено.',forecast_event_not_open:'Приём прогнозов для события закрыт.',forecast_not_started:'Приём прогнозов ещё не начался.',forecast_deadline_passed:'Срок приёма закончился. Прогноз не был изменён.',forecast_option_not_found:'Выбранный исход недоступен.',invalid_probability:'Укажите вероятность от 0% до 100%.',invalid_reasoning:'Обоснование должно быть не длиннее 280 символов.',unsupported_forecast_version:'Версия прогноза не поддерживается.',invalid_response:'Не удалось загрузить корректные данные прогноза.',unknown:'Не удалось сохранить прогноз. Попробуйте ещё раз.'};return messages[code]??messages.unknown!;};
export const resolutionErrorMessage=(error:unknown)=>{const code=error instanceof ForecastApiError?error.code:'unknown';const messages:Partial<Record<ForecastApiErrorCode,string>>={not_authenticated:'Необходимо войти в аккаунт.',forecast_resolver_not_authorized:'Доступ к фиксации исходов не предоставлен.',forecast_event_not_found:'Событие не найдено.',forecast_event_cancelled:'Событие отменено.',forecast_event_already_resolved:'Исход уже зафиксирован.',forecast_outcome_already_exists:'Исход уже зафиксирован.',forecast_event_still_open:'Приём прогнозов ещё открыт.',forecast_resolution_time_not_reached:'Время проверки ещё не наступило.',forecast_outcome_option_not_found:'Выбранный вариант недоступен.',invalid_source_reference:'Укажите корректную ссылку или описание источника.',invalid_resolution_note:'Добавьте примечание о проверке.',unsupported_forecast_version:'Версия события не поддерживается.',forecast_outcome_write_failed:'Не удалось зафиксировать исход. Попробуйте ещё раз.',invalid_response:'Сервер вернул некорректные данные.'};return messages[code]??'Не удалось зафиксировать исход. Попробуйте ещё раз.';};
