import { beforeEach, describe, expect, it, vi } from 'vitest';
const rpc=vi.fn();
vi.mock('../../../lib/supabase/client',()=>({getSupabaseClient:()=>({rpc})}));
import { ForecastApiError, getForecastWorkspace, submitForecast } from './forecastApi';

const event={id:'e',title:'Event',short_description:'Condition',category:'prices',city_id:null,geographic_scope:null,opens_at:'2026-07-25T00:00:00+00:00',closes_at:'2026-12-14T12:00:00+00:00',resolves_at:'2026-12-15T12:00:00+00:00',resolution_window_starts_at:null,resolution_window_ends_at:null,status:'open',resolution_source:'retailer-publication',domain_version:'forecast-domain-v1',created_at:'2026-07-25T00:00:00+00:00'};
const forecast={id:'f',event_id:'e',selected_option_id:'above',probability:0.5,reasoning:null,domain_version:'forecast-domain-v1',created_at:'2026-07-25T01:00:00Z',updated_at:'2026-07-25T01:00:00Z'};
beforeEach(()=>rpc.mockReset());
describe('forecast API',()=>{
 it('maps workspace and its existing forecast',async()=>{rpc.mockResolvedValue({data:{event,options:[{id:'above',label:'Above',description:null},{id:'no',label:'No',description:null}],forecast,server_timestamp:'2026-07-25T01:00:00Z',authentication_required:false,submission_permitted:true,locked:false,lock_reason:null},error:null});const value=await getForecastWorkspace('e');expect(rpc).toHaveBeenCalledWith('get_forecast_workspace',{input_event_id:'e'});expect(value.forecast).toMatchObject({id:'f',eventId:'e',probability:0.5});});
 it('sends only the controlled submit arguments',async()=>{rpc.mockResolvedValue({data:{forecast,server_timestamp:'2026-07-25T01:00:00Z',event_deadline:'2026-12-14T12:00:00Z',created:true,locked:false},error:null});await submitForecast({eventId:'e',optionId:'above',probability:.5,reasoning:'why',version:'forecast-domain-v1'});expect(rpc).toHaveBeenCalledWith('submit_forecast',{input_event_id:'e',input_option_id:'above',input_probability:.5,input_reasoning:'why',input_domain_version:'forecast-domain-v1'});expect(JSON.stringify(rpc.mock.calls)).not.toMatch(/user_id|created_at|updated_at/);});
 it('maps stable SQL errors',async()=>{rpc.mockResolvedValue({data:null,error:{message:'forecast_deadline_passed'}});await expect(submitForecast({eventId:'e',optionId:'above',probability:.5,version:'forecast-domain-v1'})).rejects.toMatchObject({code:'forecast_deadline_passed'});expect(ForecastApiError).toBeDefined();});
 it('rejects a foreign option in mapped forecast',async()=>{rpc.mockResolvedValue({data:{event,options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:{...forecast,selected_option_id:'foreign'},server_timestamp:'2026-07-25T01:00:00Z',authentication_required:false,submission_permitted:true,locked:false},error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
 it('rejects an unsupported mapped version',async()=>{rpc.mockResolvedValue({data:{event:{...event,domain_version:'v2'},options:[{id:'above',label:'Above'},{id:'no',label:'No'}],forecast:null,server_timestamp:'2026-07-25T01:00:00Z',authentication_required:true,submission_permitted:false,locked:true},error:null});await expect(getForecastWorkspace('e')).rejects.toMatchObject({code:'invalid_response'});});
});
