-- Delta MVP foundation: geospatial data model, safe RPC, and RLS.
create schema if not exists extensions;
create extension if not exists postgis with schema extensions;
set search_path = public, extensions, gis;

create table if not exists public.delta_cities (
  id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null,
  center_lat double precision not null check (center_lat between -90 and 90), center_lng double precision not null check (center_lng between -180 and 180),
  default_zoom numeric(4,1) not null default 11.5, outskirts_distance_m integer not null default 8000 check (outskirts_distance_m > 0),
  is_active boolean not null default true, created_at timestamptz not null default now()
);
insert into public.delta_cities(slug,name,center_lat,center_lng,default_zoom,outskirts_distance_m) values('perm','Пермь',58.0105,56.2502,11.5,8000)
on conflict(slug) do update set name=excluded.name, center_lat=excluded.center_lat, center_lng=excluded.center_lng, default_zoom=excluded.default_zoom, outskirts_distance_m=excluded.outskirts_distance_m;

create table if not exists public.delta_categories (
  id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, description text, icon_key text not null,
  sensitivity_weight numeric(4,3) not null check (sensitivity_weight between 0 and 1), sort_order integer not null default 0,
  is_active boolean not null default true, created_at timestamptz not null default now()
);
comment on table public.delta_categories is 'Delta category weights are Rules of the game v1, not objective truth; future curators/admins can tune them.';
insert into public.delta_categories(slug,title,description,icon_key,sensitivity_weight,sort_order) values
('transport','Транспорт и дорога','Изменения времени дороги, ожидания и городской мобильности.','transport',0.700,10),
('services','Доступность услуг','Изменения доступности повседневных городских и бытовых услуг.','services',0.600,20),
('urban-environment','Городская среда','Изменения удобства, состояния и качества городской среды.','urban-environment',0.400,30)
on conflict(slug) do update set title=excluded.title, description=excluded.description, icon_key=excluded.icon_key, sensitivity_weight=excluded.sensitivity_weight, sort_order=excluded.sort_order;

create table if not exists public.deltas (
  id uuid primary key default gen_random_uuid(), circle_id uuid not null references public.circles(id) on delete cascade,
  city_id uuid not null references public.delta_cities(id), category_id uuid not null references public.delta_categories(id), created_by uuid not null,
  direction text not null check (direction in ('positive','negative')), subject text not null check (char_length(trim(subject)) between 2 and 80),
  change_type text not null check (change_type in ('faster','slower','cheaper','more_expensive','more_available','less_available','more','less','appeared','disappeared','improved','worsened','other')),
  statement text not null check (char_length(trim(statement)) between 8 and 180), details text check (details is null or char_length(details) <= 500),
  observed_window text not null check (observed_window in ('today','last_3_days','last_week','last_2_4_weeks')), impact_level text not null check (impact_level in ('noticeable','strong','critical')),
  location geography(Point,4326) not null, public_location geography(Point,4326) not null,
  location_label text not null check (char_length(trim(location_label)) between 2 and 160), location_precision text not null default 'point' check (location_precision in ('point','district','city')),
  status text not null default 'new' check (status in ('new','checking','confirmed','fork','archived')), moderation_state text not null default 'visible' check (moderation_state in ('visible','hidden','merged')),
  confirmation_target smallint not null default 3 check (confirmation_target between 3 and 4), merged_into_id uuid references public.deltas(id), confirmed_at timestamptz, forked_at timestamptz,
  curator_review_due_at timestamptz not null default (now() + interval '20 hours'), expires_at timestamptz not null default (now() + interval '7 days'), last_activity_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists deltas_circle_id_idx on public.deltas(circle_id); create index if not exists deltas_city_id_idx on public.deltas(city_id); create index if not exists deltas_category_id_idx on public.deltas(category_id); create index if not exists deltas_status_idx on public.deltas(status); create index if not exists deltas_moderation_state_idx on public.deltas(moderation_state); create index if not exists deltas_created_at_desc_idx on public.deltas(created_at desc); create index if not exists deltas_last_activity_at_desc_idx on public.deltas(last_activity_at desc); create index if not exists deltas_location_gist_idx on public.deltas using gist(location); create index if not exists deltas_public_location_gist_idx on public.deltas using gist(public_location);

create table if not exists public.delta_reactions (
  id uuid primary key default gen_random_uuid(), delta_id uuid not null references public.deltas(id) on delete cascade, user_id uuid not null,
  reaction text not null check (reaction in ('confirm','disconfirm')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(delta_id,user_id)
);
create index if not exists delta_reactions_delta_id_idx on public.delta_reactions(delta_id); create index if not exists delta_reactions_user_id_idx on public.delta_reactions(user_id); create index if not exists delta_reactions_reaction_idx on public.delta_reactions(reaction);

create or replace function public.calculate_delta_confirmation_target(sensitivity_weight numeric, distance_from_center_m numeric, outskirts_distance_m integer default 8000) returns smallint language sql immutable set search_path = public, extensions, gis as $$ select least(4,greatest(3,3 + case when sensitivity_weight >= 0.850 then 1 else 0 end - case when distance_from_center_m >= outskirts_distance_m then 1 else 0 end))::smallint $$;
comment on function public.calculate_delta_confirmation_target(numeric,numeric,integer) is 'Distance weakly compensates lower participant density; it does not make a claim true and can reduce the raised target by at most one.';
create or replace function public.calculate_delta_priority(sensitivity_weight numeric, impact_level text, created_at timestamptz, distance_from_center_m numeric, outskirts_distance_m integer) returns numeric language sql stable set search_path = public, extensions, gis as $$ select least(1,greatest(0, sensitivity_weight*0.50 + case impact_level when 'critical' then 0.35 when 'strong' then 0.20 else 0 end + case when now()-created_at < interval '24 hours' then 0.10 when now()-created_at <= interval '72 hours' then 0.05 else 0 end + case when distance_from_center_m >= outskirts_distance_m then 0.05 else 0 end))::numeric $$;
create or replace function public.touch_delta_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists deltas_touch_updated_at on public.deltas; create trigger deltas_touch_updated_at before update on public.deltas for each row execute function public.touch_delta_updated_at();
drop trigger if exists delta_reactions_touch_updated_at on public.delta_reactions; create trigger delta_reactions_touch_updated_at before update on public.delta_reactions for each row execute function public.touch_delta_updated_at();

create or replace function public.delta_status_for_counts(confirm_count integer, disconfirm_count integer, target smallint, moderation_state text, expires_at timestamptz) returns text language sql stable set search_path = public as $$ select case when moderation_state in ('hidden','merged') or expires_at <= now() then 'archived' when confirm_count > 0 and disconfirm_count > 0 then 'fork' when confirm_count >= target then 'confirmed' when confirm_count >= 2 then 'checking' else 'new' end $$;
create or replace function public.delta_counts(input_delta_id uuid, out confirm_count integer, out disconfirm_count integer) returns record language sql stable security definer set search_path = public as $$ select count(*) filter(where reaction='confirm')::integer, count(*) filter(where reaction='disconfirm')::integer from public.delta_reactions where delta_id=input_delta_id $$;

-- Safe public payload helper: exposes only public_location and aggregate counts, never created_by, raw location or user_id.
create or replace function public.delta_card_json(d public.deltas, viewer uuid default auth.uid()) returns jsonb language sql stable security definer set search_path = public, extensions, gis as $$
  with counts as (select * from public.delta_counts(d.id)), c as (select * from public.delta_categories where id=d.category_id), city as (select * from public.delta_cities where id=d.city_id), v as (select reaction from public.delta_reactions where delta_id=d.id and user_id=viewer), dist as (select ST_Distance(d.location, ST_SetSRID(ST_MakePoint(city.center_lng, city.center_lat),4326)::geography) m from city)
  select jsonb_build_object('id',d.id,'category',jsonb_build_object('slug',c.slug,'title',c.title,'iconKey',c.icon_key),'direction',d.direction,'subject',d.subject,'changeType',d.change_type,'statement',d.statement,'details',d.details,'observedWindow',d.observed_window,'impactLevel',d.impact_level,'status',d.status,'moderationState',d.moderation_state,'confirmCount',counts.confirm_count,'disconfirmCount',counts.disconfirm_count,'confirmationTarget',d.confirmation_target,'viewerReaction',(select reaction from v),'location',jsonb_build_object('lat',ST_Y(d.public_location::geometry),'lng',ST_X(d.public_location::geometry),'label',d.location_label,'precision',d.location_precision),'locationLabel',d.location_label,'priorityScore',public.calculate_delta_priority(c.sensitivity_weight,d.impact_level,d.created_at,(select m from dist),city.outskirts_distance_m),'createdAt',d.created_at,'lastActivityAt',d.last_activity_at,'expiresAt',d.expires_at) from counts,c,city;
$$;

create or replace function public.create_delta(input_circle_id uuid,input_city_slug text,input_category_slug text,input_direction text,input_subject text,input_change_type text,input_statement text,input_details text,input_observed_window text,input_impact_level text,input_lat double precision,input_lng double precision,input_location_label text,input_location_precision text default 'point') returns jsonb language plpgsql security definer set search_path = public, extensions, gis as $$
declare uid uuid:=auth.uid(); city public.delta_cities%rowtype; cat public.delta_categories%rowtype; loc geography; publoc geography; dist numeric; target smallint; d public.deltas%rowtype;
begin
 if uid is null then raise exception 'not_authenticated'; end if; if not public.is_member(input_circle_id) then raise exception 'not_circle_member'; end if;
 select * into city from public.delta_cities where slug=input_city_slug and is_active; if city.id is null then raise exception 'city_not_found'; end if;
 select * into cat from public.delta_categories where slug=input_category_slug and is_active; if cat.id is null then raise exception 'category_not_found'; end if;
 if input_lat not between -90 and 90 or input_lng not between -180 and 180 then raise exception 'invalid_coordinates'; end if;
 if input_direction not in ('positive','negative') or input_change_type not in ('faster','slower','cheaper','more_expensive','more_available','less_available','more','less','appeared','disappeared','improved','worsened','other') or input_observed_window not in ('today','last_3_days','last_week','last_2_4_weeks') or input_impact_level not in ('noticeable','strong','critical') or coalesce(input_location_precision,'point') not in ('point','district','city') then raise exception 'invalid_delta_payload'; end if;
 loc:=ST_SetSRID(ST_MakePoint(input_lng,input_lat),4326)::geography; publoc:=ST_SetSRID(ST_MakePoint(round(input_lng::numeric,3)::double precision,round(input_lat::numeric,3)::double precision),4326)::geography;
 dist:=ST_Distance(loc, ST_SetSRID(ST_MakePoint(city.center_lng,city.center_lat),4326)::geography); target:=public.calculate_delta_confirmation_target(cat.sensitivity_weight,dist,city.outskirts_distance_m);
 insert into public.deltas(circle_id,city_id,category_id,created_by,direction,subject,change_type,statement,details,observed_window,impact_level,location,public_location,location_label,location_precision,confirmation_target,status) values(input_circle_id,city.id,cat.id,uid,input_direction,trim(input_subject),input_change_type,trim(input_statement),nullif(trim(coalesce(input_details,'')),''),input_observed_window,input_impact_level,loc,publoc,trim(input_location_label),coalesce(input_location_precision,'point'),target,'new') returning * into d;
 insert into public.delta_reactions(delta_id,user_id,reaction) values(d.id,uid,'confirm');
 return jsonb_build_object('delta', public.delta_card_json(d,uid) || jsonb_build_object('progress',jsonb_build_object('current',1,'target',target)), 'effect', jsonb_build_object('type','created','previousStatus',null,'newStatus','new','message','Дельта опубликована','detail','Сейчас вы первый наблюдатель. Нужны ещё два независимых подтверждения.'));
exception when check_violation then raise exception 'invalid_delta_payload'; end; $$;

create or replace function public.react_to_delta(input_delta_id uuid,input_reaction text) returns jsonb language plpgsql security definer set search_path = public, extensions, gis as $$
declare uid uuid:=auth.uid(); d public.deltas%rowtype; prev text; cc integer; dc integer; next text; msg text; detail text;
begin
 if uid is null then raise exception 'not_authenticated'; end if; if input_reaction not in ('confirm','disconfirm') then raise exception 'invalid_delta_payload'; end if; select * into d from public.deltas where id=input_delta_id; if d.id is null then raise exception 'delta_not_found'; end if; if not public.is_member(d.circle_id) then raise exception 'not_circle_member'; end if; if d.created_by=uid then raise exception 'author_reaction_locked'; end if;
 prev:=d.status; insert into public.delta_reactions(delta_id,user_id,reaction) values(d.id,uid,input_reaction) on conflict(delta_id,user_id) do update set reaction=excluded.reaction;
 select confirm_count, disconfirm_count into cc,dc from public.delta_counts(d.id); next:=public.delta_status_for_counts(cc,dc,d.confirmation_target,d.moderation_state,d.expires_at);
 update public.deltas set status=next, confirmed_at=case when next='confirmed' and confirmed_at is null then now() else confirmed_at end, forked_at=case when next='fork' and forked_at is null then now() else forked_at end, last_activity_at=now() where id=d.id returning * into d;
 msg:=case when next='fork' or input_reaction='disconfirm' then 'Вы создали развилку' when next='confirmed' then 'Дельта подтвердилась' else 'Ваш отклик усилил дельту' end; detail:=case when next='fork' then 'Рядом ситуацию видят по-разному.' when next='checking' and prev <> 'checking' then 'Она перешла в стадию проверки.' when next='confirmed' then 'Достигнут порог независимых подтверждений.' else 'Подтверждение учтено.' end;
 return jsonb_build_object('delta',jsonb_build_object('id',d.id,'status',next,'confirmationTarget',d.confirmation_target,'confirmCount',cc,'disconfirmCount',dc,'progress',jsonb_build_object('current',cc,'target',d.confirmation_target)),'effect',jsonb_build_object('type','reaction','previousStatus',prev,'newStatus',next,'message',msg,'detail',detail));
end; $$;

create or replace function public.get_delta_card(input_delta_id uuid) returns jsonb language plpgsql security definer set search_path = public, extensions, gis as $$ declare uid uuid:=auth.uid(); d public.deltas%rowtype; begin if uid is null then raise exception 'not_authenticated'; end if; select * into d from public.deltas where id=input_delta_id; if d.id is null then raise exception 'delta_not_found'; end if; if not public.is_member(d.circle_id) then raise exception 'not_circle_member'; end if; return public.delta_card_json(d,uid); end; $$;

create or replace function public.find_similar_deltas(input_circle_id uuid,input_city_slug text,input_category_slug text,input_direction text,input_change_type text,input_lat double precision,input_lng double precision,input_radius_m integer default 1000,input_days integer default 14) returns jsonb language plpgsql security definer set search_path = public, extensions, gis as $$ declare uid uuid:=auth.uid(); city_id uuid; cat_id uuid; pt geography; radius integer:=least(3000,greatest(100,coalesce(input_radius_m,1000))); days integer:=least(30,greatest(1,coalesce(input_days,14))); begin if uid is null then raise exception 'not_authenticated'; end if; if not public.is_member(input_circle_id) then raise exception 'not_circle_member'; end if; if input_lat not between -90 and 90 or input_lng not between -180 and 180 then raise exception 'invalid_coordinates'; end if; select id into city_id from public.delta_cities where slug=input_city_slug and is_active; if city_id is null then raise exception 'city_not_found'; end if; select id into cat_id from public.delta_categories where slug=input_category_slug and is_active; if cat_id is null then raise exception 'category_not_found'; end if; pt:=ST_SetSRID(ST_MakePoint(input_lng,input_lat),4326)::geography; return (select coalesce(jsonb_agg(row_to_json(x)::jsonb),'[]'::jsonb) from (select d.id,d.statement,d.status,(select confirm_count from public.delta_counts(d.id)) as "confirmCount",(select disconfirm_count from public.delta_counts(d.id)) as "disconfirmCount",round(ST_Distance(d.location,pt))::integer as "distanceMeters",d.location_label as "locationLabel",d.created_at as "createdAt" from public.deltas d where d.circle_id=input_circle_id and d.city_id=city_id and d.category_id=cat_id and d.direction=input_direction and d.change_type=input_change_type and d.moderation_state='visible' and d.status<>'archived' and d.created_at >= now() - make_interval(days=>days) and ST_DWithin(d.location,pt,radius) order by ST_Distance(d.location,pt), d.created_at desc limit 5) x); end; $$;

create or replace function public.list_deltas_in_view(input_circle_id uuid,input_city_slug text,min_lat double precision,min_lng double precision,max_lat double precision,max_lng double precision,input_direction text default null,input_category_slug text default null,input_status text default null) returns jsonb language plpgsql security definer set search_path = public, extensions, gis as $$ declare uid uuid:=auth.uid(); city public.delta_cities%rowtype; cat_id uuid; begin if uid is null then raise exception 'not_authenticated'; end if; if not public.is_member(input_circle_id) then raise exception 'not_circle_member'; end if; select * into city from public.delta_cities where slug=input_city_slug and is_active; if city.id is null then raise exception 'city_not_found'; end if; if input_category_slug is not null then select id into cat_id from public.delta_categories where slug=input_category_slug and is_active; if cat_id is null then raise exception 'category_not_found'; end if; end if; return (select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from (select d.id,jsonb_build_object('slug',c.slug,'title',c.title,'iconKey',c.icon_key) as category,d.direction,d.statement,d.status,(select confirm_count from public.delta_counts(d.id)) as "confirmCount",(select disconfirm_count from public.delta_counts(d.id)) as "disconfirmCount",d.confirmation_target as "confirmationTarget",public.calculate_delta_priority(c.sensitivity_weight,d.impact_level,d.created_at,ST_Distance(d.location,ST_SetSRID(ST_MakePoint(city.center_lng,city.center_lat),4326)::geography),city.outskirts_distance_m) as "priorityScore",jsonb_build_object('lat',ST_Y(d.public_location::geometry),'lng',ST_X(d.public_location::geometry),'label',d.location_label) as location,d.last_activity_at as "lastActivityAt" from public.deltas d join public.delta_categories c on c.id=d.category_id where d.circle_id=input_circle_id and d.city_id=city.id and d.moderation_state='visible' and d.status<>'archived' and d.expires_at>now() and ST_Intersects(d.public_location::geometry, ST_MakeEnvelope(min_lng,min_lat,max_lng,max_lat,4326)) and (input_direction is null or d.direction=input_direction) and (cat_id is null or d.category_id=cat_id) and (input_status is null or d.status=input_status) order by "priorityScore" desc, d.last_activity_at desc limit 500) x); end; $$;

alter table public.delta_cities enable row level security; alter table public.delta_categories enable row level security; alter table public.deltas enable row level security; alter table public.delta_reactions enable row level security;
drop policy if exists delta_cities_active_select on public.delta_cities; create policy delta_cities_active_select on public.delta_cities for select to authenticated using(is_active);
drop policy if exists delta_categories_active_select on public.delta_categories; create policy delta_categories_active_select on public.delta_categories for select to authenticated using(is_active);
-- No SELECT/INSERT/UPDATE/DELETE policies for deltas or delta_reactions: raw rows include precise location/created_by/user_id and writes go through SECURITY DEFINER RPC only.
revoke all on public.deltas from anon, authenticated; revoke all on public.delta_reactions from anon, authenticated;
grant select on public.delta_cities, public.delta_categories to authenticated;
grant execute on function public.create_delta(uuid,text,text,text,text,text,text,text,text,text,double precision,double precision,text,text) to authenticated;
grant execute on function public.react_to_delta(uuid,text) to authenticated;
grant execute on function public.get_delta_card(uuid) to authenticated;
grant execute on function public.find_similar_deltas(uuid,text,text,text,text,double precision,double precision,integer,integer) to authenticated;
grant execute on function public.list_deltas_in_view(uuid,text,double precision,double precision,double precision,double precision,text,text,text) to authenticated;
notify pgrst, 'reload schema';
