import { describe, expect, it } from 'vitest';
import { demoDeltaMapData } from '../deltaMap/demoDeltaMapData';
import { boundsFromCenterRadius, formatPulseActivity, sortCityItems, sortNearby, sortNearbyMapItems, summarizePulse, titleFor, toPulseItem } from './mobilePulseLogic';

describe('mobile Pulse logic',()=>{
 it('excludes archived, invalid activity and includes exact 24-hour boundary',()=>{const now=new Date('2026-01-02T12:00:00Z');const base=demoDeltaMapData[0];const rows=[{...base,id:'boundary',status:'new' as const,lastActivityAt:'2026-01-01T12:00:00Z'},{...base,id:'bad',status:'checking' as const,lastActivityAt:'bad'},{...base,id:'old-confirmed',status:'confirmed' as const,lastActivityAt:'2025-01-01T00:00:00Z'},{...base,id:'archived',status:'archived' as const,lastActivityAt:now.toISOString()}];expect(summarizePulse(rows,now)).toEqual({activeLast24Hours:1,checkingNow:1,confirmedNow:1,forkNow:0});});
 it('ranks newest, then priority, then stable id',()=>{const base=demoDeltaMapData[0];const rows=[{...base,id:'b',lastActivityAt:'2026-01-01',priorityScore:2},{...base,id:'a',lastActivityAt:'2026-01-01',priorityScore:2},{...base,id:'new',lastActivityAt:'2026-01-02',priorityScore:0}];expect(sortCityItems(rows).map(x=>x.id)).toEqual(['new','a','b']);});
 it('sorts nearby by shortest distance',()=>{const items=demoDeltaMapData.slice(0,2).map(x=>toPulseItem(x));expect(sortNearby(items,items[1].lat,items[1].lng)[0].id).toBe(items[1].id);});
 it('keeps bounds valid at high latitude',()=>{const bounds=boundsFromCenterRadius(89.99,179.99,100000);expect(bounds.minLat).toBeGreaterThanOrEqual(-90);expect(bounds.maxLat).toBeLessThanOrEqual(90);expect(bounds.minLng).toBeGreaterThanOrEqual(-180);expect(bounds.maxLng).toBeLessThanOrEqual(180);});
 it('searches all city rows before selecting nearby items',()=>{const base=demoDeltaMapData[0];const rows=Array.from({length:8},(_,index)=>({...base,id:`delta-${index}`,lastActivityAt:new Date(2026,0,8-index).toISOString(),location:{...base.location,lat:58.01+index*.01}}));const nearest={...rows[7],location:{...rows[7].location,lat:58.0105,lng:56.2502}};rows[7]=nearest;expect(sortCityItems(rows).slice(0,5).map(x=>x.id)).not.toContain(nearest.id);expect(sortNearbyMapItems(rows,58.0105,56.2502)[0].id).toBe(nearest.id);});
 it('formats activity without reading the current clock',()=>{const now=new Date('2026-01-02T12:00:00Z');expect(formatPulseActivity('bad',now)).toBe('время активности неизвестно');expect(formatPulseActivity('2026-01-02T12:02:00Z',now)).toBe('время активности неизвестно');expect(formatPulseActivity('2026-01-02T11:59:30Z',now)).toBe('активность только что');expect(formatPulseActivity('2026-01-02T11:40:00Z',now)).toBe('активность 20 мин. назад');expect(formatPulseActivity('2026-01-02T10:00:00Z',now)).toBe('активность 2 ч. назад');expect(formatPulseActivity('2025-12-31T12:00:00Z',now)).toBe('активность 2 дн. назад');});
 it('prefers a trimmed card subject and falls back honestly',()=>{const item=demoDeltaMapData[0];expect(titleFor(item,{subject:'  Карточка  '})).toBe('Карточка');expect(titleFor(item,{subject:' '})).toBe(item.statement);expect(titleFor({...item,statement:' '},null)).toBe('Изменение без заголовка');});
});
