import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { createEmptyDeltaDraft, restoreDeltaDraft, serializeDeltaDraft, resetDependentFields, validateDeltaStep } from '../deltaCreateLogic';
import { DELTA_CREATE_CATEGORIES, type DeltaCreateDraft } from '../deltaCreateTypes';
import { DELTA_CREATE_PRODUCTION_STORAGE_KEY, buildCreateDeltaInput, canPublishSeparate, createDemoDeltaResult, createDemoReactionResult, mapDeltaPublishError, resetProductionDraftAfterSuccess, shareDeltaPayload } from '../deltaCreateProductionLogic';
import { isLocationComplete, isWithinPermMvpArea, PERM_MVP_AREA_ERROR, shouldResetSimilarDecision } from '../deltaGeoLogic';
import { createDelta, getDeltaCard, loadDeltaCategories, reactToDelta } from '../../deltas/deltaApi';
import { loadDeltaMapContext } from '../../deltaMap/deltaMapLogic';
import { demoCard, demoDeltaMapData } from '../../deltaMap/demoDeltaMapData';
import type { DeltaCard, DeltaCategory, DeltaEffect, ReactToDeltaResult } from '../../deltas/deltaTypes';
import { isDemoMode } from '../../../app/appMode';
import { MobileDeltaChangeScreen } from './MobileDeltaChangeScreen';
import { MobileDeltaLocationScreen } from './MobileDeltaLocationScreen';
import { MobileDeltaReviewScreen } from './MobileDeltaReviewScreen';
import { MobileDeltaCreateResult } from './MobileDeltaCreateResult';
import './mobileDeltaCreate.css';

type Stage='change'|'location'|'review'; type Failed={kind:'create'}|{kind:'confirm';deltaId:string}|null;
function Header({stage,onBack}:{stage:Stage;onBack:()=>void}){const meta=stage==='change'?['Новая Дельта','1/3']:stage==='location'?['Место','2/3']:['Проверка','3/3'];return <header className="mobile-delta-header"><button aria-label={stage==='change'?'Закрыть создание Дельты':'Назад'} onClick={onBack}>{stage==='change'?<svg viewBox="0 0 24 24"><path d="M6 6l12 12M18 6L6 18"/></svg>:<svg viewBox="0 0 24 24"><path d="M15 6l-6 6 6 6"/></svg>}</button><span>{meta[0]}</span><small>{meta[1]}</small></header>}
function changeComplete(d:DeltaCreateDraft){return validateDeltaStep(d,2).concat(validateDeltaStep(d,3)).length===0} function locComplete(d:DeltaCreateDraft){return isLocationComplete(d)&&isWithinPermMvpArea(d.lat,d.lng)} function deriveStage(d:DeltaCreateDraft):Stage{return !changeComplete(d)?'change':!locComplete(d)?'location':'review'}
export function MobileDeltaCreateFlow({mode}:{mode:'production'|'geo-lab'}){const production=mode==='production'; const [params,setParams]=useSearchParams(); const navigate=useNavigate(); const requested=(params.get('stage') as Stage|null)||'change'; const [draft,setDraft]=useState(createEmptyDeltaDraft); const [pending,setPending]=useState<DeltaCreateDraft|null>(()=>restoreDeltaDraft(localStorage.getItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY))); const [errors,setErrors]=useState<string[]>([]); const [locError,setLocError]=useState(''); const [confirmReset,setConfirmReset]=useState(false);
 const [categories,setCategories]=useState<DeltaCategory[]>(isDemoMode?DELTA_CREATE_CATEGORIES:[]); const [catStatus,setCatStatus]=useState<'loading'|'ready'|'empty'|'error'>(isDemoMode?'ready':'loading'); const retryCats=useCallback(()=>{ if(isDemoMode)return; setCatStatus('loading'); loadDeltaCategories().then(c=>{setCategories(c);setCatStatus(c.length?'ready':'empty')}).catch(()=>setCatStatus('error'));},[]); useEffect(()=>{const id=setTimeout(retryCats,0); return()=>clearTimeout(id)},[retryCats]);
 const [circleState,setCircleState]=useState<'loading'|'ready'|'no-circle'|'error'>(isDemoMode||!production?'ready':'loading'); const [circleContext,setCircleContext]=useState<{circleId:string;citySlug:string}|null>(isDemoMode||!production?{circleId:'demo-circle',citySlug:'perm'}:null); const loadCircle=useCallback(()=>{if(!production||isDemoMode)return; setCircleState('loading'); loadDeltaMapContext().then(ctx=>{setCircleContext(ctx);setCircleState(ctx?'ready':'no-circle')}).catch(()=>setCircleState('error'))},[production]); useEffect(()=>{const id=setTimeout(loadCircle,0);return()=>clearTimeout(id)},[loadCircle]);
 const [result,setResult]=useState<{mode:'created_new'|'confirmed_existing';delta:DeltaCard;reaction?:ReactToDeltaResult;effect?:DeltaEffect}|null>(null); const [publishing,setPublishing]=useState(false); const pubRef=useRef(false); const [failed,setFailed]=useState<Failed>(null); const [publishError,setPublishError]=useState(''); const [authorLocked,setAuthorLocked]=useState(false); const [shareStatus,setShareStatus]=useState('');
 const update=useCallback((patch:Partial<DeltaCreateDraft>, changed?:string)=>setDraft(cur=>{let next={...cur,...patch}; if(changed==='direction'||changed==='subject'||changed==='changeType') next=resetDependentFields(next,changed); if(changed&&shouldResetSimilarDecision(changed)) next={...next,selectedSimilarDeltaId:null,similarDecision:null}; return next;}),[]);
 useEffect(()=>{if(draft.subject||draft.statement||draft.lat!=null||draft.locationLabel){const id=setTimeout(()=>localStorage.setItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY,serializeDeltaDraft({...draft,currentStep: requested==='review'?4:requested==='location'?1:2})),200);return()=>clearTimeout(id)}},[draft,requested]);
 const active:Stage = requested==='review'?'review':requested==='location'?'location':'change'; useEffect(()=>{const allowed=deriveStage(draft); if(active==='review'&&allowed!=='review') setParams(allowed==='location'?{stage:'location'}:{}, {replace:true}); if(active==='location'&&allowed==='change') setParams({}, {replace:true});},[active,draft,setParams]);
 const go=(s:Stage, replace=false)=>setParams(s==='change'?{}:{stage:s}, {replace}); const back=()=> active==='change'?navigate('/pulse'):go(active==='review'?'location':'change'); const continueChange=()=>{const e=[...validateDeltaStep(draft,2),...validateDeltaStep(draft,3)]; setErrors(e); if(e.length){document.querySelector('.mobile-delta-alert')?.scrollIntoView({block:'center'});return} go('location')}; const continueLocation=()=>{if(!locComplete(draft)){setLocError(!isWithinPermMvpArea(draft.lat,draft.lng)?PERM_MVP_AREA_ERROR:'Выберите точку');return} setLocError(''); go('review')};
 const begin=(f:Failed)=>{if(pubRef.current)return false; pubRef.current=true; setPublishing(true); setFailed(f); setPublishError(''); setAuthorLocked(false); return true}; const finish=()=>{pubRef.current=false; setPublishing(false)};
 const createSeparate=useCallback(async()=>{if(!begin({kind:'create'}))return; try{ if(!canPublishSeparate(draft)) throw new Error('invalid_delta_payload'); if(isDemoMode){const r=createDemoDeltaResult(draft); localStorage.removeItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY); setResult({mode:'created_new',delta:r.delta,effect:r.effect}); return} if(!circleContext) throw new Error('not_circle_member'); const r=await createDelta(buildCreateDeltaInput(draft,circleContext.circleId)); localStorage.removeItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY); setResult({mode:'created_new',delta:r.delta,effect:r.effect}); }catch(e){setPublishError(mapDeltaPublishError(e))}finally{finish()}},[draft,circleContext]);
 const confirmExisting=useCallback(async(id:string)=>{if(!begin({kind:'confirm',deltaId:id}))return; try{ if(isDemoMode){const card=demoCard(id)??demoCard(demoDeltaMapData[0].id); if(!card) throw new Error('delta_not_found'); const reaction=createDemoReactionResult(card); localStorage.removeItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY); setResult({mode:'confirmed_existing',delta:card,reaction}); return} const reaction=await reactToDelta(id,'confirm'); const card=await getDeltaCard(id); localStorage.removeItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY); setResult({mode:'confirmed_existing',delta:card,reaction}); }catch(e){const msg=mapDeltaPublishError(e); if(msg==='Первая отметка автора уже закреплена.') setAuthorLocked(true); else setPublishError(msg)}finally{finish()}},[]);
 const retryFailed=()=>{if(failed?.kind==='confirm') void confirmExisting(failed.deltaId); else if(failed?.kind==='create') void createSeparate()}; const clearAll=()=>{localStorage.removeItem(DELTA_CREATE_PRODUCTION_STORAGE_KEY);setDraft(createEmptyDeltaDraft());setPending(null);setConfirmReset(false);setResult(null);go('change',true)};
 if(result) return <MobileDeltaCreateResult mode={result.mode} delta={result.delta} reaction={result.reaction} effect={result.effect} onReset={()=>{clearAll();setDraft(resetProductionDraftAfterSuccess())}} onShare={async p=>setShareStatus(await shareDeltaPayload(p))} shareStatus={shareStatus}/>;
 if(circleState==='loading') return <section className="mobile-delta-flow"><h1>Проверяем доступ к кругу</h1></section>; if(circleState==='error') return <section className="mobile-delta-flow"><h1>Не удалось проверить доступ к кругу</h1><button onClick={loadCircle}>Повторить</button><button onClick={()=>navigate('/pulse')}>Вернуться в Пульс</button></section>; if(circleState==='no-circle') return <section className="mobile-delta-flow"><h1>Нужно войти в круг</h1><button onClick={()=>navigate('/pulse')}>Вернуться в Пульс</button></section>;
 if(pending) return <section className="mobile-delta-flow"><div className="mobile-delta-resume"><h1>Продолжить Дельту?</h1><p>Черновик сохранён автоматически.</p>{(pending.statement||pending.subject)&&<strong>{pending.statement||pending.subject}</strong>}{pending.locationLabel&&<p>{pending.locationLabel}</p>}<button className="mobile-delta-primary" onClick={()=>{setDraft(pending);setPending(null);go(deriveStage(pending))}}>Продолжить</button><button onClick={()=>setConfirmReset(true)}>Начать заново</button>{confirmReset&&<div role="alertdialog" className="mobile-delta-alert"><h2>Очистить черновик?</h2><button onClick={()=>setConfirmReset(false)}>Отмена</button><button onClick={clearAll}>Да, очистить</button></div>}</div></section>;
 const action=active==='change'?<button className="mobile-delta-primary" onClick={continueChange}>Продолжить</button>:active==='location'?<button className="mobile-delta-primary" disabled={!locComplete(draft)} onClick={continueLocation}>{locComplete(draft)?'Подтвердить место':'Выберите точку'}</button>:null;
 return <section className="mobile-delta-flow"><Header stage={active} onBack={back}/><div className="mobile-delta-content">{active==='change'&&<MobileDeltaChangeScreen draft={draft} update={update} categories={categories} catStatus={catStatus} retry={retryCats} errors={errors}/>} {active==='location'&&<MobileDeltaLocationScreen draft={draft} update={update} error={locError}/>} {active==='review'&&<MobileDeltaReviewScreen draft={draft} update={(p)=>{ if(p.currentStep===1) go('location'); else if(p.currentStep===2) go('change'); else update(p); }} categories={categories} circleContext={circleContext} publishing={publishing} onCreateSeparate={createSeparate} onConfirmExisting={confirmExisting} publishError={publishError} authorLocked={authorLocked} onRetryFailed={retryFailed}/>}</div>{action&&<div className="mobile-delta-actionbar">{action}</div>}</section>;
}
